REDIS_HOST=redis
REDIS_PORT=6379

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0password

RAILS_MAX_THREADS=8
RAILS_ENV=production
INTERVAL=0.1
COUNT=8

ENABLE_BATCHED_SUBMISSIONS=true
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
