-- k_b.sql  10~12획 常用漢字 (제외 목록 미포함분) N1 INSERT
-- 담당: 획수 10~12획 위주 / A담당(1~9획)과 비중복
-- 중복가드: WHERE NOT EXISTS
-- _existing_kanji.txt 대조 완료 — 미포함 글자만 수록
-- 총 62자

-- ============================================================
-- 10획
-- ============================================================
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '倦','ケン','う.む','게을릴 권','N1','[{"word":"倦怠","reading":"けんたい","meaning":"권태"},{"word":"倦む","reading":"うむ","meaning":"싫증 나다"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='倦');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '倉','ソウ','くら','곳집 창','N1','[{"word":"倉庫","reading":"そうこ","meaning":"창고"},{"word":"倉敷","reading":"くらしき","meaning":"구라시키(지명)"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='倉');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '剥','ハク','は.ぐ','벗길 박','N1','[{"word":"剥奪","reading":"はくだつ","meaning":"박탈"},{"word":"剥製","reading":"はくせい","meaning":"박제"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='剥');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '唄','バイ','うた','노래 배','N1','[{"word":"小唄","reading":"こうた","meaning":"소창(단가)"},{"word":"唄う","reading":"うたう","meaning":"노래하다"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='唄');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '孫','ソン','まご','손자 손','N1','[{"word":"孫子","reading":"まごこ","meaning":"손자"},{"word":"子孫","reading":"しそん","meaning":"자손"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='孫');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '宰','サイ','','재상 재','N1','[{"word":"主宰","reading":"しゅさい","meaning":"주재"},{"word":"宰相","reading":"さいしょう","meaning":"재상"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='宰');
-- 家: 제외목록에 있음 → 생략
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '座','ザ','すわ.る','앉을 좌','N1','[{"word":"座席","reading":"ざせき","meaning":"좌석"},{"word":"星座","reading":"せいざ","meaning":"별자리"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='座');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '庭','テイ','にわ','뜰 정','N1','[{"word":"庭園","reading":"ていえん","meaning":"정원"},{"word":"家庭","reading":"かてい","meaning":"가정"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='庭');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '根','コン','ね','뿌리 근','N1','[{"word":"根拠","reading":"こんきょ","meaning":"근거"},{"word":"根本","reading":"こんぽん","meaning":"근본"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='根');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '格','カク','','격식 격','N1','[{"word":"格差","reading":"かくさ","meaning":"격차"},{"word":"価格","reading":"かかく","meaning":"가격"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='格');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '殺','サツ','ころ.す','죽일 살','N1','[{"word":"殺人","reading":"さつじん","meaning":"살인"},{"word":"抹殺","reading":"まっさつ","meaning":"말살"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='殺');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '流','リュウ','なが.れる','흐를 류','N1','[{"word":"流通","reading":"りゅうつう","meaning":"유통"},{"word":"流行","reading":"りゅうこう","meaning":"유행"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='流');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '益','エキ','ます','더할 익','N1','[{"word":"利益","reading":"りえき","meaning":"이익"},{"word":"公益","reading":"こうえき","meaning":"공익"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='益');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '秘','ヒ','ひ.める','숨길 비','N1','[{"word":"秘密","reading":"ひみつ","meaning":"비밀"},{"word":"神秘","reading":"しんぴ","meaning":"신비"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='秘');
-- 株: 제외목록에 있음 → 생략
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '般','ハン','','가지 반','N1','[{"word":"一般","reading":"いっぱん","meaning":"일반"},{"word":"全般","reading":"ぜんぱん","meaning":"전반"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='般');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '逃','トウ','に.げる','도망할 도','N1','[{"word":"逃亡","reading":"とうぼう","meaning":"도망"},{"word":"逃走","reading":"とうそう","meaning":"도주"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='逃');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '骨','コツ','ほね','뼈 골','N1','[{"word":"骨格","reading":"こっかく","meaning":"골격"},{"word":"骨折","reading":"こっせつ","meaning":"골절"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='骨');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '航','コウ','','항해할 항','N1','[{"word":"航空","reading":"こうくう","meaning":"항공"},{"word":"航海","reading":"こうかい","meaning":"항해"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='航');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '訓','クン','','가르칠 훈','N1','[{"word":"訓練","reading":"くんれん","meaning":"훈련"},{"word":"訓読み","reading":"くんよみ","meaning":"훈독"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='訓');
-- 郊: 제외목록에 있음 → 생략
-- 酌: 제외목록에 있음 → 생략

-- ============================================================
-- 11획
-- ============================================================
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '略','リャク','','간략할 략','N1','[{"word":"省略","reading":"しょうりゃく","meaning":"생략"},{"word":"略語","reading":"りゃくご","meaning":"약어"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='略');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '張','チョウ','は.る','펼 장','N1','[{"word":"主張","reading":"しゅちょう","meaning":"주장"},{"word":"緊張","reading":"きんちょう","meaning":"긴장"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='張');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '帯','タイ','お.びる','띠 대','N1','[{"word":"地帯","reading":"ちたい","meaning":"지대"},{"word":"帯同","reading":"たいどう","meaning":"대동"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='帯');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '得','トク','え.る','얻을 득','N1','[{"word":"取得","reading":"しゅとく","meaning":"취득"},{"word":"納得","reading":"なっとく","meaning":"납득"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='得');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '授','ジュ','さず.ける','줄 수','N1','[{"word":"授業","reading":"じゅぎょう","meaning":"수업"},{"word":"教授","reading":"きょうじゅ","meaning":"교수"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='授');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '掃','ソウ','は.く','쓸 소','N1','[{"word":"掃除","reading":"そうじ","meaning":"청소"},{"word":"一掃","reading":"いっそう","meaning":"일소"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='掃');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '採','サイ','と.る','캘 채','N1','[{"word":"採用","reading":"さいよう","meaning":"채용"},{"word":"採決","reading":"さいけつ","meaning":"채결"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='採');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '探','タン','さが.す','찾을 탐','N1','[{"word":"探偵","reading":"たんてい","meaning":"탐정"},{"word":"探求","reading":"たんきゅう","meaning":"탐구"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='探');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '清','セイ','きよ.い','맑을 청','N1','[{"word":"清潔","reading":"せいけつ","meaning":"청결"},{"word":"清澄","reading":"せいちょう","meaning":"청징"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='清');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '盛','セイ','さか.る','성할 성','N1','[{"word":"盛況","reading":"せいきょう","meaning":"성황"},{"word":"全盛","reading":"ぜんせい","meaning":"전성"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='盛');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '移','イ','うつ.る','옮길 이','N1','[{"word":"移動","reading":"いどう","meaning":"이동"},{"word":"移住","reading":"いじゅう","meaning":"이주"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='移');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '菜','サイ','な','나물 채','N1','[{"word":"野菜","reading":"やさい","meaning":"채소"},{"word":"菜食","reading":"さいしょく","meaning":"채식"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='菜');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '著','チョ','いちじる.しい','나타날 저','N1','[{"word":"著者","reading":"ちょしゃ","meaning":"저자"},{"word":"著作","reading":"ちょさく","meaning":"저작"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='著');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '救','キュウ','すく.う','구할 구','N1','[{"word":"救助","reading":"きゅうじょ","meaning":"구조"},{"word":"救済","reading":"きゅうさい","meaning":"구제"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='救');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '貨','カ','','재물 화','N1','[{"word":"貨物","reading":"かもつ","meaning":"화물"},{"word":"通貨","reading":"つうか","meaning":"통화"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='貨');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '速','ソク','はや.い','빠를 속','N1','[{"word":"速度","reading":"そくど","meaning":"속도"},{"word":"高速","reading":"こうそく","meaning":"고속"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='速');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '球','キュウ','たま','공 구','N1','[{"word":"球場","reading":"きゅうじょう","meaning":"구장"},{"word":"地球","reading":"ちきゅう","meaning":"지구"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='球');
-- 疎: 제외목록에 있음 → 생략
-- 渋: 제외목록에 있음 → 생략
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '雀','ジャク','すずめ','참새 작','N1','[{"word":"雀荘","reading":"じゃんそう","meaning":"마작장"},{"word":"雀斑","reading":"そばかす","meaning":"주근깨"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='雀');
-- 鹿: 제외목록에 있음 → 생략
-- 麻: 제외목록에 있음 → 생략
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '都','ト','みやこ','도읍 도','N1','[{"word":"都市","reading":"とし","meaning":"도시"},{"word":"首都","reading":"しゅと","meaning":"수도"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='都');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '黄','オウ','き','누를 황','N1','[{"word":"黄金","reading":"おうごん","meaning":"황금"},{"word":"黄色","reading":"きいろ","meaning":"노란색"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='黄');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '雪','セツ','ゆき','눈 설','N1','[{"word":"雪害","reading":"せつがい","meaning":"설해"},{"word":"降雪","reading":"こうせつ","meaning":"강설"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='雪');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '魚','ギョ','さかな','물고기 어','N1','[{"word":"魚介","reading":"ぎょかい","meaning":"어패류"},{"word":"深海魚","reading":"しんかいぎょ","meaning":"심해어"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='魚');

-- ============================================================
-- 12획
-- ============================================================
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '傘','サン','かさ','우산 산','N1','[{"word":"傘下","reading":"さんか","meaning":"산하"},{"word":"雨傘","reading":"あまがさ","meaning":"우산"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='傘');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '勝','ショウ','か.つ','이길 승','N1','[{"word":"勝利","reading":"しょうり","meaning":"승리"},{"word":"勝負","reading":"しょうぶ","meaning":"승부"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='勝');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '喉','コウ','のど','목구멍 후','N1','[{"word":"喉頭","reading":"こうとう","meaning":"후두"},{"word":"喉仏","reading":"のどぼとけ","meaning":"목젖"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='喉');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '敬','ケイ','うやま.う','공경할 경','N1','[{"word":"敬語","reading":"けいご","meaning":"경어"},{"word":"尊敬","reading":"そんけい","meaning":"존경"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='敬');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '植','ショク','う.える','심을 식','N1','[{"word":"植物","reading":"しょくぶつ","meaning":"식물"},{"word":"植林","reading":"しょくりん","meaning":"식림"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='植');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '幅','フク','はば','폭 폭','N1','[{"word":"幅広い","reading":"はばひろい","meaning":"폭넓다"},{"word":"幅員","reading":"ふくいん","meaning":"폭원"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='幅');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '提','テイ','さ.げる','끌 제','N1','[{"word":"提案","reading":"ていあん","meaning":"제안"},{"word":"提供","reading":"ていきょう","meaning":"제공"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='提');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '絵','カイ','え','그림 회','N1','[{"word":"絵画","reading":"かいが","meaning":"회화"},{"word":"絵本","reading":"えほん","meaning":"그림책"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='絵');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '須','ス','すべから.く','모름지기 수','N1','[{"word":"必須","reading":"ひっす","meaning":"필수"},{"word":"須要","reading":"すよう","meaning":"필요"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='須');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '番','バン','','차례 번','N1','[{"word":"番号","reading":"ばんごう","meaning":"번호"},{"word":"番組","reading":"ばんぐみ","meaning":"프로그램"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='番');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '登','トウ','のぼ.る','오를 등','N1','[{"word":"登場","reading":"とうじょう","meaning":"등장"},{"word":"登録","reading":"とうろく","meaning":"등록"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='登');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '程','テイ','ほど','정도 정','N1','[{"word":"程度","reading":"ていど","meaning":"정도"},{"word":"日程","reading":"にってい","meaning":"일정"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='程');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '策','サク','','꾀 책','N1','[{"word":"対策","reading":"たいさく","meaning":"대책"},{"word":"政策","reading":"せいさく","meaning":"정책"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='策');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '童','ドウ','わらべ','아이 동','N1','[{"word":"童話","reading":"どうわ","meaning":"동화"},{"word":"児童","reading":"じどう","meaning":"아동"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='童');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '然','ゼン','','그럴 연','N1','[{"word":"自然","reading":"しぜん","meaning":"자연"},{"word":"当然","reading":"とうぜん","meaning":"당연"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='然');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '猫','ビョウ','ねこ','고양이 묘','N1','[{"word":"猫背","reading":"ねこぜ","meaning":"구부정한 등"},{"word":"野良猫","reading":"のらねこ","meaning":"들고양이"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='猫');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '賀','ガ','','하례할 하','N1','[{"word":"祝賀","reading":"しゅくが","meaning":"축하"},{"word":"賀状","reading":"がじょう","meaning":"연하장"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='賀');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '軽','ケイ','かる.い','가벼울 경','N1','[{"word":"軽減","reading":"けいげん","meaning":"경감"},{"word":"軽率","reading":"けいそつ","meaning":"경솔"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='軽');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '遅','チ','おく.れる','늦을 지','N1','[{"word":"遅延","reading":"ちえん","meaning":"지연"},{"word":"遅刻","reading":"ちこく","meaning":"지각"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='遅');
-- 雰: 제외목록에 있음 → 생략
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '雁','ガン','かり','기러기 안','N1','[{"word":"雁行","reading":"がんこう","meaning":"안행"},{"word":"雁皮","reading":"がんぴ","meaning":"안피(종이 원료)"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='雁');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '雲','ウン','くも','구름 운','N1','[{"word":"雲海","reading":"うんかい","meaning":"운해"},{"word":"積乱雲","reading":"せきらんうん","meaning":"적란운"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='雲');
