-- k_c.sql: 常用漢字 N1追加 (13획 이상 위주, 배치 C)
-- 배치 1/3

INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嗾','ソウ','そそのか・す','부추길 주','N1','[{"word":"嗾ける","reading":"そそのかす","meaning":"부추기다"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嗾');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嘉','カ','','아름다울 가','N1','[{"word":"嘉納","reading":"かのう","meaning":"기쁘게 받아들임"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嘉');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嘗','ショウ','かつ・て、な・める','일찍이 상','N1','[{"word":"嘗て","reading":"かつて","meaning":"일찍이"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嘗');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '噌','ソ・ショウ','','시끄러울 증','N1','[{"word":"味噌","reading":"みそ","meaning":"된장"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='噌');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '寥','リョウ','','쓸쓸할 료','N1','[{"word":"寂寥","reading":"せきりょう","meaning":"적막"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='寥');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嶺','レイ・リョウ','みね','재 령','N1','[{"word":"山嶺","reading":"さんれい","meaning":"산마루"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嶺');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '廓','カク','くるわ','넓을 곽','N1','[{"word":"輪廓","reading":"りんかく","meaning":"윤곽"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='廓');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '廟','ビョウ','','사당 묘','N1','[{"word":"廟堂","reading":"びょうどう","meaning":"묘당"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='廟');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '徴','チョウ','','징할 징','N1','[{"word":"特徴","reading":"とくちょう","meaning":"특징"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='徴');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '搔','ソウ','か・く','긁을 소','N1','[{"word":"搔く","reading":"かく","meaning":"긁다"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='搔');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '摺','ショウ','す・る','접을 습','N1','[{"word":"摺り合わせ","reading":"すりあわせ","meaning":"조율"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='摺');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '撚','ネン','よ・る','비틀 연','N1','[{"word":"撚り糸","reading":"よりいと","meaning":"꼰 실"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='撚');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '撫','ブ','な・でる','어루만질 무','N1','[{"word":"撫でる","reading":"なでる","meaning":"쓰다듬다"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='撫');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '擢','タク','ぬき・んでる','뽑을 탁','N1','[{"word":"抜擢","reading":"ばってき","meaning":"발탁"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='擢');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '暈','ウン','かさ','달무리 훈','N1','[{"word":"光暈","reading":"こううん","meaning":"광환"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='暈');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '暢','チョウ','','펼 창','N1','[{"word":"伸暢","reading":"しんちょう","meaning":"신창"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='暢');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '楠','ナン','くすのき','녹나무 남','N1','[{"word":"楠木","reading":"くすのき","meaning":"녹나무"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='楠');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '楡','ユ','にれ','느릅나무 유','N1','[{"word":"楡の木","reading":"にれのき","meaning":"느릅나무"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='楡');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '槌','ツイ','つち','망치 추','N1','[{"word":"木槌","reading":"きづち","meaning":"나무망치"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='槌');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '歎','タン','なげ・く','탄식할 탄','N1','[{"word":"歎息","reading":"たんそく","meaning":"탄식"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='歎');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '毀','キ','こぼ・つ','헐 훼','N1','[{"word":"毀損","reading":"きそん","meaning":"훼손"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='毀');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '漱','ソウ','くちすす・ぐ','양치할 수','N1','[{"word":"漱石","reading":"そうせき","meaning":"수석 (나쓰메 소세키)"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='漱');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '熨','イ・ウン','の・す','다림질 위','N1','[{"word":"熨斗","reading":"のし","meaning":"노시 (포장 장식)"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='熨');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '燎','リョウ','かがりび','횃불 료','N1','[{"word":"燎原","reading":"りょうげん","meaning":"요원"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='燎');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '燦','サン','きらめ・く','빛날 찬','N1','[{"word":"燦然","reading":"さんぜん","meaning":"찬연"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='燦');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '璋','ショウ','','옥그릇 장','N1','[{"word":"璋瓚","reading":"しょうさん","meaning":"장찬"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='璋');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '瞭','リョウ','','밝을 료','N1','[{"word":"明瞭","reading":"めいりょう","meaning":"명료"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='瞭');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '磐','バン','いわ','너럭바위 반','N1','[{"word":"磐石","reading":"ばんじゃく","meaning":"반석"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='磐');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '稟','ヒン・リン','','여쭐 품','N1','[{"word":"稟議","reading":"りんぎ","meaning":"품의"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='稟');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '稽','ケイ','かんが・える','상고할 계','N1','[{"word":"稽古","reading":"けいこ","meaning":"연습"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='稽');
