-- k_c_batch3.sql: 常用漢字 N1追加 (13획 이상, 배치 C-3, 検証済)
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嘉','カ','よし','아름다울 가','N1','[{"word":"嘉納","reading":"かのう","meaning":"기쁘게 받아들임"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嘉');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嘗','ショウ','かつ・て','일찍이 상','N1','[{"word":"嘗て","reading":"かつて","meaning":"일찍이"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嘗');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '嶺','レイ','みね','재 령','N1','[{"word":"嶺","reading":"みね","meaning":"산마루"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='嶺');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '徴','チョウ','','부를 징','N1','[{"word":"特徴","reading":"とくちょう","meaning":"특징"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='徴');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '毀','キ','こぼ・つ','헐 훼','N1','[{"word":"毀損","reading":"きそん","meaning":"훼손"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='毀');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '瞭','リョウ','','밝을 료','N1','[{"word":"明瞭","reading":"めいりょう","meaning":"명료"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='瞭');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '稽','ケイ','','상고할 계','N1','[{"word":"稽古","reading":"けいこ","meaning":"연습"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='稽');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '罹','リ','かか・る','걸릴 리','N1','[{"word":"罹患","reading":"りかん","meaning":"이환"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='罹');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '醤','ショウ','ひしお','장 장','N1','[{"word":"醤油","reading":"しょうゆ","meaning":"간장"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='醤');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '頒','ハン','','나눌 반','N1','[{"word":"頒布","reading":"はんぷ","meaning":"반포"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='頒');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '凛','リン','','늠름할 름','N1','[{"word":"凛々しい","reading":"りりしい","meaning":"늠름하다"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='凛');
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, jlpt_level, example_words) SELECT '賑','シン','にぎ・わう','번성할 진','N1','[{"word":"賑わい","reading":"にぎわい","meaning":"번성함"}]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM jlpt_kanji WHERE kanji='賑');
