-- N1 名詞: 文化・芸術・歴史・宗教・伝統・思想・教育 (150語)
-- v3_culture.sql

INSERT INTO jlpt_vocabulary (word, reading, meaning_ko, jlpt_level, part_of_speech)

-- 1. 文化・風潮・風習 (25語)
SELECT '風潮','ふうちょう','풍조, 시대의 흐름','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='風潮')
UNION ALL SELECT '風習','ふうしゅう','풍습, 관습','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='風習')
UNION ALL SELECT '儀式','ぎしき','의식, 의례','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='儀式')
UNION ALL SELECT '伝承','でんしょう','전승, 구전','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='伝承')
UNION ALL SELECT '風土','ふうど','풍토, 기후와 토지','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='風土')
UNION ALL SELECT '民俗','みんぞく','민속','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='民俗')
UNION ALL SELECT '土着','どちゃく','토착','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='土着')
UNION ALL SELECT '習俗','しゅうぞく','습속, 풍속','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='習俗')
UNION ALL SELECT '礼節','れいせつ','예절','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='礼節')
UNION ALL SELECT '礼儀','れいぎ','예의','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='礼儀')
UNION ALL SELECT '作法','さほう','예법, 법도','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='作法')
UNION ALL SELECT '様式','ようしき','양식, 형식','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='様式')
UNION ALL SELECT '形式','けいしき','형식','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='形式')
UNION ALL SELECT '典礼','てんれい','전례, 의전','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='典礼')
UNION ALL SELECT '祭祀','さいし','제사, 제례','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='祭祀')
UNION ALL SELECT '祭典','さいてん','제전, 축제','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='祭典')
UNION ALL SELECT '慶事','けいじ','경사, 경조사','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='慶事')
UNION ALL SELECT '冠婚葬祭','かんこんそうさい','관혼상제','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='冠婚葬祭')
UNION ALL SELECT '葬儀','そうぎ','장례, 장의','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='葬儀')
UNION ALL SELECT '追悼','ついとう','추도','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='追悼')
UNION ALL SELECT '風物詩','ふうぶつし','풍물시, 계절 풍경','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='風物詩')
UNION ALL SELECT '風情','ふぜい','풍정, 정취, 운치','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='風情')
UNION ALL SELECT '情緒','じょうちょ','정서, 정취','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='情緒')
UNION ALL SELECT '趣','おもむき','취향, 풍취, 뉘앙스','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='趣')
UNION ALL SELECT '余韻','よいん','여운','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='余韻')

-- 2. 芸術・文芸 (25語)
UNION ALL SELECT '韻律','いんりつ','운율','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='韻律')
UNION ALL SELECT '詩歌','しいか','시가, 시','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='詩歌')
UNION ALL SELECT '和歌','わか','와카(일본 전통 시)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='和歌')
UNION ALL SELECT '俳句','はいく','하이쿠','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='俳句')
UNION ALL SELECT '散文','さんぶん','산문','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='散文')
UNION ALL SELECT '韻文','いんぶん','운문','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='韻文')
UNION ALL SELECT '文芸','ぶんげい','문예','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='文芸')
UNION ALL SELECT '文学','ぶんがく','문학','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='文学')
UNION ALL SELECT '古典','こてん','고전','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='古典')
UNION ALL SELECT '劇作','げきさく','극작(희곡 창작)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='劇作')
UNION ALL SELECT '脚本','きゃくほん','각본, 시나리오','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='脚本')
UNION ALL SELECT '演出','えんしゅつ','연출','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='演出')
UNION ALL SELECT '書道','しょどう','서예','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='書道')
UNION ALL SELECT '絵画','かいが','회화, 그림','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='絵画')
UNION ALL SELECT '彫刻','ちょうこく','조각','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='彫刻')
UNION ALL SELECT '陶芸','とうげい','도예','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='陶芸')
UNION ALL SELECT '工芸','こうげい','공예','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='工芸')
UNION ALL SELECT '伝統芸能','でんとうげいのう','전통 예능','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='伝統芸能')
UNION ALL SELECT '能楽','のうがく','능악(일본 전통 연극)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='能楽')
UNION ALL SELECT '歌舞伎','かぶき','가부키','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='歌舞伎')
UNION ALL SELECT '落語','らくご','만담, 라쿠고','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='落語')
UNION ALL SELECT '芸術性','げいじゅつせい','예술성','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='芸術性')
UNION ALL SELECT '美意識','びいしき','미의식, 미적 감각','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='美意識')
UNION ALL SELECT '審美','しんび','심미, 아름다움을 감별함','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='審美')
UNION ALL SELECT '鑑賞','かんしょう','감상(예술 작품을 즐김)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='鑑賞')

-- 3. 歴史・社会 (25語)
UNION ALL SELECT '変遷','へんせん','변천','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='変遷')
UNION ALL SELECT '興亡','こうぼう','흥망','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='興亡')
UNION ALL SELECT '遺産','いさん','유산','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='遺産')
UNION ALL SELECT '系譜','けいふ','계보','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='系譜')
UNION ALL SELECT '史跡','しせき','사적, 유적','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='史跡')
UNION ALL SELECT '遺跡','いせき','유적','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='遺跡')
UNION ALL SELECT '旧跡','きゅうせき','구적, 옛 유적','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='旧跡')
UNION ALL SELECT '古代','こだい','고대','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='古代')
UNION ALL SELECT '中世','ちゅうせい','중세','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='中世')
UNION ALL SELECT '近世','きんせい','근세','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='近世')
UNION ALL SELECT '近代','きんだい','근대','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='近代')
UNION ALL SELECT '現代','げんだい','현대','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='現代')
UNION ALL SELECT '封建','ほうけん','봉건','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='封建')
UNION ALL SELECT '武家','ぶけ','무가, 무사 가문','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='武家')
UNION ALL SELECT '幕府','ばくふ','막부','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='幕府')
UNION ALL SELECT '藩','はん','번(에도시대 영지)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='藩')
UNION ALL SELECT '征服','せいふく','정복','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='征服')
UNION ALL SELECT '侵略','しんりゃく','침략','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='侵略')
UNION ALL SELECT '植民地','しょくみんち','식민지','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='植民地')
UNION ALL SELECT '開国','かいこく','개국, 개항','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='開国')
UNION ALL SELECT '維新','いしん','유신','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='維新')
UNION ALL SELECT '近代化','きんだいか','근대화','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='近代化')
UNION ALL SELECT '文明開化','ぶんめいかいか','문명 개화','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='文明開化')
UNION ALL SELECT '史観','しかん','사관, 역사 관점','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='史観')
UNION ALL SELECT '歴史観','れきしかん','역사관','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='歴史観')

-- 4. 宗教・信仰 (25語)
UNION ALL SELECT '信仰','しんこう','신앙','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='信仰')
UNION ALL SELECT '教義','きょうぎ','교의, 교리','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='教義')
UNION ALL SELECT '宗派','しゅうは','종파','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='宗派')
UNION ALL SELECT '宗旨','しゅうし','종지, 종교의 근본 취지','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='宗旨')
UNION ALL SELECT '布教','ふきょう','포교, 전도','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='布教')
UNION ALL SELECT '改宗','かいしゅう','개종','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='改宗')
UNION ALL SELECT '啓示','けいじ','계시','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='啓示')
UNION ALL SELECT '悟り','さとり','깨달음, 득도','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='悟り')
UNION ALL SELECT '修行','しゅぎょう','수행, 수련','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='修行')
UNION ALL SELECT '巡礼','じゅんれい','순례','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='巡礼')
UNION ALL SELECT '参拝','さんぱい','참배','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='参拝')
UNION ALL SELECT '祈祷','きとう','기도, 기원','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='祈祷')
UNION ALL SELECT '霊魂','れいこん','영혼','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='霊魂')
UNION ALL SELECT '輪廻','りんね','윤회','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='輪廻')
UNION ALL SELECT '因果','いんが','인과, 인과응보','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='因果')
UNION ALL SELECT '業','ごう','업(카르마)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='業')
UNION ALL SELECT '煩悩','ぼんのう','번뇌','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='煩悩')
UNION ALL SELECT '解脱','げだつ','해탈','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='解脱')
UNION ALL SELECT '冥福','めいふく','명복','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='冥福')
UNION ALL SELECT '神道','しんとう','신도(일본 전통 종교)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='神道')
UNION ALL SELECT '神社','じんじゃ','신사(신을 모시는 곳)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='神社')
UNION ALL SELECT '寺院','じいん','사원, 절','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='寺院')
UNION ALL SELECT '聖典','せいてん','성전(경전)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='聖典')
UNION ALL SELECT '経典','きょうてん','경전','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='経典')
UNION ALL SELECT '戒律','かいりつ','계율','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='戒律')

-- 5. 思想・哲学・倫理 (25語)
UNION ALL SELECT '理念','りねん','이념','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='理念')
UNION ALL SELECT '信念','しんねん','신념','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='信念')
UNION ALL SELECT '倫理','りんり','윤리','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='倫理')
UNION ALL SELECT '道徳','どうとく','도덕','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='道徳')
UNION ALL SELECT '哲学','てつがく','철학','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='哲学')
UNION ALL SELECT '思想','しそう','사상','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='思想')
UNION ALL SELECT '価値観','かちかん','가치관','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='価値観')
UNION ALL SELECT '世界観','せかいかん','세계관','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='世界観')
UNION ALL SELECT '人生観','じんせいかん','인생관','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='人生観')
UNION ALL SELECT '自然観','しぜんかん','자연관, 자연에 대한 관점','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='自然観')
UNION ALL SELECT '実存','じつぞん','실존','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='実存')
UNION ALL SELECT '存在','そんざい','존재','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='存在')
UNION ALL SELECT '本質','ほんしつ','본질','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='本質')
UNION ALL SELECT '普遍','ふへん','보편','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='普遍')
UNION ALL SELECT '個別','こべつ','개별','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='個別')
UNION ALL SELECT '弁証法','べんしょうほう','변증법','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='弁証法')
UNION ALL SELECT '唯物論','ゆいぶつろん','유물론','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='唯物論')
UNION ALL SELECT '観念論','かんねんろん','관념론','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='観念論')
UNION ALL SELECT '実用主義','じつようしゅぎ','실용주의, 프래그머티즘','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='実用主義')
UNION ALL SELECT '功利主義','こうりしゅぎ','공리주의','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='功利主義')
UNION ALL SELECT '人道主義','じんどうしゅぎ','인도주의','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='人道主義')
UNION ALL SELECT '合理主義','ごうりしゅぎ','합리주의','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='合理主義')
UNION ALL SELECT '虚無','きょむ','허무','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='虚無')
UNION ALL SELECT '超越','ちょうえつ','초월','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='超越')
UNION ALL SELECT '啓蒙','けいもう','계몽','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='啓蒙')

-- 6. 教育・知識・教養 (25語)
UNION ALL SELECT '教養','きょうよう','교양','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='教養')
UNION ALL SELECT '素養','そよう','소양','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='素養')
UNION ALL SELECT '見識','けんしき','견식, 식견','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='見識')
UNION ALL SELECT '造詣','ぞうけい','조예(깊은 지식)','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='造詣')
UNION ALL SELECT '薫陶','くんとう','훈도, 정신적 교화','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='薫陶')
UNION ALL SELECT '啓発','けいはつ','계발, 계몽','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='啓発')
UNION ALL SELECT '陶冶','とうや','도야, 교육으로 인격 형성','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='陶冶')
UNION ALL SELECT '涵養','かんよう','함양','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='涵養')
UNION ALL SELECT '修養','しゅうよう','수양','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='修養')
UNION ALL SELECT '研鑽','けんさん','연찬, 깊이 연구함','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='研鑽')
UNION ALL SELECT '学識','がくしき','학식','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='学識')
UNION ALL SELECT '知見','ちけん','지견, 지식과 견해','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='知見')
UNION ALL SELECT '博識','はくしき','박식','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='博識')
UNION ALL SELECT '博覧','はくらん','박람, 넓게 읽음','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='博覧')
UNION ALL SELECT '碩学','せきがく','석학','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='碩学')
UNION ALL SELECT '学問','がくもん','학문','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='学問')
UNION ALL SELECT '学術','がくじゅつ','학술','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='学術')
UNION ALL SELECT '論文','ろんぶん','논문','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='論文')
UNION ALL SELECT '著作','ちょさく','저작','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='著作')
UNION ALL SELECT '典拠','てんきょ','전거, 출처','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='典拠')
UNION ALL SELECT '引用','いんよう','인용','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='引用')
UNION ALL SELECT '解釈','かいしゃく','해석','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='解釈')
UNION ALL SELECT '注釈','ちゅうしゃく','주석','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='注釈')
UNION ALL SELECT '批評','ひひょう','비평','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='批評')
UNION ALL SELECT '評論','ひょうろん','평론','N1','명사' WHERE NOT EXISTS (SELECT 1 FROM jlpt_vocabulary WHERE word='評論');
