-- JLPT N4 漢字 シードデータ (181 kanji)
DELETE FROM jlpt_kanji WHERE jlpt_level = 'N4';

INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('不', 'フ、ブ', NULL, '불(不), 아니다', 'not, un-, non-', 4, 'N4', '[{"word":"不便","reading":"ふべん","meaning":"불편"},{"word":"不安","reading":"ふあん","meaning":"불안"}]'::jsonb, 1),
('世', 'セ、セイ', 'よ', '세(世), 세상', 'world, generation', 5, 'N4', '[{"word":"世界","reading":"せかい","meaning":"세계"},{"word":"世話","reading":"せわ","meaning":"돌봄"}]'::jsonb, 2),
('主', 'シュ', 'ぬし、おも', '주(主), 주인', 'main, master, lord', 5, 'N4', '[{"word":"主人","reading":"しゅじん","meaning":"주인"},{"word":"主に","reading":"おもに","meaning":"주로"}]'::jsonb, 3),
('乗', 'ジョウ', 'の.る、の.せる', '승(乘), 타다', 'ride, board, mount', 9, 'N4', '[{"word":"乗る","reading":"のる","meaning":"타다"},{"word":"乗り物","reading":"のりもの","meaning":"탈것"}]'::jsonb, 4),
('事', 'ジ、ズ', 'こと', '사(事), 일', 'thing, matter, affair', 8, 'N4', '[{"word":"事故","reading":"じこ","meaning":"사고"},{"word":"仕事","reading":"しごと","meaning":"일"}]'::jsonb, 5),
('仕', 'シ、ジ', 'つか.える', '사(仕), 섬기다', 'serve, work', 5, 'N4', '[{"word":"仕事","reading":"しごと","meaning":"일"},{"word":"仕方","reading":"しかた","meaning":"방법"}]'::jsonb, 6),
('以', 'イ', NULL, '이(以), ~로써', 'by means of, since', 5, 'N4', '[{"word":"以上","reading":"いじょう","meaning":"이상"},{"word":"以下","reading":"いか","meaning":"이하"}]'::jsonb, 7),
('低', 'テイ', 'ひく.い、ひく.める', '저(低), 낮다', 'low, short', 7, 'N4', '[{"word":"低い","reading":"ひくい","meaning":"낮다"},{"word":"最低","reading":"さいてい","meaning":"최저"}]'::jsonb, 8),
('住', 'ジュウ', 'す.む、す.まう', '주(住), 살다', 'dwell, reside, live', 7, 'N4', '[{"word":"住む","reading":"すむ","meaning":"살다"},{"word":"住所","reading":"じゅうしょ","meaning":"주소"}]'::jsonb, 9),
('体', 'タイ、テイ', 'からだ', '체(體), 몸', 'body', 7, 'N4', '[{"word":"体","reading":"からだ","meaning":"몸"},{"word":"大体","reading":"だいたい","meaning":"대체로"}]'::jsonb, 10),
('作', 'サク、サ', 'つく.る', '작(作), 만들다', 'make, create, produce', 7, 'N4', '[{"word":"作る","reading":"つくる","meaning":"만들다"},{"word":"作文","reading":"さくぶん","meaning":"작문"}]'::jsonb, 11),
('使', 'シ', 'つか.う', '사(使), 쓰다', 'use, employ', 8, 'N4', '[{"word":"使う","reading":"つかう","meaning":"사용하다"},{"word":"大使館","reading":"たいしかん","meaning":"대사관"}]'::jsonb, 12),
('借', 'シャク', 'か.りる', '차(借), 빌리다', 'borrow, rent', 10, 'N4', '[{"word":"借りる","reading":"かりる","meaning":"빌리다"},{"word":"借金","reading":"しゃっきん","meaning":"빚"}]'::jsonb, 13),
('働', 'ドウ', 'はたら.く', '동(働), 일하다', 'work, labor', 13, 'N4', '[{"word":"働く","reading":"はたらく","meaning":"일하다"},{"word":"労働","reading":"ろうどう","meaning":"노동"}]'::jsonb, 14),
('元', 'ゲン、ガン', 'もと', '원(元), 으뜸', 'origin, former, beginning', 4, 'N4', '[{"word":"元気","reading":"げんき","meaning":"건강"},{"word":"元","reading":"もと","meaning":"원래"}]'::jsonb, 15),
('兄', 'ケイ、キョウ', 'あに', '형(兄), 형', 'elder brother', 5, 'N4', '[{"word":"お兄さん","reading":"おにいさん","meaning":"형/오빠"},{"word":"兄弟","reading":"きょうだい","meaning":"형제"}]'::jsonb, 16),
('光', 'コウ', 'ひか.る、ひかり', '광(光), 빛', 'light, ray', 6, 'N4', '[{"word":"光","reading":"ひかり","meaning":"빛"},{"word":"観光","reading":"かんこう","meaning":"관광"}]'::jsonb, 17),
('写', 'シャ', 'うつ.す、うつ.る', '사(寫), 베끼다', 'copy, photograph', 5, 'N4', '[{"word":"写真","reading":"しゃしん","meaning":"사진"},{"word":"写す","reading":"うつす","meaning":"베끼다"}]'::jsonb, 18),
('冬', 'トウ', 'ふゆ', '동(冬), 겨울', 'winter', 5, 'N4', '[{"word":"冬","reading":"ふゆ","meaning":"겨울"},{"word":"冬休み","reading":"ふゆやすみ","meaning":"겨울방학"}]'::jsonb, 19),
('切', 'セツ、サイ', 'き.る、き.れる', '절(切), 자르다', 'cut, sever', 4, 'N4', '[{"word":"切る","reading":"きる","meaning":"자르다"},{"word":"大切","reading":"たいせつ","meaning":"소중하다"}]'::jsonb, 20),
('別', 'ベツ', 'わか.れる', '별(別), 나누다', 'separate, different', 7, 'N4', '[{"word":"別れる","reading":"わかれる","meaning":"헤어지다"},{"word":"特別","reading":"とくべつ","meaning":"특별"}]'::jsonb, 21),
('力', 'リョク、リキ', 'ちから', '력(力), 힘', 'power, force, strength', 2, 'N4', '[{"word":"力","reading":"ちから","meaning":"힘"},{"word":"努力","reading":"どりょく","meaning":"노력"}]'::jsonb, 22),
('動', 'ドウ', 'うご.く、うご.かす', '동(動), 움직이다', 'move, motion', 11, 'N4', '[{"word":"動く","reading":"うごく","meaning":"움직이다"},{"word":"動物","reading":"どうぶつ","meaning":"동물"}]'::jsonb, 23),
('勉', 'ベン', NULL, '면(勉), 힘쓰다', 'endeavor, study', 10, 'N4', '[{"word":"勉強","reading":"べんきょう","meaning":"공부"},{"word":"勉強する","reading":"べんきょうする","meaning":"공부하다"}]'::jsonb, 24),
('区', 'ク', NULL, '구(區), 구역', 'ward, district', 4, 'N4', '[{"word":"区","reading":"く","meaning":"구"},{"word":"地区","reading":"ちく","meaning":"지구"}]'::jsonb, 25),
('医', 'イ', NULL, '의(醫), 의원', 'doctor, medicine', 7, 'N4', '[{"word":"医者","reading":"いしゃ","meaning":"의사"},{"word":"医学","reading":"いがく","meaning":"의학"}]'::jsonb, 26),
('去', 'キョ、コ', 'さ.る', '거(去), 가다', 'gone, past, leave', 5, 'N4', '[{"word":"去年","reading":"きょねん","meaning":"작년"},{"word":"過去","reading":"かこ","meaning":"과거"}]'::jsonb, 27),
('台', 'ダイ、タイ', NULL, '대(臺), 대', 'pedestal, counter', 5, 'N4', '[{"word":"台風","reading":"たいふう","meaning":"태풍"},{"word":"台所","reading":"だいどころ","meaning":"부엌"}]'::jsonb, 28),
('合', 'ゴウ、ガッ、カッ', 'あ.う、あ.わせる', '합(合), 합하다', 'fit, join, match', 6, 'N4', '[{"word":"合う","reading":"あう","meaning":"맞다"},{"word":"場合","reading":"ばあい","meaning":"경우"}]'::jsonb, 29),
('同', 'ドウ', 'おな.じ', '동(同), 같다', 'same, agree, equal', 6, 'N4', '[{"word":"同じ","reading":"おなじ","meaning":"같은"},{"word":"同時","reading":"どうじ","meaning":"동시"}]'::jsonb, 30),
('味', 'ミ', 'あじ、あじ.わう', '미(味), 맛', 'flavor, taste', 8, 'N4', '[{"word":"味","reading":"あじ","meaning":"맛"},{"word":"意味","reading":"いみ","meaning":"의미"}]'::jsonb, 31),
('品', 'ヒン', 'しな', '품(品), 물건', 'goods, article, quality', 9, 'N4', '[{"word":"品物","reading":"しなもの","meaning":"물건"},{"word":"食品","reading":"しょくひん","meaning":"식품"}]'::jsonb, 32),
('員', 'イン', NULL, '원(員), 인원', 'member, employee', 10, 'N4', '[{"word":"会員","reading":"かいいん","meaning":"회원"},{"word":"店員","reading":"てんいん","meaning":"점원"}]'::jsonb, 33),
('問', 'モン', 'と.う、と.い', '문(問), 묻다', 'question, ask', 11, 'N4', '[{"word":"問題","reading":"もんだい","meaning":"문제"},{"word":"質問","reading":"しつもん","meaning":"질문"}]'::jsonb, 34),
('回', 'カイ', 'まわ.る、まわ.す', '회(回), 돌다', 'times, revolve', 6, 'N4', '[{"word":"回る","reading":"まわる","meaning":"돌다"},{"word":"今回","reading":"こんかい","meaning":"이번"}]'::jsonb, 35),
('図', 'ズ、ト', 'はか.る', '도(圖), 그림', 'drawing, diagram', 7, 'N4', '[{"word":"図書館","reading":"としょかん","meaning":"도서관"},{"word":"地図","reading":"ちず","meaning":"지도"}]'::jsonb, 36),
('地', 'チ、ジ', NULL, '지(地), 땅', 'ground, earth, land', 6, 'N4', '[{"word":"地図","reading":"ちず","meaning":"지도"},{"word":"地下鉄","reading":"ちかてつ","meaning":"지하철"}]'::jsonb, 37),
('堂', 'ドウ', NULL, '당(堂), 집', 'hall, temple', 11, 'N4', '[{"word":"食堂","reading":"しょくどう","meaning":"식당"},{"word":"公会堂","reading":"こうかいどう","meaning":"공회당"}]'::jsonb, 38),
('場', 'ジョウ', 'ば', '장(場), 마당', 'place, occasion', 12, 'N4', '[{"word":"場所","reading":"ばしょ","meaning":"장소"},{"word":"場合","reading":"ばあい","meaning":"경우"}]'::jsonb, 39),
('売', 'バイ', 'う.る、う.れる', '매(賣), 팔다', 'sell', 7, 'N4', '[{"word":"売る","reading":"うる","meaning":"팔다"},{"word":"売り場","reading":"うりば","meaning":"매장"}]'::jsonb, 40),
('変', 'ヘン', 'か.わる、か.える', '변(變), 변하다', 'change, strange', 9, 'N4', '[{"word":"変わる","reading":"かわる","meaning":"변하다"},{"word":"大変","reading":"たいへん","meaning":"매우"}]'::jsonb, 41),
('夏', 'カ、ゲ', 'なつ', '하(夏), 여름', 'summer', 10, 'N4', '[{"word":"夏","reading":"なつ","meaning":"여름"},{"word":"夏休み","reading":"なつやすみ","meaning":"여름방학"}]'::jsonb, 42),
('夕', 'セキ', 'ゆう', '석(夕), 저녁', 'evening', 3, 'N4', '[{"word":"夕方","reading":"ゆうがた","meaning":"저녁때"},{"word":"夕食","reading":"ゆうしょく","meaning":"저녁식사"}]'::jsonb, 43),
('太', 'タイ、タ', 'ふと.い、ふと.る', '태(太), 크다', 'thick, fat, big', 4, 'N4', '[{"word":"太い","reading":"ふとい","meaning":"굵다"},{"word":"太る","reading":"ふとる","meaning":"살찌다"}]'::jsonb, 44),
('妹', 'マイ', 'いもうと', '매(妹), 여동생', 'younger sister', 8, 'N4', '[{"word":"妹","reading":"いもうと","meaning":"여동생"},{"word":"姉妹","reading":"しまい","meaning":"자매"}]'::jsonb, 45),
('姉', 'シ', 'あね', '자(姉), 언니/누나', 'elder sister', 8, 'N4', '[{"word":"お姉さん","reading":"おねえさん","meaning":"언니/누나"},{"word":"姉妹","reading":"しまい","meaning":"자매"}]'::jsonb, 46),
('始', 'シ', 'はじ.める、はじ.まる', '시(始), 시작하다', 'begin, start', 8, 'N4', '[{"word":"始める","reading":"はじめる","meaning":"시작하다"},{"word":"開始","reading":"かいし","meaning":"개시"}]'::jsonb, 47),
('届', NULL, 'とど.く、とど.ける', '届, 닿다/전달하다', 'deliver, reach, sincerity', 8, 'N4', '[{"word":"届ける","reading":"とどける","meaning":"전달하다"},{"word":"届く","reading":"とどく","meaning":"닿다"}]'::jsonb, 48),
('屋', 'オク', 'や', '옥(屋), 집', 'roof, house, shop', 9, 'N4', '[{"word":"部屋","reading":"へや","meaning":"방"},{"word":"屋上","reading":"おくじょう","meaning":"옥상"}]'::jsonb, 49),
('工', 'コウ、ク', NULL, '공(工), 장인', 'craft, construction', 3, 'N4', '[{"word":"工場","reading":"こうじょう","meaning":"공장"},{"word":"工事","reading":"こうじ","meaning":"공사"}]'::jsonb, 50),
('広', 'コウ', 'ひろ.い、ひろ.げる', '광(廣), 넓다', 'wide, broad', 5, 'N4', '[{"word":"広い","reading":"ひろい","meaning":"넓다"},{"word":"広場","reading":"ひろば","meaning":"광장"}]'::jsonb, 51),
('度', 'ド、タク', 'たび', '도(度), 정도', 'degree, times', 9, 'N4', '[{"word":"温度","reading":"おんど","meaning":"온도"},{"word":"今度","reading":"こんど","meaning":"이번"}]'::jsonb, 52),
('建', 'ケン、コン', 'た.てる、た.つ', '건(建), 세우다', 'build, construct', 9, 'N4', '[{"word":"建てる","reading":"たてる","meaning":"짓다"},{"word":"建物","reading":"たてもの","meaning":"건물"}]'::jsonb, 53),
('引', 'イン', 'ひ.く、ひ.ける', '인(引), 끌다', 'pull, draw', 4, 'N4', '[{"word":"引く","reading":"ひく","meaning":"끌다"},{"word":"引っ越し","reading":"ひっこし","meaning":"이사"}]'::jsonb, 54),
('弟', 'テイ、ダイ、デ', 'おとうと', '제(弟), 아우', 'younger brother', 7, 'N4', '[{"word":"弟","reading":"おとうと","meaning":"남동생"},{"word":"兄弟","reading":"きょうだい","meaning":"형제"}]'::jsonb, 55),
('強', 'キョウ、ゴウ', 'つよ.い、し.いる', '강(強), 강하다', 'strong, powerful', 11, 'N4', '[{"word":"強い","reading":"つよい","meaning":"강하다"},{"word":"勉強","reading":"べんきょう","meaning":"공부"}]'::jsonb, 56),
('当', 'トウ', 'あ.たる、あ.てる', '당(當), 마땅하다', 'hit, right', 6, 'N4', '[{"word":"本当","reading":"ほんとう","meaning":"정말"},{"word":"当たる","reading":"あたる","meaning":"맞다"}]'::jsonb, 57),
('形', 'ケイ、ギョウ', 'かたち、かた', '형(形), 모양', 'shape, form', 7, 'N4', '[{"word":"形","reading":"かたち","meaning":"모양"},{"word":"人形","reading":"にんぎょう","meaning":"인형"}]'::jsonb, 58),
('待', 'タイ', 'ま.つ', '대(待), 기다리다', 'wait, expect', 9, 'N4', '[{"word":"待つ","reading":"まつ","meaning":"기다리다"},{"word":"招待","reading":"しょうたい","meaning":"초대"}]'::jsonb, 59),
('心', 'シン', 'こころ', '심(心), 마음', 'heart, mind, spirit', 4, 'N4', '[{"word":"心","reading":"こころ","meaning":"마음"},{"word":"安心","reading":"あんしん","meaning":"안심"}]'::jsonb, 60),
('思', 'シ', 'おも.う', '사(思), 생각하다', 'think, consider', 9, 'N4', '[{"word":"思う","reading":"おもう","meaning":"생각하다"},{"word":"思い出","reading":"おもいで","meaning":"추억"}]'::jsonb, 61),
('急', 'キュウ', 'いそ.ぐ', '급(急), 급하다', 'hurry, emergency', 9, 'N4', '[{"word":"急ぐ","reading":"いそぐ","meaning":"서두르다"},{"word":"急に","reading":"きゅうに","meaning":"갑자기"}]'::jsonb, 62),
('悪', 'アク、オ', 'わる.い', '악(惡), 나쁘다', 'bad, evil, wrong', 11, 'N4', '[{"word":"悪い","reading":"わるい","meaning":"나쁘다"},{"word":"悪魔","reading":"あくま","meaning":"악마"}]'::jsonb, 63),
('意', 'イ', NULL, '의(意), 뜻', 'intention, meaning', 13, 'N4', '[{"word":"意味","reading":"いみ","meaning":"의미"},{"word":"意見","reading":"いけん","meaning":"의견"}]'::jsonb, 64),
('持', 'ジ', 'も.つ', '지(持), 가지다', 'hold, have, possess', 9, 'N4', '[{"word":"持つ","reading":"もつ","meaning":"가지다"},{"word":"気持ち","reading":"きもち","meaning":"기분"}]'::jsonb, 65),
('教', 'キョウ', 'おし.える、おそ.わる', '교(教), 가르치다', 'teach, instruct', 11, 'N4', '[{"word":"教える","reading":"おしえる","meaning":"가르치다"},{"word":"教室","reading":"きょうしつ","meaning":"교실"}]'::jsonb, 66),
('文', 'ブン、モン', 'ふみ', '문(文), 글', 'text, sentence', 4, 'N4', '[{"word":"文化","reading":"ぶんか","meaning":"문화"},{"word":"文章","reading":"ぶんしょう","meaning":"문장"}]'::jsonb, 67),
('料', 'リョウ', NULL, '료(料), 헤아리다', 'fee, material', 10, 'N4', '[{"word":"料理","reading":"りょうり","meaning":"요리"},{"word":"料金","reading":"りょうきん","meaning":"요금"}]'::jsonb, 68),
('旅', 'リョ', 'たび', '려(旅), 나그네', 'travel, trip', 10, 'N4', '[{"word":"旅行","reading":"りょこう","meaning":"여행"},{"word":"旅館","reading":"りょかん","meaning":"여관"}]'::jsonb, 69),
('族', 'ゾク', NULL, '족(族), 겨레', 'tribe, family, clan', 11, 'N4', '[{"word":"家族","reading":"かぞく","meaning":"가족"},{"word":"民族","reading":"みんぞく","meaning":"민족"}]'::jsonb, 70),
('早', 'ソウ、サッ', 'はや.い、はや.める', '조(早), 이르다', 'early, fast', 6, 'N4', '[{"word":"早い","reading":"はやい","meaning":"이르다"},{"word":"早く","reading":"はやく","meaning":"빨리"}]'::jsonb, 71),
('映', 'エイ', 'うつ.る、うつ.す', '영(映), 비치다', 'reflect, project', 9, 'N4', '[{"word":"映画","reading":"えいが","meaning":"영화"},{"word":"映る","reading":"うつる","meaning":"비치다"}]'::jsonb, 72),
('春', 'シュン', 'はる', '춘(春), 봄', 'spring', 9, 'N4', '[{"word":"春","reading":"はる","meaning":"봄"},{"word":"春休み","reading":"はるやすみ","meaning":"봄방학"}]'::jsonb, 73),
('暑', 'ショ', 'あつ.い', '서(暑), 덥다', 'hot (weather)', 12, 'N4', '[{"word":"暑い","reading":"あつい","meaning":"덥다"},{"word":"蒸し暑い","reading":"むしあつい","meaning":"무덥다"}]'::jsonb, 74),
('暗', 'アン', 'くら.い', '암(暗), 어둡다', 'dark, darkness', 13, 'N4', '[{"word":"暗い","reading":"くらい","meaning":"어둡다"},{"word":"暗記","reading":"あんき","meaning":"암기"}]'::jsonb, 75),
('有', 'ユウ、ウ', 'あ.る', '유(有), 있다', 'have, exist', 6, 'N4', '[{"word":"有名","reading":"ゆうめい","meaning":"유명"},{"word":"有る","reading":"ある","meaning":"있다"}]'::jsonb, 76),
('服', 'フク', NULL, '복(服), 옷', 'clothes, clothing', 8, 'N4', '[{"word":"服","reading":"ふく","meaning":"옷"},{"word":"洋服","reading":"ようふく","meaning":"양복"}]'::jsonb, 77),
('朝', 'チョウ', 'あさ', '조(朝), 아침', 'morning', 12, 'N4', '[{"word":"朝","reading":"あさ","meaning":"아침"},{"word":"朝食","reading":"ちょうしょく","meaning":"아침식사"}]'::jsonb, 78),
('業', 'ギョウ、ゴウ', 'わざ', '업(業), 업', 'business, industry', 13, 'N4', '[{"word":"授業","reading":"じゅぎょう","meaning":"수업"},{"word":"卒業","reading":"そつぎょう","meaning":"졸업"}]'::jsonb, 79),
('楽', 'ガク、ラク', 'たの.しい、たの.しむ', '락(樂), 즐기다', 'pleasure, music', 13, 'N4', '[{"word":"楽しい","reading":"たのしい","meaning":"즐겁다"},{"word":"音楽","reading":"おんがく","meaning":"음악"}]'::jsonb, 80),
('歌', 'カ', 'うた、うた.う', '가(歌), 노래', 'song, sing', 14, 'N4', '[{"word":"歌う","reading":"うたう","meaning":"노래하다"},{"word":"歌手","reading":"かしゅ","meaning":"가수"}]'::jsonb, 81),
('止', 'シ', 'と.まる、と.める', '지(止), 그치다', 'stop, halt', 4, 'N4', '[{"word":"止まる","reading":"とまる","meaning":"멈추다"},{"word":"中止","reading":"ちゅうし","meaning":"중지"}]'::jsonb, 82),
('死', 'シ', 'し.ぬ', '사(死), 죽다', 'death, die', 6, 'N4', '[{"word":"死ぬ","reading":"しぬ","meaning":"죽다"},{"word":"死亡","reading":"しぼう","meaning":"사망"}]'::jsonb, 83),
('注', 'チュウ', 'そそ.ぐ', '주(注), 붓다', 'pour, notes', 8, 'N4', '[{"word":"注意","reading":"ちゅうい","meaning":"주의"},{"word":"注文","reading":"ちゅうもん","meaning":"주문"}]'::jsonb, 84),
('洋', 'ヨウ', NULL, '양(洋), 바다', 'ocean, western', 9, 'N4', '[{"word":"洋服","reading":"ようふく","meaning":"양복"},{"word":"西洋","reading":"せいよう","meaning":"서양"}]'::jsonb, 85),
('活', 'カツ', NULL, '활(活), 살다', 'lively, active', 9, 'N4', '[{"word":"生活","reading":"せいかつ","meaning":"생활"},{"word":"活動","reading":"かつどう","meaning":"활동"}]'::jsonb, 86),
('海', 'カイ', 'うみ', '해(海), 바다', 'sea, ocean', 9, 'N4', '[{"word":"海","reading":"うみ","meaning":"바다"},{"word":"海外","reading":"かいがい","meaning":"해외"}]'::jsonb, 87),
('漢', 'カン', NULL, '한(漢), 한나라', 'China, kanji', 13, 'N4', '[{"word":"漢字","reading":"かんじ","meaning":"한자"},{"word":"漢方","reading":"かんぽう","meaning":"한방"}]'::jsonb, 88),
('点', 'テン', NULL, '점(點), 점', 'point, mark, dot', 9, 'N4', '[{"word":"点","reading":"てん","meaning":"점"},{"word":"交差点","reading":"こうさてん","meaning":"교차점"}]'::jsonb, 89),
('無', 'ム、ブ', 'な.い', '무(無), 없다', 'nothing, none', 12, 'N4', '[{"word":"無理","reading":"むり","meaning":"무리"},{"word":"無料","reading":"むりょう","meaning":"무료"}]'::jsonb, 90),
('特', 'トク', NULL, '특(特), 특별하다', 'special, unique', 10, 'N4', '[{"word":"特に","reading":"とくに","meaning":"특히"},{"word":"特別","reading":"とくべつ","meaning":"특별"}]'::jsonb, 91),
('犬', 'ケン', 'いぬ', '견(犬), 개', 'dog', 4, 'N4', '[{"word":"犬","reading":"いぬ","meaning":"개"},{"word":"子犬","reading":"こいぬ","meaning":"강아지"}]'::jsonb, 92),
('理', 'リ', NULL, '리(理), 다스리다', 'reason, logic', 11, 'N4', '[{"word":"料理","reading":"りょうり","meaning":"요리"},{"word":"無理","reading":"むり","meaning":"무리"}]'::jsonb, 93),
('産', 'サン', 'う.む、う.まれる', '산(産), 낳다', 'produce, give birth', 11, 'N4', '[{"word":"産業","reading":"さんぎょう","meaning":"산업"},{"word":"お土産","reading":"おみやげ","meaning":"선물"}]'::jsonb, 94),
('用', 'ヨウ', 'もち.いる', '용(用), 쓰다', 'use, employ', 5, 'N4', '[{"word":"用事","reading":"ようじ","meaning":"용건"},{"word":"使用","reading":"しよう","meaning":"사용"}]'::jsonb, 95),
('界', 'カイ', NULL, '계(界), 경계', 'world, boundary', 9, 'N4', '[{"word":"世界","reading":"せかい","meaning":"세계"},{"word":"業界","reading":"ぎょうかい","meaning":"업계"}]'::jsonb, 96),
('発', 'ハツ、ホツ', NULL, '발(發), 쏘다', 'departure, emit', 9, 'N4', '[{"word":"出発","reading":"しゅっぱつ","meaning":"출발"},{"word":"発見","reading":"はっけん","meaning":"발견"}]'::jsonb, 97),
('着', 'チャク', 'き.る、つ.く', '착(着), 입다', 'arrive, wear', 12, 'N4', '[{"word":"着る","reading":"きる","meaning":"입다"},{"word":"到着","reading":"とうちゃく","meaning":"도착"}]'::jsonb, 98),
('知', 'チ', 'し.る', '지(知), 알다', 'know, wisdom', 8, 'N4', '[{"word":"知る","reading":"しる","meaning":"알다"},{"word":"知識","reading":"ちしき","meaning":"지식"}]'::jsonb, 99),
('研', 'ケン', 'と.ぐ', '연(硏), 갈다', 'polish, study', 9, 'N4', '[{"word":"研究","reading":"けんきゅう","meaning":"연구"},{"word":"研究所","reading":"けんきゅうじょ","meaning":"연구소"}]'::jsonb, 100),
('究', 'キュウ', 'きわ.める', '구(究), 궁구하다', 'research, investigate', 7, 'N4', '[{"word":"研究","reading":"けんきゅう","meaning":"연구"},{"word":"究極","reading":"きゅうきょく","meaning":"궁극"}]'::jsonb, 101),
('私', 'シ', 'わたくし、わたし', '사(私), 사사롭다', 'private, I, me', 7, 'N4', '[{"word":"私","reading":"わたし","meaning":"나"},{"word":"私立","reading":"しりつ","meaning":"사립"}]'::jsonb, 102),
('秋', 'シュウ', 'あき', '추(秋), 가을', 'autumn, fall', 9, 'N4', '[{"word":"秋","reading":"あき","meaning":"가을"},{"word":"秋分","reading":"しゅうぶん","meaning":"추분"}]'::jsonb, 103),
('空', 'クウ', 'そら、あ.く、から', '공(空), 비다', 'sky, empty, void', 8, 'N4', '[{"word":"空","reading":"そら","meaning":"하늘"},{"word":"空港","reading":"くうこう","meaning":"공항"}]'::jsonb, 104),
('立', 'リツ、リュウ', 'た.つ、た.てる', '립(立), 서다', 'stand, establish', 5, 'N4', '[{"word":"立つ","reading":"たつ","meaning":"서다"},{"word":"国立","reading":"こくりつ","meaning":"국립"}]'::jsonb, 105),
('終', 'シュウ', 'お.わる、お.える', '종(終), 마치다', 'end, finish', 11, 'N4', '[{"word":"終わる","reading":"おわる","meaning":"끝나다"},{"word":"最終","reading":"さいしゅう","meaning":"최종"}]'::jsonb, 106),
('経', 'ケイ、キョウ', 'へ.る、た.つ', '경(經), 지나다', 'pass through, experience', 11, 'N4', '[{"word":"経験","reading":"けいけん","meaning":"경험"},{"word":"経済","reading":"けいざい","meaning":"경제"}]'::jsonb, 107),
('習', 'シュウ', 'なら.う', '습(習), 익히다', 'learn, practice', 11, 'N4', '[{"word":"習う","reading":"ならう","meaning":"배우다"},{"word":"練習","reading":"れんしゅう","meaning":"연습"}]'::jsonb, 108),
('考', 'コウ', 'かんが.える', '고(考), 생각하다', 'think, consider', 6, 'N4', '[{"word":"考える","reading":"かんがえる","meaning":"생각하다"},{"word":"参考","reading":"さんこう","meaning":"참고"}]'::jsonb, 109),
('者', 'シャ', 'もの', '자(者), 사람', 'person, someone', 8, 'N4', '[{"word":"医者","reading":"いしゃ","meaning":"의사"},{"word":"若者","reading":"わかもの","meaning":"젊은이"}]'::jsonb, 110),
('自', 'ジ、シ', 'みずか.ら', '자(自), 스스로', 'self, oneself', 6, 'N4', '[{"word":"自分","reading":"じぶん","meaning":"자신"},{"word":"自転車","reading":"じてんしゃ","meaning":"자전거"}]'::jsonb, 111),
('色', 'ショク、シキ', 'いろ', '색(色), 빛깔', 'color', 6, 'N4', '[{"word":"色","reading":"いろ","meaning":"색"},{"word":"景色","reading":"けしき","meaning":"경치"}]'::jsonb, 112),
('花', 'カ', 'はな', '화(花), 꽃', 'flower', 7, 'N4', '[{"word":"花","reading":"はな","meaning":"꽃"},{"word":"花見","reading":"はなみ","meaning":"꽃놀이"}]'::jsonb, 113),
('茶', 'チャ、サ', NULL, '다(茶), 차', 'tea', 9, 'N4', '[{"word":"お茶","reading":"おちゃ","meaning":"차"},{"word":"茶色","reading":"ちゃいろ","meaning":"갈색"}]'::jsonb, 114),
('薬', 'ヤク', 'くすり', '약(藥), 약', 'medicine, drug', 16, 'N4', '[{"word":"薬","reading":"くすり","meaning":"약"},{"word":"薬局","reading":"やっきょく","meaning":"약국"}]'::jsonb, 115),
('親', 'シン', 'おや、した.しい', '친(親), 어버이', 'parent, intimacy', 16, 'N4', '[{"word":"親","reading":"おや","meaning":"부모"},{"word":"親切","reading":"しんせつ","meaning":"친절"}]'::jsonb, 116),
('計', 'ケイ', 'はか.る', '계(計), 세다', 'plan, measure', 9, 'N4', '[{"word":"時計","reading":"とけい","meaning":"시계"},{"word":"計画","reading":"けいかく","meaning":"계획"}]'::jsonb, 117),
('試', 'シ', 'こころ.みる、ため.す', '시(試), 시험하다', 'try, test', 13, 'N4', '[{"word":"試験","reading":"しけん","meaning":"시험"},{"word":"試す","reading":"ためす","meaning":"시험해보다"}]'::jsonb, 118),
('説', 'セツ、ゼイ', 'と.く', '설(說), 말하다', 'explain, theory', 14, 'N4', '[{"word":"説明","reading":"せつめい","meaning":"설명"},{"word":"小説","reading":"しょうせつ","meaning":"소설"}]'::jsonb, 119),
('質', 'シツ、シチ', NULL, '질(質), 바탕', 'quality, question', 15, 'N4', '[{"word":"質問","reading":"しつもん","meaning":"질문"},{"word":"品質","reading":"ひんしつ","meaning":"품질"}]'::jsonb, 120),
('赤', 'セキ、シャク', 'あか、あか.い', '적(赤), 붉다', 'red', 7, 'N4', '[{"word":"赤い","reading":"あかい","meaning":"빨갛다"},{"word":"赤ちゃん","reading":"あかちゃん","meaning":"아기"}]'::jsonb, 121),
('走', 'ソウ', 'はし.る', '주(走), 달리다', 'run', 7, 'N4', '[{"word":"走る","reading":"はしる","meaning":"달리다"},{"word":"走行","reading":"そうこう","meaning":"주행"}]'::jsonb, 122),
('足', 'ソク', 'あし、た.りる', '족(足), 발', 'foot, leg, sufficient', 7, 'N4', '[{"word":"足","reading":"あし","meaning":"발"},{"word":"不足","reading":"ふそく","meaning":"부족"}]'::jsonb, 123),
('転', 'テン', 'ころ.がる、ころ.げる', '전(轉), 구르다', 'revolve, turn', 11, 'N4', '[{"word":"自転車","reading":"じてんしゃ","meaning":"자전거"},{"word":"運転","reading":"うんてん","meaning":"운전"}]'::jsonb, 124),
('送', 'ソウ', 'おく.る', '송(送), 보내다', 'send, transmit', 9, 'N4', '[{"word":"送る","reading":"おくる","meaning":"보내다"},{"word":"放送","reading":"ほうそう","meaning":"방송"}]'::jsonb, 125),
('通', 'ツウ、ツ', 'とお.る、かよ.う', '통(通), 통하다', 'pass through, commute', 10, 'N4', '[{"word":"通る","reading":"とおる","meaning":"지나가다"},{"word":"通う","reading":"かよう","meaning":"다니다"}]'::jsonb, 126),
('進', 'シン', 'すす.む、すす.める', '진(進), 나아가다', 'advance, proceed', 11, 'N4', '[{"word":"進む","reading":"すすむ","meaning":"나아가다"},{"word":"進学","reading":"しんがく","meaning":"진학"}]'::jsonb, 127),
('運', 'ウン', 'はこ.ぶ', '운(運), 옮기다', 'carry, luck', 12, 'N4', '[{"word":"運動","reading":"うんどう","meaning":"운동"},{"word":"運転","reading":"うんてん","meaning":"운전"}]'::jsonb, 128),
('遊', 'ユウ、ユ', 'あそ.ぶ', '유(遊), 놀다', 'play, amusement', 12, 'N4', '[{"word":"遊ぶ","reading":"あそぶ","meaning":"놀다"},{"word":"遊園地","reading":"ゆうえんち","meaning":"놀이공원"}]'::jsonb, 129),
('開', 'カイ', 'ひら.く、あ.く、あ.ける', '개(開), 열다', 'open', 12, 'N4', '[{"word":"開く","reading":"あく","meaning":"열리다"},{"word":"開始","reading":"かいし","meaning":"개시"}]'::jsonb, 130),
('集', 'シュウ', 'あつ.める、あつ.まる', '집(集), 모으다', 'gather, collect', 12, 'N4', '[{"word":"集める","reading":"あつめる","meaning":"모으다"},{"word":"集まる","reading":"あつまる","meaning":"모이다"}]'::jsonb, 131),
('青', 'セイ、ショウ', 'あお、あお.い', '청(靑), 푸르다', 'blue, green', 8, 'N4', '[{"word":"青い","reading":"あおい","meaning":"파랗다"},{"word":"青年","reading":"せいねん","meaning":"청년"}]'::jsonb, 132),
('音', 'オン、イン', 'おと、ね', '음(音), 소리', 'sound, noise', 9, 'N4', '[{"word":"音楽","reading":"おんがく","meaning":"음악"},{"word":"音","reading":"おと","meaning":"소리"}]'::jsonb, 133),
('頭', 'トウ、ズ', 'あたま、かしら', '두(頭), 머리', 'head', 16, 'N4', '[{"word":"頭","reading":"あたま","meaning":"머리"},{"word":"頭痛","reading":"ずつう","meaning":"두통"}]'::jsonb, 134),
('顔', 'ガン', 'かお', '안(顔), 얼굴', 'face', 18, 'N4', '[{"word":"顔","reading":"かお","meaning":"얼굴"},{"word":"笑顔","reading":"えがお","meaning":"웃는 얼굴"}]'::jsonb, 135),
('風', 'フウ、フ', 'かぜ、かざ', '풍(風), 바람', 'wind, style', 9, 'N4', '[{"word":"風","reading":"かぜ","meaning":"바람"},{"word":"台風","reading":"たいふう","meaning":"태풍"}]'::jsonb, 136),
('飯', 'ハン', 'めし', '반(飯), 밥', 'meal, cooked rice', 12, 'N4', '[{"word":"ご飯","reading":"ごはん","meaning":"밥"},{"word":"朝飯","reading":"あさめし","meaning":"아침밥"}]'::jsonb, 137),
('館', 'カン', 'やかた', '관(館), 집', 'building, hall', 16, 'N4', '[{"word":"図書館","reading":"としょかん","meaning":"도서관"},{"word":"旅館","reading":"りょかん","meaning":"여관"}]'::jsonb, 138),
('首', 'シュ', 'くび', '수(首), 머리', 'neck, head, chief', 9, 'N4', '[{"word":"首","reading":"くび","meaning":"목"},{"word":"首都","reading":"しゅと","meaning":"수도"}]'::jsonb, 139),
('験', 'ケン、ゲン', NULL, '험(驗), 시험하다', 'test, examine', 18, 'N4', '[{"word":"試験","reading":"しけん","meaning":"시험"},{"word":"経験","reading":"けいけん","meaning":"경험"}]'::jsonb, 140),
('鳥', 'チョウ', 'とり', '조(鳥), 새', 'bird', 11, 'N4', '[{"word":"鳥","reading":"とり","meaning":"새"},{"word":"焼き鳥","reading":"やきとり","meaning":"야키토리"}]'::jsonb, 141),
('黒', 'コク', 'くろ、くろ.い', '흑(黑), 검다', 'black', 11, 'N4', '[{"word":"黒い","reading":"くろい","meaning":"검다"},{"word":"黒","reading":"くろ","meaning":"검정"}]'::jsonb, 142),
('鼻', 'ビ', 'はな', '비(鼻), 코', 'nose', 14, 'N4', '[{"word":"鼻","reading":"はな","meaning":"코"},{"word":"鼻水","reading":"はなみず","meaning":"콧물"}]'::jsonb, 143),
('目', 'モク、ボク', 'め', '목(目), 눈', 'eye', 5, 'N4', '[{"word":"目","reading":"め","meaning":"눈"},{"word":"目的","reading":"もくてき","meaning":"목적"}]'::jsonb, 144),
('耳', 'ジ', 'みみ', '이(耳), 귀', 'ear', 6, 'N4', '[{"word":"耳","reading":"みみ","meaning":"귀"},{"word":"耳鼻科","reading":"じびか","meaning":"이비인후과"}]'::jsonb, 145),
('口', 'コウ、ク', 'くち', '구(口), 입', 'mouth, opening', 3, 'N4', '[{"word":"口","reading":"くち","meaning":"입"},{"word":"入口","reading":"いりぐち","meaning":"입구"}]'::jsonb, 146),
('手', 'シュ', 'て', '수(手), 손', 'hand', 4, 'N4', '[{"word":"手","reading":"て","meaning":"손"},{"word":"上手","reading":"じょうず","meaning":"잘하다"}]'::jsonb, 147),
('紙', 'シ', 'かみ', '지(紙), 종이', 'paper', 10, 'N4', '[{"word":"紙","reading":"かみ","meaning":"종이"},{"word":"手紙","reading":"てがみ","meaning":"편지"}]'::jsonb, 148),
('字', 'ジ', 'あざ', '자(字), 글자', 'character, letter', 6, 'N4', '[{"word":"漢字","reading":"かんじ","meaning":"한자"},{"word":"文字","reading":"もじ","meaning":"문자"}]'::jsonb, 149),
('帰', 'キ', 'かえ.る、かえ.す', '귀(歸), 돌아가다', 'return, go home', 10, 'N4', '[{"word":"帰る","reading":"かえる","meaning":"돌아가다"},{"word":"帰国","reading":"きこく","meaning":"귀국"}]'::jsonb, 150),
('会', 'カイ、エ', 'あ.う', '회(會), 모이다', 'meet, association', 6, 'N4', '[{"word":"会う","reading":"あう","meaning":"만나다"},{"word":"会社","reading":"かいしゃ","meaning":"회사"}]'::jsonb, 151),
('代', 'ダイ、タイ', 'か.わる、よ、しろ', '대(代), 대신하다', 'substitute, generation', 5, 'N4', '[{"word":"時代","reading":"じだい","meaning":"시대"},{"word":"代わり","reading":"かわり","meaning":"대신"}]'::jsonb, 152),
('供', 'キョウ、ク', 'そな.える、とも', '공(供), 바치다', 'offer, companion', 8, 'N4', '[{"word":"子供","reading":"こども","meaning":"어린이"},{"word":"提供","reading":"ていきょう","meaning":"제공"}]'::jsonb, 153),
('正', 'セイ、ショウ', 'ただ.しい、まさ', '정(正), 바르다', 'correct, right', 5, 'N4', '[{"word":"正しい","reading":"ただしい","meaning":"올바르다"},{"word":"正月","reading":"しょうがつ","meaning":"정월"}]'::jsonb, 154),
('民', 'ミン', 'たみ', '민(民), 백성', 'people, nation', 5, 'N4', '[{"word":"国民","reading":"こくみん","meaning":"국민"},{"word":"民族","reading":"みんぞく","meaning":"민족"}]'::jsonb, 155),
('池', 'チ', 'いけ', '지(池), 못', 'pond, pool', 6, 'N4', '[{"word":"池","reading":"いけ","meaning":"연못"},{"word":"電池","reading":"でんち","meaning":"배터리"}]'::jsonb, 156),
('決', 'ケツ', 'き.める、き.まる', '결(決), 결정하다', 'decide, determine', 7, 'N4', '[{"word":"決める","reading":"きめる","meaning":"정하다"},{"word":"決定","reading":"けってい","meaning":"결정"}]'::jsonb, 157),
('払', 'フツ', 'はら.う', '불(拂), 털다', 'pay, clear away', 5, 'N4', '[{"word":"払う","reading":"はらう","meaning":"지불하다"},{"word":"支払い","reading":"しはらい","meaning":"지불"}]'::jsonb, 158),
('林', 'リン', 'はやし', '림(林), 수풀', 'grove, forest', 8, 'N4', '[{"word":"林","reading":"はやし","meaning":"숲"},{"word":"森林","reading":"しんりん","meaning":"삼림"}]'::jsonb, 159),
('森', 'シン', 'もり', '삼(森), 빽빽하다', 'forest, woods', 12, 'N4', '[{"word":"森","reading":"もり","meaning":"숲"},{"word":"森林","reading":"しんりん","meaning":"삼림"}]'::jsonb, 160),
('橋', 'キョウ', 'はし', '교(橋), 다리', 'bridge', 16, 'N4', '[{"word":"橋","reading":"はし","meaning":"다리"},{"word":"歩道橋","reading":"ほどうきょう","meaning":"육교"}]'::jsonb, 161),
('歩', 'ホ、ブ、フ', 'ある.く、あゆ.む', '보(步), 걷다', 'walk, step', 8, 'N4', '[{"word":"歩く","reading":"あるく","meaning":"걷다"},{"word":"散歩","reading":"さんぽ","meaning":"산책"}]'::jsonb, 162),
('病', 'ビョウ、ヘイ', 'や.む、やまい', '병(病), 병', 'illness, disease', 10, 'N4', '[{"word":"病気","reading":"びょうき","meaning":"병"},{"word":"病院","reading":"びょういん","meaning":"병원"}]'::jsonb, 163),
('院', 'イン', NULL, '원(院), 집', 'institution, hospital', 10, 'N4', '[{"word":"病院","reading":"びょういん","meaning":"병원"},{"word":"入院","reading":"にゅういん","meaning":"입원"}]'::jsonb, 164),
('真', 'シン', 'ま、まこと', '진(眞), 참', 'true, real', 10, 'N4', '[{"word":"写真","reading":"しゃしん","meaning":"사진"},{"word":"真ん中","reading":"まんなか","meaning":"한가운데"}]'::jsonb, 165),
('石', 'セキ、シャク、コク', 'いし', '석(石), 돌', 'stone, rock', 5, 'N4', '[{"word":"石","reading":"いし","meaning":"돌"},{"word":"宝石","reading":"ほうせき","meaning":"보석"}]'::jsonb, 166),
('社', 'シャ', 'やしろ', '사(社), 모임', 'company, shrine', 7, 'N4', '[{"word":"会社","reading":"かいしゃ","meaning":"회사"},{"word":"社会","reading":"しゃかい","meaning":"사회"}]'::jsonb, 167),
('野', 'ヤ', 'の', '야(野), 들', 'field, wild', 11, 'N4', '[{"word":"野菜","reading":"やさい","meaning":"야채"},{"word":"野球","reading":"やきゅう","meaning":"야구"}]'::jsonb, 168),
('重', 'ジュウ、チョウ', 'おも.い、かさ.ねる、え', '중(重), 무겁다', 'heavy, important', 9, 'N4', '[{"word":"重い","reading":"おもい","meaning":"무겁다"},{"word":"重要","reading":"じゅうよう","meaning":"중요"}]'::jsonb, 169),
('銀', 'ギン', NULL, '은(銀), 은', 'silver', 14, 'N4', '[{"word":"銀行","reading":"ぎんこう","meaning":"은행"},{"word":"銀","reading":"ぎん","meaning":"은"}]'::jsonb, 170),
('鉄', 'テツ', NULL, '철(鐵), 쇠', 'iron, steel', 13, 'N4', '[{"word":"地下鉄","reading":"ちかてつ","meaning":"지하철"},{"word":"鉄道","reading":"てつどう","meaning":"철도"}]'::jsonb, 171),
('門', 'モン', 'かど', '문(門), 문', 'gate, door', 8, 'N4', '[{"word":"門","reading":"もん","meaning":"문"},{"word":"専門","reading":"せんもん","meaning":"전문"}]'::jsonb, 172),
('町', 'チョウ', 'まち', '정(町), 마을', 'town, city block', 7, 'N4', '[{"word":"町","reading":"まち","meaning":"마을"},{"word":"町中","reading":"まちなか","meaning":"마을 안"}]'::jsonb, 173),
('答', 'トウ', 'こた.える、こた.え', '답(答), 대답하다', 'answer, reply', 12, 'N4', '[{"word":"答える","reading":"こたえる","meaning":"대답하다"},{"word":"答え","reading":"こたえ","meaning":"답"}]'::jsonb, 174),
('肉', 'ニク', NULL, '육(肉), 고기', 'meat, flesh', 6, 'N4', '[{"word":"肉","reading":"にく","meaning":"고기"},{"word":"牛肉","reading":"ぎゅうにく","meaning":"소고기"}]'::jsonb, 175),
('物', 'ブツ、モツ', 'もの', '물(物), 물건', 'thing, object', 8, 'N4', '[{"word":"物","reading":"もの","meaning":"물건"},{"word":"動物","reading":"どうぶつ","meaning":"동물"}]'::jsonb, 176),
('近', 'キン', 'ちか.い', '근(近), 가깝다', 'near, close', 7, 'N4', '[{"word":"近い","reading":"ちかい","meaning":"가깝다"},{"word":"最近","reading":"さいきん","meaning":"최근"}]'::jsonb, 177),
('週', 'シュウ', NULL, '주(週), 주일', 'week', 11, 'N4', '[{"word":"今週","reading":"こんしゅう","meaning":"이번 주"},{"word":"来週","reading":"らいしゅう","meaning":"다음 주"}]'::jsonb, 178),
('道', 'ドウ、トウ', 'みち', '도(道), 길', 'road, path, way', 12, 'N4', '[{"word":"道","reading":"みち","meaning":"길"},{"word":"道路","reading":"どうろ","meaning":"도로"}]'::jsonb, 179),
('違', 'イ', 'ちが.う、ちが.える', '위(違), 다르다', 'differ, mistake', 13, 'N4', '[{"word":"違う","reading":"ちがう","meaning":"다르다"},{"word":"間違い","reading":"まちがい","meaning":"실수"}]'::jsonb, 180),
('貸', 'タイ', 'か.す', '대(貸), 빌려주다', 'lend, loan', 12, 'N4', '[{"word":"貸す","reading":"かす","meaning":"빌려주다"},{"word":"貸し出し","reading":"かしだし","meaning":"대출"}]'::jsonb, 181);
