-- 00070 추가 어휘에 예문 추가 (207개)
-- 기존 glossary.sql 166개와 동일 품질 — IT/비즈니스 현장 맥락의 일본어 1문장

-- ============================================
-- dev (54 terms)
-- ============================================
UPDATE it_glossary SET example_sentence = '設計書のレビューを来週までに完了してください。' WHERE term_ja = '設計書';
UPDATE it_glossary SET example_sentence = 'データの整合性を確認してから本番環境に反映します。' WHERE term_ja = '整合性';
UPDATE it_glossary SET example_sentence = 'システムが安定して稼働しているか毎日確認しています。' WHERE term_ja = '稼働' AND category = 'dev';
UPDATE it_glossary SET example_sentence = '作業内容の明細書を月末までに提出してください。' WHERE term_ja = '明細書';
UPDATE it_glossary SET example_sentence = 'セキュリティの脆弱性について改修を実施します。' WHERE term_ja = '改修';
UPDATE it_glossary SET example_sentence = '仕様書に基づいて画面レイアウトを実装してください。' WHERE term_ja = '仕様書';
UPDATE it_glossary SET example_sentence = '開発環境の構築が完了しました。' WHERE term_ja = '構築';
UPDATE it_glossary SET example_sentence = '要件定義の段階で顧客の要望を正確に把握します。' WHERE term_ja = '要件定義';
UPDATE it_glossary SET example_sentence = 'ドキュメントの見出しを分かりやすく整理してください。' WHERE term_ja = '見出し';
UPDATE it_glossary SET example_sentence = '入力項目の仕様を確認してから実装に入ります。' WHERE term_ja = '項目';
UPDATE it_glossary SET example_sentence = '名刺には正式な肩書を記載してください。' WHERE term_ja = '肩書';
UPDATE it_glossary SET example_sentence = '会社紹介ページに沿革を掲載する必要があります。' WHERE term_ja = '沿革';
UPDATE it_glossary SET example_sentence = '来月からクライアント先に派遣される予定です。' WHERE term_ja = '派遣' AND category = 'dev';
UPDATE it_glossary SET example_sentence = '代表取締役の承認が必要な書類です。' WHERE term_ja = '代表取締役';
UPDATE it_glossary SET example_sentence = 'セクション間に区切り線を入れて見やすくしてください。' WHERE term_ja = '区切り線';
UPDATE it_glossary SET example_sentence = '基本設計書をクライアントに提出しました。' WHERE term_ja = '基本設計書';
UPDATE it_glossary SET example_sentence = '詳細設計書に沿って実装を進めてください。' WHERE term_ja = '詳細設計書';
UPDATE it_glossary SET example_sentence = 'テーブル定義書に新しいカラムを追加しました。' WHERE term_ja = 'テーブル定義書' AND category = 'dev' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = '運用マニュアルを最新の状態に更新してください。' WHERE term_ja = 'マニュアル';
UPDATE it_glossary SET example_sentence = 'デプロイ手順書に従って作業を進めてください。' WHERE term_ja = '手順書';
UPDATE it_glossary SET example_sentence = '新バージョンにAI機能を搭載しました。' WHERE term_ja = '搭載';
UPDATE it_glossary SET example_sentence = 'サーバールームの機器配置図を更新してください。' WHERE term_ja = '機器配置';
UPDATE it_glossary SET example_sentence = '設計時の参考資料を共有フォルダに保存しました。' WHERE term_ja = '参考資料';
UPDATE it_glossary SET example_sentence = '組込みソフトウェアの開発経験が求められます。' WHERE term_ja = '組込み';
UPDATE it_glossary SET example_sentence = 'パッチの適用作業を今週末に実施します。' WHERE term_ja = '適用作業';
UPDATE it_glossary SET example_sentence = '新規案件の起案書を作成して承認を得てください。' WHERE term_ja = '起案書';
UPDATE it_glossary SET example_sentence = '要件定義書の最終版をレビューしてください。' WHERE term_ja = '要件定義書';
UPDATE it_glossary SET example_sentence = '実装前に必ず仕様確認を行ってください。' WHERE term_ja = '仕様確認';
UPDATE it_glossary SET example_sentence = '仕様変更が発生したので工数を再見積もりします。' WHERE term_ja = '仕様変更' AND category = 'dev';
UPDATE it_glossary SET example_sentence = '外部システムとの連携画面を設計中です。' WHERE term_ja = '連携画面';
UPDATE it_glossary SET example_sentence = '開発用のサーバーを発注しました。' WHERE term_ja = '発注' AND category = 'dev';
UPDATE it_glossary SET example_sentence = '製品の出荷前に最終テストを実施します。' WHERE term_ja = '出荷';
UPDATE it_glossary SET example_sentence = 'プロジェクトの初期段階から参画しています。' WHERE term_ja = '参画';
UPDATE it_glossary SET example_sentence = '包括的なテスト計画を策定しましょう。' WHERE term_ja = '包括的';
UPDATE it_glossary SET example_sentence = 'プロジェクト計画の策定が完了しました。' WHERE term_ja = '策定';
UPDATE it_glossary SET example_sentence = 'コーディングスタイルを一貫して統一してください。' WHERE term_ja = '一貫する';
UPDATE it_glossary SET example_sentence = '開発プロセスの改善を推進する方針です。' WHERE term_ja = '推進する';
UPDATE it_glossary SET example_sentence = '利害関係者の意見を調整する必要があります。' WHERE term_ja = '利害';
UPDATE it_glossary SET example_sentence = 'ドキュメントを体系的に整理してください。' WHERE term_ja = '体系的';
UPDATE it_glossary SET example_sentence = '修正による影響範囲を事前に調査してください。' WHERE term_ja = '影響範囲';
UPDATE it_glossary SET example_sentence = 'テスト中に不具合が発見されたので修正します。' WHERE term_ja = '不具合' AND category = 'dev' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = '障害の原因を切り分けて調査しています。' WHERE term_ja = '切り分け';
UPDATE it_glossary SET example_sentence = 'まず正常系のテストケースを作成してください。' WHERE term_ja = '正常系';
UPDATE it_glossary SET example_sentence = '異常系のテストも忘れずに実施してください。' WHERE term_ja = '異常系';
UPDATE it_glossary SET example_sentence = '例外系のパターンも考慮して設計します。' WHERE term_ja = '例外系';
UPDATE it_glossary SET example_sentence = '境界値テストで入力の上限と下限を確認します。' WHERE term_ja = '境界値';
UPDATE it_glossary SET example_sentence = 'プロジェクトの成果物一覧を作成してください。' WHERE term_ja = '成果物' AND category = 'dev' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'テストの結果物をフォルダにまとめてください。' WHERE term_ja = '結果物';
UPDATE it_glossary SET example_sentence = '製品の説明書を日本語で作成してください。' WHERE term_ja = '説明書';
UPDATE it_glossary SET example_sentence = '契約書の内容を法務部に確認してもらいます。' WHERE term_ja = '契約書' AND category = 'dev';
UPDATE it_glossary SET example_sentence = 'ネットワークの構成図を更新してください。' WHERE term_ja = '構成図';
UPDATE it_glossary SET example_sentence = 'インターフェース定義書を作成して共有します。' WHERE term_ja = '定義書';
UPDATE it_glossary SET example_sentence = '最新の技術書を参考にして設計を行います。' WHERE term_ja = '技術書';
UPDATE it_glossary SET example_sentence = '会議の議事録を作成して参加者に共有してください。' WHERE term_ja = '議事録';

-- ============================================
-- it (34 terms)
-- ============================================
UPDATE it_glossary SET example_sentence = 'サービスのグレードに応じて料金プランが異なります。' WHERE term_ja = 'グレード';
UPDATE it_glossary SET example_sentence = 'システムの移行性を考慮して設計を進めています。' WHERE term_ja = '移行性';
UPDATE it_glossary SET example_sentence = 'ミドルウェアのバージョンを最新に更新してください。' WHERE term_ja = 'ミドルウェア';
UPDATE it_glossary SET example_sentence = '入出力系のテストを優先的に実施してください。' WHERE term_ja = '入出力系';
UPDATE it_glossary SET example_sentence = 'サーバーのメンテナンスを今週末に実施します。' WHERE term_ja = 'メンテナンス';
UPDATE it_glossary SET example_sentence = 'エラーはソースコードの120行目で発生しています。' WHERE term_ja = '行目';
UPDATE it_glossary SET example_sentence = '提案書をブラッシュアップしてから提出してください。' WHERE term_ja = 'ブラッシュアップ';
UPDATE it_glossary SET example_sentence = '顧客の要望に合わせてシステムをカスタマイズします。' WHERE term_ja = 'カスタマイズ';
UPDATE it_glossary SET example_sentence = 'マイクロサービスは疎結合な設計が基本です。' WHERE term_ja = '疎結合';
UPDATE it_glossary SET example_sentence = 'システム構成図を作成して全体像を把握しましょう。' WHERE term_ja = 'システム構成図' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'ER図を見ながらテーブル間の関連を確認します。' WHERE term_ja = 'ER図' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'ステークホルダーへの定期報告を準備してください。' WHERE term_ja = 'ステークホルダー' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'スケジュール通りに進捗しているか確認します。' WHERE term_ja = 'スケジュール' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'リスク管理表を定期的に更新してください。' WHERE term_ja = 'リスク管理' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'プロジェクトのリードを担当しています。' WHERE term_ja = 'リード';
UPDATE it_glossary SET example_sentence = 'コードレビューを依頼しましたので確認をお願いします。' WHERE term_ja = 'レビュー';
UPDATE it_glossary SET example_sentence = '来週のリリースに向けて準備を進めています。' WHERE term_ja = 'リリース' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'ステージング環境にデプロイして動作確認を行います。' WHERE term_ja = 'デプロイ';
UPDATE it_glossary SET example_sentence = 'エラーハンドリングを適切に実装してください。' WHERE term_ja = 'エラーハンドリング';
UPDATE it_glossary SET example_sentence = '一覧画面にページネーションを実装しました。' WHERE term_ja = 'ページネーション';
UPDATE it_glossary SET example_sentence = 'フォーム入力のバリデーションを追加してください。' WHERE term_ja = 'バリデーション';
UPDATE it_glossary SET example_sentence = '入力チェック機能を画面に実装しました。' WHERE term_ja = '入力チェック';
UPDATE it_glossary SET example_sentence = 'リモート環境からサーバーに接続します。' WHERE term_ja = 'リモート';
UPDATE it_glossary SET example_sentence = 'フロントエンドの実装をReactで進めています。' WHERE term_ja = 'フロントエンド';
UPDATE it_glossary SET example_sentence = 'バックエンドのAPIを先に完成させます。' WHERE term_ja = 'バックエンド';
UPDATE it_glossary SET example_sentence = 'ビジネスロジックをサーバー側に実装します。' WHERE term_ja = 'ロジック';
UPDATE it_glossary SET example_sentence = 'ログイン機能に二段階認証を追加しました。' WHERE term_ja = 'ログイン';
UPDATE it_glossary SET example_sentence = '開発用の環境設定を完了しました。' WHERE term_ja = '環境設定';
UPDATE it_glossary SET example_sentence = 'アプリケーションのローグを分析して問題を特定します。' WHERE term_ja = 'ローグ';
UPDATE it_glossary SET example_sentence = '業務フローを図にまとめて共有してください。' WHERE term_ja = 'フロー';
UPDATE it_glossary SET example_sentence = 'ガントチャートで各タスクの期間を可視化します。' WHERE term_ja = 'ガントチャート' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'ローコードツールを使って管理画面を素早く開発しました。' WHERE term_ja = 'ローコード';
UPDATE it_glossary SET example_sentence = 'ノーコードで簡単な業務アプリを作成しました。' WHERE term_ja = 'ノーコード';
UPDATE it_glossary SET example_sentence = '複雑な機能はプロコードで開発する必要があります。' WHERE term_ja = 'プロコード';

-- ============================================
-- business (119 terms)
-- ============================================
UPDATE it_glossary SET example_sentence = '施主の要望に沿った提案書を作成してください。' WHERE term_ja = '施主';
UPDATE it_glossary SET example_sentence = 'クライアントへのヒアリングを来週実施する予定です。' WHERE term_ja = 'ヒアリング';
UPDATE it_glossary SET example_sentence = '故障した部位を特定して報告してください。' WHERE term_ja = '部位';
UPDATE it_glossary SET example_sentence = '要件をすべて網羅しているか確認してください。' WHERE term_ja = '網羅';
UPDATE it_glossary SET example_sentence = 'テスト業務を外部に委託する予定です。' WHERE term_ja = '委託';
UPDATE it_glossary SET example_sentence = '納品物の検収を来週までに完了してください。' WHERE term_ja = '検収' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = '動作確認は複数回実施してください。' WHERE term_ja = '複数回';
UPDATE it_glossary SET example_sentence = '接続先のサーバー情報を確認してください。' WHERE term_ja = '接続先';
UPDATE it_glossary SET example_sentence = '契約書に必要な注釈を追加してください。' WHERE term_ja = '注釈';
UPDATE it_glossary SET example_sentence = '各メンバーにタスクを割り当てました。' WHERE term_ja = '割り当て';
UPDATE it_glossary SET example_sentence = 'メールの宛先を間違えないように注意してください。' WHERE term_ja = '宛先';
UPDATE it_glossary SET example_sentence = '業務委託契約を締結しました。' WHERE term_ja = '締結';
UPDATE it_glossary SET example_sentence = '来月セキュリティ監査が予定されています。' WHERE term_ja = '監査';
UPDATE it_glossary SET example_sentence = '下流工程の担当者と連携して進めてください。' WHERE term_ja = '下流';
UPDATE it_glossary SET example_sentence = '開発期間を短縮するために自動化を導入します。' WHERE term_ja = '短縮';
UPDATE it_glossary SET example_sentence = '四半期ごとに損益を報告する必要があります。' WHERE term_ja = '損益';
UPDATE it_glossary SET example_sentence = '研修動画の上映を会議室で行います。' WHERE term_ja = '上映';
UPDATE it_glossary SET example_sentence = '準委任契約でエンジニアを確保しました。' WHERE term_ja = '準委';
UPDATE it_glossary SET example_sentence = '契約条件について交渉を進めています。' WHERE term_ja = '交渉';
UPDATE it_glossary SET example_sentence = '両社の提案は互角だと評価されました。' WHERE term_ja = '互角だ';
UPDATE it_glossary SET example_sentence = '情報技術は現代文明を大きく変えました。' WHERE term_ja = '文明';
UPDATE it_glossary SET example_sentence = 'ヨーロッパ風のデザインを参考にしました。' WHERE term_ja = 'ヨーロッパ風';
UPDATE it_glossary SET example_sentence = 'プロジェクトの予算を工面する必要があります。' WHERE term_ja = '工面する';
UPDATE it_glossary SET example_sentence = '部品を洗浄液に浸してから組み立ててください。' WHERE term_ja = '浸す';
UPDATE it_glossary SET example_sentence = '人材の斡旋サービスを利用しています。' WHERE term_ja = '斡旋';
UPDATE it_glossary SET example_sentence = '契約には2年縛りの条件が含まれています。' WHERE term_ja = '縛り';
UPDATE it_glossary SET example_sentence = 'プロジェクト全体を俯瞰して課題を整理しましょう。' WHERE term_ja = '俯瞰';
UPDATE it_glossary SET example_sentence = '入力値は整数のみ受け付ける仕様です。' WHERE term_ja = '整数';
UPDATE it_glossary SET example_sentence = '契約を途中解除すると違約金が発生します。' WHERE term_ja = '違約金';
UPDATE it_glossary SET example_sentence = '経営の透明性を高めることが求められています。' WHERE term_ja = '透明性';
UPDATE it_glossary SET example_sentence = '品質管理を基軸に事業を展開しています。' WHERE term_ja = '基軸';
UPDATE it_glossary SET example_sentence = '現場での経験を身をもって実感しました。' WHERE term_ja = '身をもって実感';
UPDATE it_glossary SET example_sentence = '俯瞰系の視点でシステム全体を把握してください。' WHERE term_ja = '俯瞰系';
UPDATE it_glossary SET example_sentence = 'まず基本機能を実装してから拡張します。' WHERE term_ja = '基本機能';
UPDATE it_glossary SET example_sentence = '次のリリースで拡張機能を追加する予定です。' WHERE term_ja = '拡張機能';
UPDATE it_glossary SET example_sentence = '要件が不明確な部分はクライアントに確認してください。' WHERE term_ja = '不明確';
UPDATE it_glossary SET example_sentence = 'セキュリティ対策は最優先で対応してください。' WHERE term_ja = '最優先';
UPDATE it_glossary SET example_sentence = '他社との差別化を図るために新機能を開発します。' WHERE term_ja = '差別化';
UPDATE it_glossary SET example_sentence = '今月の業務率を集計して報告してください。' WHERE term_ja = '業務率';
UPDATE it_glossary SET example_sentence = '今後の事業展望について説明します。' WHERE term_ja = '展望';
UPDATE it_glossary SET example_sentence = 'プロジェクトの様相が大きく変わりました。' WHERE term_ja = '様相';
UPDATE it_glossary SET example_sentence = 'このライブラリの使用を推奨します。' WHERE term_ja = '推奨';
UPDATE it_glossary SET example_sentence = '納期は厳守でお願いします。' WHERE term_ja = '厳守';
UPDATE it_glossary SET example_sentence = '社内規定を遵守して業務を行ってください。' WHERE term_ja = '遵守';
UPDATE it_glossary SET example_sentence = '規約違反には制裁措置が取られます。' WHERE term_ja = '制裁';
UPDATE it_glossary SET example_sentence = '新しい評価基準を設ける方針です。' WHERE term_ja = '設ける';
UPDATE it_glossary SET example_sentence = 'コスト増加を抑制するための対策を検討します。' WHERE term_ja = '抑制';
UPDATE it_glossary SET example_sentence = 'チーム間のコミュニケーションを促進しましょう。' WHERE term_ja = '促進';
UPDATE it_glossary SET example_sentence = 'セキュリティリスクを排除するための対策を講じます。' WHERE term_ja = '排除';
UPDATE it_glossary SET example_sentence = '業務負担を軽減するために自動化を導入します。' WHERE term_ja = '軽減';
UPDATE it_glossary SET example_sentence = 'プロジェクトで得た知見を蓄積しています。' WHERE term_ja = '蓄積';
UPDATE it_glossary SET example_sentence = '新しいビジネス価値を創出することが目標です。' WHERE term_ja = '創出';
UPDATE it_glossary SET example_sentence = '予算超過のため提案が却下されました。' WHERE term_ja = '却下';
UPDATE it_glossary SET example_sentence = 'セキュリティインシデントに対して緊急措置を取りました。' WHERE term_ja = '措置';
UPDATE it_glossary SET example_sentence = 'アクセス権限を制御してセキュリティを強化します。' WHERE term_ja = '制御';
UPDATE it_glossary SET example_sentence = '肝心なのは納期を守ることです。' WHERE term_ja = '肝心';
UPDATE it_glossary SET example_sentence = 'システム設計では安全性を考慮する必要があります。' WHERE term_ja = '安全性を考慮する';
UPDATE it_glossary SET example_sentence = '契約内容に基づいて作業を進めます。' WHERE term_ja = '基づく';
UPDATE it_glossary SET example_sentence = '会議では質問の意図を正しく把握することが大切です。' WHERE term_ja = '質問の意図を正しく把握する';
UPDATE it_glossary SET example_sentence = '遠隔から会議に参加することも可能です。' WHERE term_ja = '遠隔';
UPDATE it_glossary SET example_sentence = 'クライアント先に常駐して業務を行っています。' WHERE term_ja = '常駐' AND example_sentence IS NULL;
UPDATE it_glossary SET example_sentence = 'この案件の担当者を決めてください。' WHERE term_ja = '担当者';
UPDATE it_glossary SET example_sentence = 'タスクの優先度を設定して対応してください。' WHERE term_ja = '優先度';
UPDATE it_glossary SET example_sentence = 'レポートの提出期限は今週金曜日です。' WHERE term_ja = '期限';
UPDATE it_glossary SET example_sentence = '納期に間に合うようにスケジュールを調整します。' WHERE term_ja = '納期';
UPDATE it_glossary SET example_sentence = '顧客からの要望を取りまとめてください。' WHERE term_ja = '顧客';
UPDATE it_glossary SET example_sentence = '必要な書類を準備して提出してください。' WHERE term_ja = '書類';
UPDATE it_glossary SET example_sentence = '資格の証明書のコピーを提出してください。' WHERE term_ja = '証明書';
UPDATE it_glossary SET example_sentence = 'オフィスの設備を修繕する予定です。' WHERE term_ja = '修繕';
UPDATE it_glossary SET example_sentence = 'システムの維持補修を定期的に行っています。' WHERE term_ja = '維持補修';
UPDATE it_glossary SET example_sentence = 'プロジェクトの方向先を明確にして進めましょう。' WHERE term_ja = '方向先';
UPDATE it_glossary SET example_sentence = '新しい環境にいち早く適応基盤を整えることが大切です。' WHERE term_ja = 'いち早く適応基盤を整える';
UPDATE it_glossary SET example_sentence = 'タスクの優先順位をつけて効率的に進めましょう。' WHERE term_ja = '優先順位';
UPDATE it_glossary SET example_sentence = '仕様書と実装に相違がないか確認してください。' WHERE term_ja = '相違';
UPDATE it_glossary SET example_sentence = '新しい課題に積極的に取組む姿勢が大切です。' WHERE term_ja = '取組む';
UPDATE it_glossary SET example_sentence = '外部データをシステムに取込む処理を実装します。' WHERE term_ja = '取込む';
UPDATE it_glossary SET example_sentence = '個人情報の取扱いには十分注意してください。' WHERE term_ja = '取扱い';
UPDATE it_glossary SET example_sentence = 'システムの管理者権限を設定してください。' WHERE term_ja = '管理者';
UPDATE it_glossary SET example_sentence = '予算の制約がある中で最善の方法を検討します。' WHERE term_ja = '制約';
UPDATE it_glossary SET example_sentence = '非機能要件も考慮してシステムを設計します。' WHERE term_ja = '非機能';
UPDATE it_glossary SET example_sentence = '個人情報の利用に関する同意書を取得してください。' WHERE term_ja = '同意書';
UPDATE it_glossary SET example_sentence = 'クライアントから仕様変更の了承を得ました。' WHERE term_ja = '了承';
UPDATE it_glossary SET example_sentence = '契約条件について先方の承諾を得ています。' WHERE term_ja = '承諾';
UPDATE it_glossary SET example_sentence = '納期が迫りスケジュールを圧迫しています。' WHERE term_ja = '圧迫';
UPDATE it_glossary SET example_sentence = 'サービスの解約手続きを行ってください。' WHERE term_ja = '解約';
UPDATE it_glossary SET example_sentence = '金額の計算では小数点以下を四捨五入します。' WHERE term_ja = '四捨五入';
UPDATE it_glossary SET example_sentence = '日頃から報連相を心がけてチーム連携を強化しましょう。' WHERE term_ja = '報連相(報告・連絡・相談)';
UPDATE it_glossary SET example_sentence = '今月はこのプロジェクトに専念してください。' WHERE term_ja = '専念';
UPDATE it_glossary SET example_sentence = '出勤時と退勤時に必ず打刻してください。' WHERE term_ja = '打刻';
UPDATE it_glossary SET example_sentence = '社内ルールの励行を徹底してください。' WHERE term_ja = '励行';
UPDATE it_glossary SET example_sentence = '問題が発生した場合は速やかな報告をお願いします。' WHERE term_ja = '速やかな';
UPDATE it_glossary SET example_sentence = '常に品質の向上を心掛けることが重要です。' WHERE term_ja = '心掛ける';
UPDATE it_glossary SET example_sentence = 'デスク周りの整理整頓を心がけてください。' WHERE term_ja = '整理整頓';
UPDATE it_glossary SET example_sentence = '所定の手続きを済ませてから作業を開始します。' WHERE term_ja = '所定';
UPDATE it_glossary SET example_sentence = '住所変更の届出を総務部に提出してください。' WHERE term_ja = '届出';
UPDATE it_glossary SET example_sentence = 'やむを得ない場合は上司に相談してください。' WHERE term_ja = 'やむを得ない';
UPDATE it_glossary SET example_sentence = '社内では名札を見える位置に着用してください。' WHERE term_ja = '名札';
UPDATE it_glossary SET example_sentence = 'みだりに社外秘情報を持ち出さないでください。' WHERE term_ja = 'みだり';
UPDATE it_glossary SET example_sentence = '執務時間中は業務に集中してください。' WHERE term_ja = '執務';
UPDATE it_glossary SET example_sentence = 'この案件は緊急性を帯びています。' WHERE term_ja = '帯びる';
UPDATE it_glossary SET example_sentence = '窃盗行為は懲戒処分の対象となります。' WHERE term_ja = '窃盗';
UPDATE it_glossary SET example_sentence = '横領は重大な法律違反です。' WHERE term_ja = '横領';
UPDATE it_glossary SET example_sentence = '職場での傷害事故を防止するため安全管理を徹底します。' WHERE term_ja = '傷害';
UPDATE it_glossary SET example_sentence = '刑法犯に該当する行為は厳しく処分されます。' WHERE term_ja = '刑法犯';
UPDATE it_glossary SET example_sentence = '契約違反の場合は損害賠償を請求されます。' WHERE term_ja = '損害賠償';
UPDATE it_glossary SET example_sentence = '私物の持込は事前に許可が必要です。' WHERE term_ja = '持込';
UPDATE it_glossary SET example_sentence = '社内資料の持出しは禁止されています。' WHERE term_ja = '持出し';
UPDATE it_glossary SET example_sentence = '抜き打ちでセキュリティチェックを実施します。' WHERE term_ja = '抜き打ち';
UPDATE it_glossary SET example_sentence = 'ビジネスの場に相応しい服装でお願いします。' WHERE term_ja = '相応しい';
UPDATE it_glossary SET example_sentence = '残業は極力減らすように調整してください。' WHERE term_ja = '極力';
UPDATE it_glossary SET example_sentence = '会議の資料は予め目を通しておいてください。' WHERE term_ja = '予め';
UPDATE it_glossary SET example_sentence = '職場の秩序を乱す行為は禁止されています。' WHERE term_ja = '乱す';
UPDATE it_glossary SET example_sentence = '顧客からの問い合わせには迅速に対応してください。' WHERE term_ja = '迅速';
UPDATE it_glossary SET example_sentence = '判断に迷う場合は上司の指示を仰いでください。' WHERE term_ja = '仰ぐ';
UPDATE it_glossary SET example_sentence = '会議には全員が出席することが望ましいです。' WHERE term_ja = '望ましい';
UPDATE it_glossary SET example_sentence = '報告を怠ると問題が大きくなる可能性があります。' WHERE term_ja = '怠る';
UPDATE it_glossary SET example_sentence = '遺失物を発見した場合は総務部に届けてください。' WHERE term_ja = '遺失物';
UPDATE it_glossary SET example_sentence = '不審物を発見した場合はすぐに報告してください。' WHERE term_ja = '不審物';
UPDATE it_glossary SET example_sentence = '前置きは短くして本題に入りましょう。' WHERE term_ja = '前置き';
