-- JLPT N3 漢字 シードデータ
DELETE FROM jlpt_kanji WHERE jlpt_level = 'N3';

-- Batch 1 (sort_order 1-93)
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('悪', 'アク、オ', 'わる.い', '악(悪), 나쁘다', 'bad, evil', 11, 'N3', '[{"word":"悪い","reading":"わるい","meaning":"나쁘다"},{"word":"悪化","reading":"あっか","meaning":"악화"}]'::jsonb, 2),
('暗', 'アン', 'くら.い', '암(暗), 어둡다', 'dark', 13, 'N3', '[{"word":"暗い","reading":"くらい","meaning":"어둡다"},{"word":"暗記","reading":"あんき","meaning":"암기"}]'::jsonb, 3),
('以', 'イ', NULL, '이(以), ~으로써', 'by means of, since', 5, 'N3', '[{"word":"以上","reading":"いじょう","meaning":"이상"},{"word":"以下","reading":"いか","meaning":"이하"}]'::jsonb, 4),
('意', 'イ', NULL, '의(意), 뜻', 'meaning, intention', 13, 'N3', '[{"word":"意味","reading":"いみ","meaning":"의미"},{"word":"意見","reading":"いけん","meaning":"의견"}]'::jsonb, 5),
('育', 'イク', 'そだ.つ、そだ.てる', '육(育), 기르다', 'raise, grow up', 8, 'N3', '[{"word":"育てる","reading":"そだてる","meaning":"기르다"},{"word":"教育","reading":"きょういく","meaning":"교육"}]'::jsonb, 6),
('医', 'イ', NULL, '의(醫), 의사', 'medicine, doctor', 7, 'N3', '[{"word":"医者","reading":"いしゃ","meaning":"의사"},{"word":"医学","reading":"いがく","meaning":"의학"}]'::jsonb, 7),
('位', 'イ', 'くらい', '위(位), 자리', 'rank, position', 7, 'N3', '[{"word":"位置","reading":"いち","meaning":"위치"},{"word":"単位","reading":"たんい","meaning":"단위"}]'::jsonb, 8),
('囲', 'イ', 'かこ.む、かこ.う', '위(圍), 둘러싸다', 'surround, enclose', 7, 'N3', '[{"word":"囲む","reading":"かこむ","meaning":"둘러싸다"},{"word":"範囲","reading":"はんい","meaning":"범위"}]'::jsonb, 9),
('胃', 'イ', NULL, '위(胃), 위장', 'stomach', 9, 'N3', '[{"word":"胃","reading":"い","meaning":"위"},{"word":"胃腸","reading":"いちょう","meaning":"위장"}]'::jsonb, 10),
('衣', 'イ', 'ころも', '의(衣), 옷', 'clothes, garment', 6, 'N3', '[{"word":"衣服","reading":"いふく","meaning":"의복"},{"word":"衣類","reading":"いるい","meaning":"의류"}]'::jsonb, 11),
('印', 'イン', 'しるし', '인(印), 도장', 'stamp, mark', 6, 'N3', '[{"word":"印象","reading":"いんしょう","meaning":"인상"},{"word":"印刷","reading":"いんさつ","meaning":"인쇄"}]'::jsonb, 12),
('因', 'イン', NULL, '인(因), 원인', 'cause, factor', 6, 'N3', '[{"word":"原因","reading":"げんいん","meaning":"원인"},{"word":"要因","reading":"よういん","meaning":"요인"}]'::jsonb, 13),
('引', 'イン', 'ひ.く、ひ.ける', '인(引), 끌다', 'pull, draw', 4, 'N3', '[{"word":"引く","reading":"ひく","meaning":"끌다"},{"word":"引退","reading":"いんたい","meaning":"은퇴"}]'::jsonb, 14),
('宇', 'ウ', NULL, '우(宇), 우주', 'universe, eaves', 6, 'N3', '[{"word":"宇宙","reading":"うちゅう","meaning":"우주"}]'::jsonb, 15),
('運', 'ウン', 'はこ.ぶ', '운(運), 나르다', 'carry, luck, fate', 12, 'N3', '[{"word":"運ぶ","reading":"はこぶ","meaning":"나르다"},{"word":"運動","reading":"うんどう","meaning":"운동"}]'::jsonb, 16),
('営', 'エイ', 'いとな.む', '영(營), 경영하다', 'manage, operate', 12, 'N3', '[{"word":"営業","reading":"えいぎょう","meaning":"영업"},{"word":"経営","reading":"けいえい","meaning":"경영"}]'::jsonb, 17),
('永', 'エイ', 'なが.い', '영(永), 길다', 'eternal, long', 5, 'N3', '[{"word":"永遠","reading":"えいえん","meaning":"영원"},{"word":"永久","reading":"えいきゅう","meaning":"영구"}]'::jsonb, 18),
('泳', 'エイ', 'およ.ぐ', '영(泳), 수영하다', 'swim', 8, 'N3', '[{"word":"泳ぐ","reading":"およぐ","meaning":"수영하다"},{"word":"水泳","reading":"すいえい","meaning":"수영"}]'::jsonb, 19),
('液', 'エキ', NULL, '액(液), 액체', 'liquid, fluid', 11, 'N3', '[{"word":"液体","reading":"えきたい","meaning":"액체"},{"word":"血液","reading":"けつえき","meaning":"혈액"}]'::jsonb, 20),
('演', 'エン', NULL, '연(演), 연기하다', 'perform, act', 14, 'N3', '[{"word":"演説","reading":"えんぜつ","meaning":"연설"},{"word":"演奏","reading":"えんそう","meaning":"연주"}]'::jsonb, 21),
('応', 'オウ', 'こた.える', '응(應), 응하다', 'respond, apply', 7, 'N3', '[{"word":"応じる","reading":"おうじる","meaning":"응하다"},{"word":"応用","reading":"おうよう","meaning":"응용"}]'::jsonb, 22),
('央', 'オウ', NULL, '앙(央), 가운데', 'center, middle', 5, 'N3', '[{"word":"中央","reading":"ちゅうおう","meaning":"중앙"}]'::jsonb, 23),
('億', 'オク', NULL, '억(億), 억', 'hundred million', 15, 'N3', '[{"word":"一億","reading":"いちおく","meaning":"1억"}]'::jsonb, 24),
('温', 'オン', 'あたた.かい、あたた.める', '온(溫), 따뜻하다', 'warm, temperature', 12, 'N3', '[{"word":"温かい","reading":"あたたかい","meaning":"따뜻하다"},{"word":"温度","reading":"おんど","meaning":"온도"}]'::jsonb, 25),
('化', 'カ、ケ', 'ば.ける、ば.かす', '화(化), 변하다', 'change, transform', 4, 'N3', '[{"word":"文化","reading":"ぶんか","meaning":"문화"},{"word":"変化","reading":"へんか","meaning":"변화"}]'::jsonb, 26),
('荷', 'カ', 'に', '하(荷), 짐', 'baggage, load', 10, 'N3', '[{"word":"荷物","reading":"にもつ","meaning":"짐"},{"word":"出荷","reading":"しゅっか","meaning":"출하"}]'::jsonb, 27),
('階', 'カイ', NULL, '계(階), 층', 'floor, story', 12, 'N3', '[{"word":"階段","reading":"かいだん","meaning":"계단"},{"word":"二階","reading":"にかい","meaning":"2층"}]'::jsonb, 28),
('開', 'カイ', 'ひら.く、あ.く', '개(開), 열다', 'open', 12, 'N3', '[{"word":"開く","reading":"ひらく","meaning":"열다"},{"word":"開発","reading":"かいはつ","meaning":"개발"}]'::jsonb, 29),
('界', 'カイ', NULL, '계(界), 세계', 'world, boundary', 9, 'N3', '[{"word":"世界","reading":"せかい","meaning":"세계"},{"word":"業界","reading":"ぎょうかい","meaning":"업계"}]'::jsonb, 30),
('害', 'ガイ', NULL, '해(害), 해치다', 'harm, damage', 10, 'N3', '[{"word":"被害","reading":"ひがい","meaning":"피해"},{"word":"公害","reading":"こうがい","meaning":"공해"}]'::jsonb, 31),
('各', 'カク', 'おのおの', '각(各), 각각', 'each, every', 6, 'N3', '[{"word":"各地","reading":"かくち","meaning":"각지"},{"word":"各自","reading":"かくじ","meaning":"각자"}]'::jsonb, 32),
('覚', 'カク', 'おぼ.える、さ.ます', '각(覺), 깨닫다', 'memorize, awake', 12, 'N3', '[{"word":"覚える","reading":"おぼえる","meaning":"외우다"},{"word":"感覚","reading":"かんかく","meaning":"감각"}]'::jsonb, 33),
('完', 'カン', NULL, '완(完), 완전하다', 'complete, perfect', 7, 'N3', '[{"word":"完全","reading":"かんぜん","meaning":"완전"},{"word":"完成","reading":"かんせい","meaning":"완성"}]'::jsonb, 34),
('官', 'カン', NULL, '관(官), 벼슬', 'government, official', 8, 'N3', '[{"word":"官庁","reading":"かんちょう","meaning":"관청"},{"word":"警官","reading":"けいかん","meaning":"경관"}]'::jsonb, 35),
('管', 'カン', 'くだ', '관(管), 대롱', 'pipe, tube, manage', 14, 'N3', '[{"word":"管理","reading":"かんり","meaning":"관리"},{"word":"管","reading":"くだ","meaning":"관"}]'::jsonb, 36),
('関', 'カン', 'せき、かか.わる', '관(關), 관계하다', 'connection, barrier', 14, 'N3', '[{"word":"関係","reading":"かんけい","meaning":"관계"},{"word":"関心","reading":"かんしん","meaning":"관심"}]'::jsonb, 37),
('観', 'カン', NULL, '관(觀), 보다', 'view, observe', 18, 'N3', '[{"word":"観光","reading":"かんこう","meaning":"관광"},{"word":"観客","reading":"かんきゃく","meaning":"관객"}]'::jsonb, 38),
('感', 'カン', NULL, '감(感), 느끼다', 'emotion, feeling', 13, 'N3', '[{"word":"感じる","reading":"かんじる","meaning":"느끼다"},{"word":"感動","reading":"かんどう","meaning":"감동"}]'::jsonb, 39),
('慣', 'カン', 'な.れる、な.らす', '관(慣), 익숙하다', 'accustomed, get used to', 14, 'N3', '[{"word":"慣れる","reading":"なれる","meaning":"익숙해지다"},{"word":"習慣","reading":"しゅうかん","meaning":"습관"}]'::jsonb, 40),
('換', 'カン', 'か.える、か.わる', '환(換), 바꾸다', 'exchange, replace', 12, 'N3', '[{"word":"交換","reading":"こうかん","meaning":"교환"},{"word":"換気","reading":"かんき","meaning":"환기"}]'::jsonb, 41),
('簡', 'カン', NULL, '간(簡), 간략하다', 'simple, brief', 18, 'N3', '[{"word":"簡単","reading":"かんたん","meaning":"간단"},{"word":"簡略","reading":"かんりゃく","meaning":"간략"}]'::jsonb, 42),
('丸', 'ガン', 'まる、まる.い', '환(丸), 둥글다', 'round, circle', 3, 'N3', '[{"word":"丸い","reading":"まるい","meaning":"둥글다"},{"word":"丸","reading":"まる","meaning":"원"}]'::jsonb, 43),
('含', 'ガン', 'ふく.む、ふく.める', '함(含), 포함하다', 'contain, include', 7, 'N3', '[{"word":"含む","reading":"ふくむ","meaning":"포함하다"},{"word":"含める","reading":"ふくめる","meaning":"포함시키다"}]'::jsonb, 44),
('岩', 'ガン', 'いわ', '암(岩), 바위', 'rock, cliff', 8, 'N3', '[{"word":"岩","reading":"いわ","meaning":"바위"},{"word":"岩石","reading":"がんせき","meaning":"암석"}]'::jsonb, 45),
('基', 'キ', 'もと、もとい', '기(基), 기초', 'foundation, base', 11, 'N3', '[{"word":"基本","reading":"きほん","meaning":"기본"},{"word":"基礎","reading":"きそ","meaning":"기초"}]'::jsonb, 46),
('寄', 'キ', 'よ.る、よ.せる', '기(寄), 기대다', 'approach, draw near', 11, 'N3', '[{"word":"寄る","reading":"よる","meaning":"들르다"},{"word":"寄付","reading":"きふ","meaning":"기부"}]'::jsonb, 47),
('規', 'キ', NULL, '규(規), 법', 'rule, regulation', 11, 'N3', '[{"word":"規則","reading":"きそく","meaning":"규칙"},{"word":"規模","reading":"きぼ","meaning":"규모"}]'::jsonb, 48),
('記', 'キ', 'しる.す', '기(記), 기록하다', 'record, write down', 10, 'N3', '[{"word":"記事","reading":"きじ","meaning":"기사"},{"word":"記録","reading":"きろく","meaning":"기록"}]'::jsonb, 49),
('貴', 'キ', 'とうと.い、たっと.い', '귀(貴), 귀하다', 'precious, noble', 12, 'N3', '[{"word":"貴重","reading":"きちょう","meaning":"귀중"},{"word":"貴族","reading":"きぞく","meaning":"귀족"}]'::jsonb, 50),
('起', 'キ', 'お.きる、お.こる、お.こす', '기(起), 일어나다', 'rise, wake up', 10, 'N3', '[{"word":"起きる","reading":"おきる","meaning":"일어나다"},{"word":"起こる","reading":"おこる","meaning":"발생하다"}]'::jsonb, 51),
('技', 'ギ', 'わざ', '기(技), 재주', 'skill, technique', 7, 'N3', '[{"word":"技術","reading":"ぎじゅつ","meaning":"기술"},{"word":"技能","reading":"ぎのう","meaning":"기능"}]'::jsonb, 52),
('議', 'ギ', NULL, '의(議), 의논하다', 'deliberation, discussion', 20, 'N3', '[{"word":"会議","reading":"かいぎ","meaning":"회의"},{"word":"議論","reading":"ぎろん","meaning":"의론"}]'::jsonb, 53),
('客', 'キャク、カク', NULL, '객(客), 손님', 'guest, customer', 9, 'N3', '[{"word":"客","reading":"きゃく","meaning":"손님"},{"word":"乗客","reading":"じょうきゃく","meaning":"승객"}]'::jsonb, 54),
('逆', 'ギャク', 'さか、さか.らう', '역(逆), 거스르다', 'reverse, opposite', 9, 'N3', '[{"word":"逆","reading":"ぎゃく","meaning":"역"},{"word":"逆転","reading":"ぎゃくてん","meaning":"역전"}]'::jsonb, 55),
('久', 'キュウ、ク', 'ひさ.しい', '구(久), 오래다', 'long time, old story', 3, 'N3', '[{"word":"久しぶり","reading":"ひさしぶり","meaning":"오랜만"},{"word":"永久","reading":"えいきゅう","meaning":"영구"}]'::jsonb, 56),
('旧', 'キュウ', NULL, '구(舊), 예', 'old, former', 5, 'N3', '[{"word":"旧式","reading":"きゅうしき","meaning":"구식"},{"word":"旧友","reading":"きゅうゆう","meaning":"옛 친구"}]'::jsonb, 57),
('居', 'キョ', 'い.る、お.る', '거(居), 살다', 'reside, dwell', 8, 'N3', '[{"word":"居る","reading":"いる","meaning":"있다"},{"word":"居間","reading":"いま","meaning":"거실"}]'::jsonb, 58),
('許', 'キョ', 'ゆる.す', '허(許), 허락하다', 'permit, allow', 11, 'N3', '[{"word":"許す","reading":"ゆるす","meaning":"허락하다"},{"word":"免許","reading":"めんきょ","meaning":"면허"}]'::jsonb, 59),
('共', 'キョウ', 'とも', '공(共), 함께', 'together, both', 6, 'N3', '[{"word":"共通","reading":"きょうつう","meaning":"공통"},{"word":"公共","reading":"こうきょう","meaning":"공공"}]'::jsonb, 60),
('競', 'キョウ、ケイ', 'きそ.う、せ.る', '경(競), 겨루다', 'compete, contest', 20, 'N3', '[{"word":"競争","reading":"きょうそう","meaning":"경쟁"},{"word":"競技","reading":"きょうぎ","meaning":"경기"}]'::jsonb, 61),
('況', 'キョウ', NULL, '황(況), 상황', 'condition, situation', 7, 'N3', '[{"word":"状況","reading":"じょうきょう","meaning":"상황"}]'::jsonb, 62),
('境', 'キョウ、ケイ', 'さかい', '경(境), 지경', 'boundary, border', 14, 'N3', '[{"word":"環境","reading":"かんきょう","meaning":"환경"},{"word":"国境","reading":"こっきょう","meaning":"국경"}]'::jsonb, 63),
('禁', 'キン', NULL, '금(禁), 금하다', 'prohibit, forbid', 13, 'N3', '[{"word":"禁止","reading":"きんし","meaning":"금지"},{"word":"禁煙","reading":"きんえん","meaning":"금연"}]'::jsonb, 64),
('均', 'キン', NULL, '균(均), 고르다', 'equal, level', 7, 'N3', '[{"word":"平均","reading":"へいきん","meaning":"평균"},{"word":"均等","reading":"きんとう","meaning":"균등"}]'::jsonb, 65),
('勤', 'キン、ゴン', 'つと.める', '근(勤), 부지런하다', 'work, serve', 12, 'N3', '[{"word":"勤める","reading":"つとめる","meaning":"근무하다"},{"word":"通勤","reading":"つうきん","meaning":"통근"}]'::jsonb, 66),
('筋', 'キン', 'すじ', '근(筋), 힘줄', 'muscle, sinew, plot', 12, 'N3', '[{"word":"筋肉","reading":"きんにく","meaning":"근육"},{"word":"筋","reading":"すじ","meaning":"줄기"}]'::jsonb, 67),
('句', 'ク', NULL, '구(句), 글귀', 'phrase, clause', 5, 'N3', '[{"word":"文句","reading":"もんく","meaning":"불만"},{"word":"俳句","reading":"はいく","meaning":"하이쿠"}]'::jsonb, 68),
('群', 'グン', 'む.れる、むら', '군(群), 무리', 'group, flock', 13, 'N3', '[{"word":"群れ","reading":"むれ","meaning":"무리"},{"word":"群衆","reading":"ぐんしゅう","meaning":"군중"}]'::jsonb, 69),
('係', 'ケイ', 'かか.る、かかり', '계(係), 관계하다', 'connection, duty', 9, 'N3', '[{"word":"関係","reading":"かんけい","meaning":"관계"},{"word":"係","reading":"かかり","meaning":"담당"}]'::jsonb, 70),
('型', 'ケイ', 'かた', '형(型), 거푸집', 'type, model, mold', 9, 'N3', '[{"word":"型","reading":"かた","meaning":"형"},{"word":"大型","reading":"おおがた","meaning":"대형"}]'::jsonb, 71),
('景', 'ケイ', NULL, '경(景), 경치', 'scenery, landscape', 12, 'N3', '[{"word":"景色","reading":"けしき","meaning":"경치"},{"word":"風景","reading":"ふうけい","meaning":"풍경"}]'::jsonb, 72),
('芸', 'ゲイ', NULL, '예(藝), 재주', 'art, craft, skill', 7, 'N3', '[{"word":"芸術","reading":"げいじゅつ","meaning":"예술"},{"word":"芸能","reading":"げいのう","meaning":"예능"}]'::jsonb, 73),
('欠', 'ケツ', 'か.ける、か.く', '결(缺), 이지러지다', 'lack, gap', 4, 'N3', '[{"word":"欠点","reading":"けってん","meaning":"결점"},{"word":"欠席","reading":"けっせき","meaning":"결석"}]'::jsonb, 74),
('結', 'ケツ', 'むす.ぶ、ゆ.う', '결(結), 맺다', 'tie, bind, conclude', 12, 'N3', '[{"word":"結ぶ","reading":"むすぶ","meaning":"맺다"},{"word":"結果","reading":"けっか","meaning":"결과"}]'::jsonb, 75),
('件', 'ケン', NULL, '건(件), 일', 'matter, case, item', 6, 'N3', '[{"word":"事件","reading":"じけん","meaning":"사건"},{"word":"条件","reading":"じょうけん","meaning":"조건"}]'::jsonb, 76),
('券', 'ケン', NULL, '권(券), 문서', 'ticket, certificate', 8, 'N3', '[{"word":"乗車券","reading":"じょうしゃけん","meaning":"승차권"},{"word":"入場券","reading":"にゅうじょうけん","meaning":"입장권"}]'::jsonb, 77),
('険', 'ケン', 'けわ.しい', '험(險), 험하다', 'steep, dangerous', 11, 'N3', '[{"word":"危険","reading":"きけん","meaning":"위험"},{"word":"保険","reading":"ほけん","meaning":"보험"}]'::jsonb, 78),
('検', 'ケン', NULL, '검(檢), 검사하다', 'examine, inspect', 12, 'N3', '[{"word":"検査","reading":"けんさ","meaning":"검사"},{"word":"検討","reading":"けんとう","meaning":"검토"}]'::jsonb, 79),
('限', 'ゲン', 'かぎ.る、かぎ.り', '한(限), 한정하다', 'limit, restrict', 9, 'N3', '[{"word":"限る","reading":"かぎる","meaning":"한정하다"},{"word":"制限","reading":"せいげん","meaning":"제한"}]'::jsonb, 80),
('現', 'ゲン', 'あらわ.れる、あらわ.す', '현(現), 나타나다', 'present, appear', 11, 'N3', '[{"word":"現在","reading":"げんざい","meaning":"현재"},{"word":"現れる","reading":"あらわれる","meaning":"나타나다"}]'::jsonb, 81),
('減', 'ゲン', 'へ.る、へ.らす', '감(減), 줄다', 'decrease, reduce', 12, 'N3', '[{"word":"減る","reading":"へる","meaning":"줄다"},{"word":"減少","reading":"げんしょう","meaning":"감소"}]'::jsonb, 82),
('原', 'ゲン', 'はら', '원(原), 벌판', 'origin, plain, field', 10, 'N3', '[{"word":"原因","reading":"げんいん","meaning":"원인"},{"word":"原料","reading":"げんりょう","meaning":"원료"}]'::jsonb, 83),
('個', 'コ', NULL, '개(個), 낱', 'individual, counter', 10, 'N3', '[{"word":"個人","reading":"こじん","meaning":"개인"},{"word":"一個","reading":"いっこ","meaning":"한 개"}]'::jsonb, 84),
('故', 'コ', 'ゆえ', '고(故), 연고', 'old, reason, cause', 9, 'N3', '[{"word":"故障","reading":"こしょう","meaning":"고장"},{"word":"事故","reading":"じこ","meaning":"사고"}]'::jsonb, 85),
('湖', 'コ', 'みずうみ', '호(湖), 호수', 'lake', 12, 'N3', '[{"word":"湖","reading":"みずうみ","meaning":"호수"},{"word":"湖畔","reading":"こはん","meaning":"호반"}]'::jsonb, 86),
('己', 'コ、キ', 'おのれ', '기(己), 자기', 'self, oneself', 3, 'N3', '[{"word":"自己","reading":"じこ","meaning":"자기"},{"word":"利己","reading":"りこ","meaning":"이기"}]'::jsonb, 87),
('庫', 'コ、ク', 'くら', '고(庫), 곳간', 'storehouse, warehouse', 10, 'N3', '[{"word":"倉庫","reading":"そうこ","meaning":"창고"},{"word":"車庫","reading":"しゃこ","meaning":"차고"}]'::jsonb, 88),
('呼', 'コ', 'よ.ぶ', '호(呼), 부르다', 'call, invite', 8, 'N3', '[{"word":"呼ぶ","reading":"よぶ","meaning":"부르다"},{"word":"呼吸","reading":"こきゅう","meaning":"호흡"}]'::jsonb, 89),
('交', 'コウ', 'まじ.わる、ま.ぜる、か.わす', '교(交), 사귀다', 'exchange, mix', 6, 'N3', '[{"word":"交通","reading":"こうつう","meaning":"교통"},{"word":"交換","reading":"こうかん","meaning":"교환"}]'::jsonb, 90),
('候', 'コウ', 'そうろう', '후(候), 기후', 'climate, season, wait', 10, 'N3', '[{"word":"天候","reading":"てんこう","meaning":"천후"},{"word":"気候","reading":"きこう","meaning":"기후"}]'::jsonb, 91),
('向', 'コウ', 'む.く、む.ける、む.かう', '향(向), 향하다', 'face, turn toward', 6, 'N3', '[{"word":"向く","reading":"むく","meaning":"향하다"},{"word":"方向","reading":"ほうこう","meaning":"방향"}]'::jsonb, 92),
('港', 'コウ', 'みなと', '항(港), 항구', 'harbor, port', 12, 'N3', '[{"word":"港","reading":"みなと","meaning":"항구"},{"word":"空港","reading":"くうこう","meaning":"공항"}]'::jsonb, 93);

-- Batch 2 (sort_order 94-186)
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('構', 'コウ', 'かま.える、かま.う', '구(構), 얽다', 'construct, care about', 14, 'N3', '[{"word":"構造","reading":"こうぞう","meaning":"구조"},{"word":"構う","reading":"かまう","meaning":"상관하다"}]'::jsonb, 94),
('耕', 'コウ', 'たがや.す', '경(耕), 갈다', 'plow, cultivate', 10, 'N3', '[{"word":"耕す","reading":"たがやす","meaning":"갈다"},{"word":"農耕","reading":"のうこう","meaning":"농경"}]'::jsonb, 95),
('鉱', 'コウ', NULL, '광(鑛), 쇳돌', 'mineral, ore', 13, 'N3', '[{"word":"鉱物","reading":"こうぶつ","meaning":"광물"},{"word":"鉱山","reading":"こうざん","meaning":"광산"}]'::jsonb, 96),
('効', 'コウ', 'き.く', '효(效), 효험', 'effect, result', 8, 'N3', '[{"word":"効果","reading":"こうか","meaning":"효과"},{"word":"有効","reading":"ゆうこう","meaning":"유효"}]'::jsonb, 97),
('厚', 'コウ', 'あつ.い', '후(厚), 두텁다', 'thick, kind', 9, 'N3', '[{"word":"厚い","reading":"あつい","meaning":"두껍다"},{"word":"厚生","reading":"こうせい","meaning":"후생"}]'::jsonb, 98),
('公', 'コウ', 'おおやけ', '공(公), 공평하다', 'public, official', 4, 'N3', '[{"word":"公園","reading":"こうえん","meaning":"공원"},{"word":"公共","reading":"こうきょう","meaning":"공공"}]'::jsonb, 99),
('功', 'コウ、ク', NULL, '공(功), 공', 'achievement, merit', 5, 'N3', '[{"word":"成功","reading":"せいこう","meaning":"성공"},{"word":"功績","reading":"こうせき","meaning":"공적"}]'::jsonb, 100),
('降', 'コウ', 'お.りる、ふ.る', '강(降), 내리다', 'descend, fall', 10, 'N3', '[{"word":"降りる","reading":"おりる","meaning":"내리다"},{"word":"降る","reading":"ふる","meaning":"내리다(비)"}]'::jsonb, 101),
('混', 'コン', 'ま.ぜる、こ.む', '혼(混), 섞다', 'mix, blend', 11, 'N3', '[{"word":"混ぜる","reading":"まぜる","meaning":"섞다"},{"word":"混雑","reading":"こんざつ","meaning":"혼잡"}]'::jsonb, 102),
('差', 'サ', 'さ.す', '차(差), 다르다', 'difference, distinction', 10, 'N3', '[{"word":"差","reading":"さ","meaning":"차이"},{"word":"差別","reading":"さべつ","meaning":"차별"}]'::jsonb, 103),
('査', 'サ', NULL, '사(査), 조사하다', 'investigate, inspect', 9, 'N3', '[{"word":"調査","reading":"ちょうさ","meaning":"조사"},{"word":"検査","reading":"けんさ","meaning":"검사"}]'::jsonb, 104),
('再', 'サイ、サ', 'ふたた.び', '재(再), 다시', 'again, re-', 6, 'N3', '[{"word":"再び","reading":"ふたたび","meaning":"다시"},{"word":"再生","reading":"さいせい","meaning":"재생"}]'::jsonb, 105),
('災', 'サイ', 'わざわ.い', '재(災), 재앙', 'disaster, calamity', 7, 'N3', '[{"word":"災害","reading":"さいがい","meaning":"재해"},{"word":"火災","reading":"かさい","meaning":"화재"}]'::jsonb, 106),
('際', 'サイ', 'きわ', '제(際), 즈음', 'occasion, edge', 14, 'N3', '[{"word":"国際","reading":"こくさい","meaning":"국제"},{"word":"実際","reading":"じっさい","meaning":"실제"}]'::jsonb, 107),
('材', 'ザイ', NULL, '재(材), 재목', 'material, wood', 7, 'N3', '[{"word":"材料","reading":"ざいりょう","meaning":"재료"},{"word":"人材","reading":"じんざい","meaning":"인재"}]'::jsonb, 108),
('罪', 'ザイ', 'つみ', '죄(罪), 허물', 'crime, sin', 13, 'N3', '[{"word":"罪","reading":"つみ","meaning":"죄"},{"word":"犯罪","reading":"はんざい","meaning":"범죄"}]'::jsonb, 109),
('財', 'ザイ、サイ', NULL, '재(財), 재물', 'wealth, property', 10, 'N3', '[{"word":"財産","reading":"ざいさん","meaning":"재산"},{"word":"財布","reading":"さいふ","meaning":"지갑"}]'::jsonb, 110),
('算', 'サン', NULL, '산(算), 세다', 'calculate, count', 14, 'N3', '[{"word":"計算","reading":"けいさん","meaning":"계산"},{"word":"予算","reading":"よさん","meaning":"예산"}]'::jsonb, 111),
('参', 'サン', 'まい.る', '참(參), 참여하다', 'participate, visit', 8, 'N3', '[{"word":"参加","reading":"さんか","meaning":"참가"},{"word":"参考","reading":"さんこう","meaning":"참고"}]'::jsonb, 112),
('賛', 'サン', NULL, '찬(贊), 도울', 'approve, praise', 15, 'N3', '[{"word":"賛成","reading":"さんせい","meaning":"찬성"},{"word":"賛同","reading":"さんどう","meaning":"찬동"}]'::jsonb, 113),
('残', 'ザン', 'のこ.る、のこ.す', '잔(殘), 남다', 'remain, left over', 10, 'N3', '[{"word":"残る","reading":"のこる","meaning":"남다"},{"word":"残念","reading":"ざんねん","meaning":"유감"}]'::jsonb, 114),
('志', 'シ', 'こころざ.す、こころざし', '지(志), 뜻', 'will, intention', 7, 'N3', '[{"word":"志望","reading":"しぼう","meaning":"지망"},{"word":"志","reading":"こころざし","meaning":"뜻"}]'::jsonb, 115),
('師', 'シ', NULL, '사(師), 스승', 'teacher, master', 10, 'N3', '[{"word":"教師","reading":"きょうし","meaning":"교사"},{"word":"医師","reading":"いし","meaning":"의사"}]'::jsonb, 116),
('指', 'シ', 'ゆび、さ.す', '지(指), 가리키다', 'finger, point', 9, 'N3', '[{"word":"指","reading":"ゆび","meaning":"손가락"},{"word":"指示","reading":"しじ","meaning":"지시"}]'::jsonb, 117),
('支', 'シ', 'ささ.える', '지(支), 지탱하다', 'support, branch', 4, 'N3', '[{"word":"支える","reading":"ささえる","meaning":"지탱하다"},{"word":"支持","reading":"しじ","meaning":"지지"}]'::jsonb, 118),
('資', 'シ', NULL, '자(資), 재물', 'resources, capital', 13, 'N3', '[{"word":"資料","reading":"しりょう","meaning":"자료"},{"word":"投資","reading":"とうし","meaning":"투자"}]'::jsonb, 119),
('似', 'ジ', 'に.る', '사(似), 닮다', 'resemble, similar', 7, 'N3', '[{"word":"似る","reading":"にる","meaning":"닮다"},{"word":"似合う","reading":"にあう","meaning":"어울리다"}]'::jsonb, 120),
('識', 'シキ', NULL, '식(識), 알다', 'know, discriminate', 19, 'N3', '[{"word":"知識","reading":"ちしき","meaning":"지식"},{"word":"意識","reading":"いしき","meaning":"의식"}]'::jsonb, 121),
('示', 'ジ、シ', 'しめ.す', '시(示), 보이다', 'show, indicate', 5, 'N3', '[{"word":"示す","reading":"しめす","meaning":"보이다"},{"word":"指示","reading":"しじ","meaning":"지시"}]'::jsonb, 122),
('詞', 'シ', NULL, '사(詞), 말', 'words, part of speech', 12, 'N3', '[{"word":"歌詞","reading":"かし","meaning":"가사"},{"word":"名詞","reading":"めいし","meaning":"명사"}]'::jsonb, 123),
('捨', 'シャ', 'す.てる', '사(捨), 버리다', 'throw away, discard', 11, 'N3', '[{"word":"捨てる","reading":"すてる","meaning":"버리다"}]'::jsonb, 124),
('若', 'ジャク、ニャク', 'わか.い、も.しくは', '약(若), 젊다', 'young, if', 8, 'N3', '[{"word":"若い","reading":"わかい","meaning":"젊다"},{"word":"若者","reading":"わかもの","meaning":"젊은이"}]'::jsonb, 125),
('周', 'シュウ', 'まわ.り', '주(周), 두루', 'circumference, around', 8, 'N3', '[{"word":"周り","reading":"まわり","meaning":"주위"},{"word":"周囲","reading":"しゅうい","meaning":"주위"}]'::jsonb, 126),
('州', 'シュウ', 'す', '주(州), 고을', 'state, province', 6, 'N3', '[{"word":"九州","reading":"きゅうしゅう","meaning":"규슈"},{"word":"州","reading":"しゅう","meaning":"주"}]'::jsonb, 127),
('収', 'シュウ', 'おさ.める、おさ.まる', '수(收), 거두다', 'collect, obtain', 4, 'N3', '[{"word":"収入","reading":"しゅうにゅう","meaning":"수입"},{"word":"回収","reading":"かいしゅう","meaning":"회수"}]'::jsonb, 128),
('宗', 'シュウ、ソウ', 'むね', '종(宗), 마루', 'religion, sect', 8, 'N3', '[{"word":"宗教","reading":"しゅうきょう","meaning":"종교"},{"word":"宗派","reading":"しゅうは","meaning":"종파"}]'::jsonb, 129),
('就', 'シュウ、ジュ', 'つ.く、つ.ける', '취(就), 나아가다', 'settle in, take position', 12, 'N3', '[{"word":"就職","reading":"しゅうしょく","meaning":"취직"},{"word":"就く","reading":"つく","meaning":"취임하다"}]'::jsonb, 130),
('修', 'シュウ、シュ', 'おさ.める、おさ.まる', '수(修), 닦다', 'repair, study', 10, 'N3', '[{"word":"修理","reading":"しゅうり","meaning":"수리"},{"word":"研修","reading":"けんしゅう","meaning":"연수"}]'::jsonb, 131),
('拾', 'シュウ、ジュウ', 'ひろ.う', '습(拾), 줍다', 'pick up, gather', 9, 'N3', '[{"word":"拾う","reading":"ひろう","meaning":"줍다"}]'::jsonb, 132),
('祝', 'シュク、シュウ', 'いわ.う', '축(祝), 빌다', 'celebrate, congratulate', 9, 'N3', '[{"word":"祝う","reading":"いわう","meaning":"축하하다"},{"word":"祝日","reading":"しゅくじつ","meaning":"공휴일"}]'::jsonb, 133),
('術', 'ジュツ', NULL, '술(術), 재주', 'art, technique, skill', 11, 'N3', '[{"word":"技術","reading":"ぎじゅつ","meaning":"기술"},{"word":"芸術","reading":"げいじゅつ","meaning":"예술"}]'::jsonb, 134),
('述', 'ジュツ', 'の.べる', '술(述), 기술하다', 'state, mention', 8, 'N3', '[{"word":"述べる","reading":"のべる","meaning":"기술하다"},{"word":"記述","reading":"きじゅつ","meaning":"기술"}]'::jsonb, 135),
('準', 'ジュン', NULL, '준(準), 기준', 'standard, level', 13, 'N3', '[{"word":"準備","reading":"じゅんび","meaning":"준비"},{"word":"基準","reading":"きじゅん","meaning":"기준"}]'::jsonb, 136),
('順', 'ジュン', NULL, '순(順), 순서', 'order, sequence', 12, 'N3', '[{"word":"順番","reading":"じゅんばん","meaning":"순서"},{"word":"順調","reading":"じゅんちょう","meaning":"순조"}]'::jsonb, 137),
('処', 'ショ', NULL, '처(處), 곳', 'dispose, deal with', 5, 'N3', '[{"word":"処理","reading":"しょり","meaning":"처리"},{"word":"処分","reading":"しょぶん","meaning":"처분"}]'::jsonb, 138),
('署', 'ショ', NULL, '서(署), 관서', 'government office', 13, 'N3', '[{"word":"警察署","reading":"けいさつしょ","meaning":"경찰서"},{"word":"消防署","reading":"しょうぼうしょ","meaning":"소방서"}]'::jsonb, 139),
('除', 'ジョ、ジ', 'のぞ.く', '제(除), 덜다', 'remove, exclude', 10, 'N3', '[{"word":"除く","reading":"のぞく","meaning":"제거하다"},{"word":"掃除","reading":"そうじ","meaning":"청소"}]'::jsonb, 140),
('商', 'ショウ', 'あきな.う', '상(商), 장사', 'commerce, trade', 11, 'N3', '[{"word":"商品","reading":"しょうひん","meaning":"상품"},{"word":"商売","reading":"しょうばい","meaning":"장사"}]'::jsonb, 141),
('焼', 'ショウ', 'や.く、や.ける', '소(燒), 태우다', 'burn, bake, roast', 12, 'N3', '[{"word":"焼く","reading":"やく","meaning":"굽다"},{"word":"焼ける","reading":"やける","meaning":"타다"}]'::jsonb, 142),
('照', 'ショウ', 'て.る、て.らす', '조(照), 비추다', 'illuminate, shine', 13, 'N3', '[{"word":"照らす","reading":"てらす","meaning":"비추다"},{"word":"参照","reading":"さんしょう","meaning":"참조"}]'::jsonb, 143),
('章', 'ショウ', NULL, '장(章), 글', 'chapter, badge', 11, 'N3', '[{"word":"文章","reading":"ぶんしょう","meaning":"문장"},{"word":"章","reading":"しょう","meaning":"장"}]'::jsonb, 144),
('象', 'ショウ、ゾウ', NULL, '상(象), 코끼리', 'elephant, phenomenon', 12, 'N3', '[{"word":"印象","reading":"いんしょう","meaning":"인상"},{"word":"対象","reading":"たいしょう","meaning":"대상"}]'::jsonb, 145),
('賞', 'ショウ', NULL, '상(賞), 상', 'prize, reward', 15, 'N3', '[{"word":"賞","reading":"しょう","meaning":"상"},{"word":"受賞","reading":"じゅしょう","meaning":"수상"}]'::jsonb, 146),
('状', 'ジョウ', NULL, '장(狀), 형상', 'condition, letter', 7, 'N3', '[{"word":"状態","reading":"じょうたい","meaning":"상태"},{"word":"状況","reading":"じょうきょう","meaning":"상황"}]'::jsonb, 147),
('条', 'ジョウ', NULL, '조(條), 가지', 'article, clause, strip', 7, 'N3', '[{"word":"条件","reading":"じょうけん","meaning":"조건"},{"word":"条約","reading":"じょうやく","meaning":"조약"}]'::jsonb, 148),
('常', 'ジョウ', 'つね、とこ', '상(常), 항상', 'usual, ordinary', 11, 'N3', '[{"word":"常に","reading":"つねに","meaning":"항상"},{"word":"非常","reading":"ひじょう","meaning":"비상"}]'::jsonb, 149),
('情', 'ジョウ、セイ', 'なさ.け', '정(情), 뜻', 'emotion, feeling, fact', 11, 'N3', '[{"word":"情報","reading":"じょうほう","meaning":"정보"},{"word":"感情","reading":"かんじょう","meaning":"감정"}]'::jsonb, 150),
('職', 'ショク', NULL, '직(職), 직분', 'employment, job', 18, 'N3', '[{"word":"職業","reading":"しょくぎょう","meaning":"직업"},{"word":"就職","reading":"しゅうしょく","meaning":"취직"}]'::jsonb, 151),
('信', 'シン', NULL, '신(信), 믿다', 'believe, trust', 9, 'N3', '[{"word":"信じる","reading":"しんじる","meaning":"믿다"},{"word":"自信","reading":"じしん","meaning":"자신감"}]'::jsonb, 152),
('深', 'シン', 'ふか.い、ふか.める', '심(深), 깊다', 'deep, profound', 11, 'N3', '[{"word":"深い","reading":"ふかい","meaning":"깊다"},{"word":"深夜","reading":"しんや","meaning":"심야"}]'::jsonb, 153),
('申', 'シン', 'もう.す', '신(申), 펴다', 'say, report (humble)', 5, 'N3', '[{"word":"申す","reading":"もうす","meaning":"말씀드리다"},{"word":"申し込む","reading":"もうしこむ","meaning":"신청하다"}]'::jsonb, 154),
('神', 'シン、ジン', 'かみ、かん', '신(神), 귀신', 'god, spirit', 9, 'N3', '[{"word":"神様","reading":"かみさま","meaning":"신"},{"word":"神社","reading":"じんじゃ","meaning":"신사"}]'::jsonb, 155),
('身', 'シン', 'み', '신(身), 몸', 'body, oneself', 7, 'N3', '[{"word":"身体","reading":"しんたい","meaning":"신체"},{"word":"自身","reading":"じしん","meaning":"자신"}]'::jsonb, 156),
('針', 'シン', 'はり', '침(針), 바늘', 'needle, pin', 10, 'N3', '[{"word":"針","reading":"はり","meaning":"바늘"},{"word":"方針","reading":"ほうしん","meaning":"방침"}]'::jsonb, 157),
('吹', 'スイ', 'ふ.く', '취(吹), 불다', 'blow, breathe, puff', 7, 'N3', '[{"word":"吹く","reading":"ふく","meaning":"불다"},{"word":"吹雪","reading":"ふぶき","meaning":"눈보라"}]'::jsonb, 158),
('推', 'スイ', 'お.す', '추(推), 밀다', 'conjecture, infer', 11, 'N3', '[{"word":"推定","reading":"すいてい","meaning":"추정"},{"word":"推薦","reading":"すいせん","meaning":"추천"}]'::jsonb, 159),
('性', 'セイ、ショウ', NULL, '성(性), 성품', 'nature, sex, gender', 8, 'N3', '[{"word":"性格","reading":"せいかく","meaning":"성격"},{"word":"女性","reading":"じょせい","meaning":"여성"}]'::jsonb, 160),
('成', 'セイ、ジョウ', 'な.る、な.す', '성(成), 이루다', 'become, achieve', 6, 'N3', '[{"word":"成功","reading":"せいこう","meaning":"성공"},{"word":"完成","reading":"かんせい","meaning":"완성"}]'::jsonb, 161),
('政', 'セイ、ショウ', 'まつりごと', '정(政), 정사', 'politics, government', 9, 'N3', '[{"word":"政治","reading":"せいじ","meaning":"정치"},{"word":"政府","reading":"せいふ","meaning":"정부"}]'::jsonb, 162),
('整', 'セイ', 'ととの.える、ととの.う', '정(整), 가지런하다', 'arrange, adjust', 16, 'N3', '[{"word":"整理","reading":"せいり","meaning":"정리"},{"word":"調整","reading":"ちょうせい","meaning":"조정"}]'::jsonb, 163),
('精', 'セイ、ショウ', NULL, '정(精), 정미', 'refined, spirit', 14, 'N3', '[{"word":"精神","reading":"せいしん","meaning":"정신"},{"word":"精密","reading":"せいみつ","meaning":"정밀"}]'::jsonb, 164),
('製', 'セイ', NULL, '제(製), 만들다', 'manufacture, make', 14, 'N3', '[{"word":"製品","reading":"せいひん","meaning":"제품"},{"word":"製造","reading":"せいぞう","meaning":"제조"}]'::jsonb, 165),
('税', 'ゼイ', NULL, '세(稅), 세금', 'tax, duty', 12, 'N3', '[{"word":"税金","reading":"ぜいきん","meaning":"세금"},{"word":"消費税","reading":"しょうひぜい","meaning":"소비세"}]'::jsonb, 166),
('絶', 'ゼツ', 'た.える、た.やす、た.つ', '절(絶), 끊다', 'sever, discontinue', 12, 'N3', '[{"word":"絶対","reading":"ぜったい","meaning":"절대"},{"word":"絶える","reading":"たえる","meaning":"끊기다"}]'::jsonb, 167),
('設', 'セツ', 'もう.ける', '설(設), 베풀다', 'establish, set up', 11, 'N3', '[{"word":"設計","reading":"せっけい","meaning":"설계"},{"word":"設備","reading":"せつび","meaning":"설비"}]'::jsonb, 168),
('善', 'ゼン', 'よ.い', '선(善), 착하다', 'good, virtuous', 12, 'N3', '[{"word":"善悪","reading":"ぜんあく","meaning":"선악"},{"word":"改善","reading":"かいぜん","meaning":"개선"}]'::jsonb, 169),
('祖', 'ソ', NULL, '조(祖), 할아버지', 'ancestor, grandfather', 9, 'N3', '[{"word":"祖父","reading":"そふ","meaning":"할아버지"},{"word":"祖母","reading":"そぼ","meaning":"할머니"}]'::jsonb, 170),
('素', 'ソ、ス', NULL, '소(素), 본디', 'element, plain', 10, 'N3', '[{"word":"素晴らしい","reading":"すばらしい","meaning":"훌륭하다"},{"word":"素材","reading":"そざい","meaning":"소재"}]'::jsonb, 171),
('組', 'ソ', 'く.む、くみ', '조(組), 짜다', 'group, assemble', 11, 'N3', '[{"word":"組む","reading":"くむ","meaning":"짜다"},{"word":"番組","reading":"ばんぐみ","meaning":"프로그램"}]'::jsonb, 172),
('想', 'ソウ', NULL, '상(想), 생각하다', 'concept, idea', 13, 'N3', '[{"word":"想像","reading":"そうぞう","meaning":"상상"},{"word":"感想","reading":"かんそう","meaning":"감상"}]'::jsonb, 173),
('相', 'ソウ、ショウ', 'あい', '상(相), 서로', 'mutual, phase', 9, 'N3', '[{"word":"相手","reading":"あいて","meaning":"상대"},{"word":"相談","reading":"そうだん","meaning":"상담"}]'::jsonb, 174),
('送', 'ソウ', 'おく.る', '송(送), 보내다', 'send, transmit', 9, 'N3', '[{"word":"送る","reading":"おくる","meaning":"보내다"},{"word":"放送","reading":"ほうそう","meaning":"방송"}]'::jsonb, 175),
('増', 'ゾウ', 'ま.す、ふ.える、ふ.やす', '증(增), 더하다', 'increase, add', 14, 'N3', '[{"word":"増える","reading":"ふえる","meaning":"늘다"},{"word":"増加","reading":"ぞうか","meaning":"증가"}]'::jsonb, 176),
('側', 'ソク', 'がわ', '측(側), 곁', 'side, faction', 11, 'N3', '[{"word":"側","reading":"がわ","meaning":"쪽"},{"word":"両側","reading":"りょうがわ","meaning":"양쪽"}]'::jsonb, 177),
('則', 'ソク', NULL, '칙(則), 법칙', 'rule, law', 9, 'N3', '[{"word":"規則","reading":"きそく","meaning":"규칙"},{"word":"法則","reading":"ほうそく","meaning":"법칙"}]'::jsonb, 178),
('測', 'ソク', 'はか.る', '측(測), 재다', 'measure, fathom', 12, 'N3', '[{"word":"測る","reading":"はかる","meaning":"재다"},{"word":"観測","reading":"かんそく","meaning":"관측"}]'::jsonb, 179),
('属', 'ゾク', NULL, '속(屬), 붙다', 'belong, genus', 12, 'N3', '[{"word":"金属","reading":"きんぞく","meaning":"금속"},{"word":"所属","reading":"しょぞく","meaning":"소속"}]'::jsonb, 180),
('率', 'リツ、ソツ', 'ひき.いる', '율(率), 비율', 'rate, ratio, lead', 11, 'N3', '[{"word":"確率","reading":"かくりつ","meaning":"확률"},{"word":"率","reading":"りつ","meaning":"비율"}]'::jsonb, 181),
('退', 'タイ', 'しりぞ.く、しりぞ.ける', '퇴(退), 물러나다', 'retreat, withdraw', 9, 'N3', '[{"word":"退く","reading":"しりぞく","meaning":"물러나다"},{"word":"引退","reading":"いんたい","meaning":"은퇴"}]'::jsonb, 182),
('態', 'タイ', NULL, '태(態), 모양', 'attitude, condition', 14, 'N3', '[{"word":"状態","reading":"じょうたい","meaning":"상태"},{"word":"態度","reading":"たいど","meaning":"태도"}]'::jsonb, 183),
('対', 'タイ、ツイ', NULL, '대(對), 대하다', 'oppose, versus', 7, 'N3', '[{"word":"対象","reading":"たいしょう","meaning":"대상"},{"word":"反対","reading":"はんたい","meaning":"반대"}]'::jsonb, 184),
('宅', 'タク', NULL, '택(宅), 집', 'home, house, residence', 6, 'N3', '[{"word":"自宅","reading":"じたく","meaning":"자택"},{"word":"宅配","reading":"たくはい","meaning":"택배"}]'::jsonb, 185),
('達', 'タツ', NULL, '달(達), 통달하다', 'reach, arrive, attain', 12, 'N3', '[{"word":"友達","reading":"ともだち","meaning":"친구"},{"word":"達成","reading":"たっせい","meaning":"달성"}]'::jsonb, 186);

-- Batch 3 (sort_order 187-286)
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('担', 'タン', 'かつ.ぐ、にな.う', '담(擔), 메다', 'carry, bear', 8, 'N3', '[{"word":"担当","reading":"たんとう","meaning":"담당"},{"word":"負担","reading":"ふたん","meaning":"부담"}]'::jsonb, 187),
('断', 'ダン', 'ことわ.る、た.つ', '단(斷), 끊다', 'refuse, cut off', 11, 'N3', '[{"word":"断る","reading":"ことわる","meaning":"거절하다"},{"word":"判断","reading":"はんだん","meaning":"판단"}]'::jsonb, 188),
('値', 'チ', 'ね、あたい', '치(値), 값', 'value, price', 10, 'N3', '[{"word":"値段","reading":"ねだん","meaning":"값"},{"word":"価値","reading":"かち","meaning":"가치"}]'::jsonb, 189),
('仲', 'チュウ', 'なか', '중(仲), 사이', 'relationship, go-between', 6, 'N3', '[{"word":"仲間","reading":"なかま","meaning":"동료"},{"word":"仲良し","reading":"なかよし","meaning":"친한 사이"}]'::jsonb, 191),
('貯', 'チョ', NULL, '저(貯), 저축하다', 'savings, store', 12, 'N3', '[{"word":"貯金","reading":"ちょきん","meaning":"저금"},{"word":"貯蓄","reading":"ちょちく","meaning":"저축"}]'::jsonb, 192),
('挑', 'チョウ', 'いど.む', '도(挑), 도전하다', 'challenge', 9, 'N3', '[{"word":"挑戦","reading":"ちょうせん","meaning":"도전"},{"word":"挑む","reading":"いどむ","meaning":"도전하다"}]'::jsonb, 193),
('調', 'チョウ', 'しら.べる、ととの.える', '조(調), 조사하다', 'investigate, tune', 15, 'N3', '[{"word":"調べる","reading":"しらべる","meaning":"조사하다"},{"word":"調子","reading":"ちょうし","meaning":"상태"}]'::jsonb, 194),
('築', 'チク', 'きず.く', '축(築), 쌓다', 'build, construct', 16, 'N3', '[{"word":"建築","reading":"けんちく","meaning":"건축"},{"word":"築く","reading":"きずく","meaning":"쌓다"}]'::jsonb, 195),
('追', 'ツイ', 'お.う', '추(追), 쫓다', 'chase, pursue', 9, 'N3', '[{"word":"追う","reading":"おう","meaning":"쫓다"},{"word":"追加","reading":"ついか","meaning":"추가"}]'::jsonb, 196),
('痛', 'ツウ', 'いた.い、いた.む', '통(痛), 아프다', 'pain, ache', 12, 'N3', '[{"word":"痛い","reading":"いたい","meaning":"아프다"},{"word":"頭痛","reading":"ずつう","meaning":"두통"}]'::jsonb, 197),
('滞', 'タイ', 'とどこお.る', '체(滞), 체류하다', 'stagnate, stay', 13, 'N3', '[{"word":"滞在","reading":"たいざい","meaning":"체재"},{"word":"渋滞","reading":"じゅうたい","meaning":"정체"}]'::jsonb, 198),
('適', 'テキ', NULL, '적(適), 적당하다', 'suitable, fit', 14, 'N3', '[{"word":"適当","reading":"てきとう","meaning":"적당"},{"word":"適切","reading":"てきせつ","meaning":"적절"}]'::jsonb, 199),
('伝', 'デン', 'つた.わる、つた.える', '전(伝), 전하다', 'transmit, legend', 6, 'N3', '[{"word":"伝える","reading":"つたえる","meaning":"전하다"},{"word":"伝統","reading":"でんとう","meaning":"전통"}]'::jsonb, 200),
('投', 'トウ', 'な.げる', '투(投), 던지다', 'throw, invest', 7, 'N3', '[{"word":"投げる","reading":"なげる","meaning":"던지다"},{"word":"投資","reading":"とうし","meaning":"투자"}]'::jsonb, 201),
('盗', 'トウ', 'ぬす.む', '도(盗), 훔치다', 'steal, rob', 11, 'N3', '[{"word":"盗む","reading":"ぬすむ","meaning":"훔치다"},{"word":"盗難","reading":"とうなん","meaning":"도난"}]'::jsonb, 202),
('等', 'トウ', 'ひと.しい', '등(等), 같다', 'equal, class', 12, 'N3', '[{"word":"平等","reading":"びょうどう","meaning":"평등"},{"word":"等しい","reading":"ひとしい","meaning":"같다"}]'::jsonb, 203),
('毒', 'ドク', NULL, '독(毒), 독', 'poison, toxic', 8, 'N3', '[{"word":"毒","reading":"どく","meaning":"독"},{"word":"中毒","reading":"ちゅうどく","meaning":"중독"}]'::jsonb, 204),
('独', 'ドク', 'ひと.り', '독(独), 홀로', 'alone, unique', 9, 'N3', '[{"word":"独立","reading":"どくりつ","meaning":"독립"},{"word":"独特","reading":"どくとく","meaning":"독특"}]'::jsonb, 205),
('届', NULL, 'とど.ける、とど.く', '届, 닿다, 전달하다', 'deliver, reach', 8, 'N3', '[{"word":"届ける","reading":"とどける","meaning":"전달하다"},{"word":"届く","reading":"とどく","meaning":"닿다"}]'::jsonb, 206),
('任', 'ニン', 'まか.せる', '임(任), 맡기다', 'entrust, responsibility', 6, 'N3', '[{"word":"任せる","reading":"まかせる","meaning":"맡기다"},{"word":"任務","reading":"にんむ","meaning":"임무"}]'::jsonb, 207),
('燃', 'ネン', 'も.える、も.やす', '연(燃), 타다', 'burn, fuel', 16, 'N3', '[{"word":"燃える","reading":"もえる","meaning":"타다"},{"word":"燃料","reading":"ねんりょう","meaning":"연료"}]'::jsonb, 208),
('脳', 'ノウ', NULL, '뇌(脳), 뇌', 'brain', 11, 'N3', '[{"word":"頭脳","reading":"ずのう","meaning":"두뇌"},{"word":"脳","reading":"のう","meaning":"뇌"}]'::jsonb, 209),
('濃', 'ノウ', 'こ.い', '농(濃), 짙다', 'thick, concentrated', 16, 'N3', '[{"word":"濃い","reading":"こい","meaning":"짙다"},{"word":"濃度","reading":"のうど","meaning":"농도"}]'::jsonb, 210);

-- Batch 4 (sort_order 211-310)
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('認', 'ニン', 'みと.める', '인(認), 인정하다', 'recognize, approve', 14, 'N3', '[{"word":"認める","reading":"みとめる","meaning":"인정하다"},{"word":"確認","reading":"かくにん","meaning":"확인"}]'::jsonb, 211),
('熱', 'ネツ', 'あつ.い', '열(熱), 뜨겁다', 'heat, fever', 15, 'N3', '[{"word":"熱い","reading":"あつい","meaning":"뜨겁다"},{"word":"熱心","reading":"ねっしん","meaning":"열심"}]'::jsonb, 212),
('農', 'ノウ', NULL, '농(農), 농사', 'agriculture, farming', 13, 'N3', '[{"word":"農業","reading":"のうぎょう","meaning":"농업"},{"word":"農家","reading":"のうか","meaning":"농가"}]'::jsonb, 213),
('能', 'ノウ', NULL, '능(能), 능력', 'ability, talent', 10, 'N3', '[{"word":"能力","reading":"のうりょく","meaning":"능력"},{"word":"可能","reading":"かのう","meaning":"가능"}]'::jsonb, 214),
('波', 'ハ', 'なみ', '파(波), 물결', 'wave', 8, 'N3', '[{"word":"波","reading":"なみ","meaning":"파도"},{"word":"電波","reading":"でんぱ","meaning":"전파"}]'::jsonb, 215),
('破', 'ハ', 'やぶ.る、やぶ.れる', '파(破), 깨뜨리다', 'break, destroy', 10, 'N3', '[{"word":"破る","reading":"やぶる","meaning":"깨뜨리다"},{"word":"破壊","reading":"はかい","meaning":"파괴"}]'::jsonb, 216),
('配', 'ハイ', 'くば.る', '배(配), 나누다', 'distribute, deliver', 10, 'N3', '[{"word":"配る","reading":"くばる","meaning":"나누다"},{"word":"心配","reading":"しんぱい","meaning":"걱정"}]'::jsonb, 217),
('拝', 'ハイ', 'おが.む', '배(拝), 절하다', 'worship, pray', 8, 'N3', '[{"word":"拝む","reading":"おがむ","meaning":"절하다"},{"word":"拝見","reading":"はいけん","meaning":"배견"}]'::jsonb, 218),
('敗', 'ハイ', 'やぶ.れる', '패(敗), 지다', 'defeat, failure', 11, 'N3', '[{"word":"失敗","reading":"しっぱい","meaning":"실패"},{"word":"敗北","reading":"はいぼく","meaning":"패배"}]'::jsonb, 219),
('背', 'ハイ', 'せ、そむ.く', '배(背), 등', 'back, behind', 9, 'N3', '[{"word":"背中","reading":"せなか","meaning":"등"},{"word":"背景","reading":"はいけい","meaning":"배경"}]'::jsonb, 220),
('倍', 'バイ', NULL, '배(倍), 곱', 'double, times', 10, 'N3', '[{"word":"倍","reading":"ばい","meaning":"배"},{"word":"何倍","reading":"なんばい","meaning":"몇 배"}]'::jsonb, 221),
('爆', 'バク', NULL, '폭(爆), 터지다', 'bomb, explode', 19, 'N3', '[{"word":"爆発","reading":"ばくはつ","meaning":"폭발"},{"word":"爆弾","reading":"ばくだん","meaning":"폭탄"}]'::jsonb, 222),
('箱', NULL, 'はこ', '상(箱), 상자', 'box', 15, 'N3', '[{"word":"箱","reading":"はこ","meaning":"상자"},{"word":"本箱","reading":"ほんばこ","meaning":"책장"}]'::jsonb, 223),
('畑', NULL, 'はたけ、はた', '전(畑), 밭', 'field, farm', 9, 'N3', '[{"word":"畑","reading":"はたけ","meaning":"밭"},{"word":"花畑","reading":"はなばたけ","meaning":"꽃밭"}]'::jsonb, 224),
('判', 'ハン、バン', NULL, '판(判), 판단하다', 'judge, decide', 7, 'N3', '[{"word":"判断","reading":"はんだん","meaning":"판단"},{"word":"裁判","reading":"さいばん","meaning":"재판"}]'::jsonb, 225),
('版', 'ハン', NULL, '판(版), 판', 'edition, printing', 8, 'N3', '[{"word":"出版","reading":"しゅっぱん","meaning":"출판"},{"word":"版","reading":"ばん","meaning":"판"}]'::jsonb, 226),
('犯', 'ハン', 'おか.す', '범(犯), 범하다', 'crime, commit', 5, 'N3', '[{"word":"犯人","reading":"はんにん","meaning":"범인"},{"word":"犯罪","reading":"はんざい","meaning":"범죄"}]'::jsonb, 227),
('販', 'ハン', NULL, '판(販), 팔다', 'sell, trade', 11, 'N3', '[{"word":"販売","reading":"はんばい","meaning":"판매"},{"word":"自販機","reading":"じはんき","meaning":"자판기"}]'::jsonb, 228),
('比', 'ヒ', 'くら.べる', '비(比), 비교하다', 'compare, ratio', 4, 'N3', '[{"word":"比べる","reading":"くらべる","meaning":"비교하다"},{"word":"比較","reading":"ひかく","meaning":"비교"}]'::jsonb, 229),
('否', 'ヒ', 'いな', '부(否), 아니다', 'deny, negate', 7, 'N3', '[{"word":"否定","reading":"ひてい","meaning":"부정"},{"word":"可否","reading":"かひ","meaning":"가부"}]'::jsonb, 230),
('費', 'ヒ', 'つい.やす', '비(費), 쓰다', 'expense, cost', 12, 'N3', '[{"word":"費用","reading":"ひよう","meaning":"비용"},{"word":"消費","reading":"しょうひ","meaning":"소비"}]'::jsonb, 231),
('非', 'ヒ', NULL, '비(非), 아니다', 'non-, un-, wrong', 8, 'N3', '[{"word":"非常","reading":"ひじょう","meaning":"비상"},{"word":"非常に","reading":"ひじょうに","meaning":"매우"}]'::jsonb, 232),
('美', 'ビ', 'うつく.しい', '미(美), 아름답다', 'beauty, beautiful', 9, 'N3', '[{"word":"美しい","reading":"うつくしい","meaning":"아름답다"},{"word":"美術","reading":"びじゅつ","meaning":"미술"}]'::jsonb, 233),
('必', 'ヒツ', 'かなら.ず', '필(必), 반드시', 'necessarily, must', 5, 'N3', '[{"word":"必ず","reading":"かならず","meaning":"반드시"},{"word":"必要","reading":"ひつよう","meaning":"필요"}]'::jsonb, 234),
('筆', 'ヒツ', 'ふで', '필(筆), 붓', 'writing brush, pen', 12, 'N3', '[{"word":"筆","reading":"ふで","meaning":"붓"},{"word":"鉛筆","reading":"えんぴつ","meaning":"연필"}]'::jsonb, 235),
('氷', 'ヒョウ', 'こおり', '빙(氷), 얼음', 'ice', 5, 'N3', '[{"word":"氷","reading":"こおり","meaning":"얼음"},{"word":"氷山","reading":"ひょうざん","meaning":"빙산"}]'::jsonb, 236),
('評', 'ヒョウ', NULL, '평(評), 평가하다', 'evaluate, comment', 12, 'N3', '[{"word":"評価","reading":"ひょうか","meaning":"평가"},{"word":"批評","reading":"ひひょう","meaning":"비평"}]'::jsonb, 237),
('表', 'ヒョウ', 'おもて、あらわ.す', '표(表), 나타내다', 'surface, express', 8, 'N3', '[{"word":"表","reading":"おもて","meaning":"표면"},{"word":"発表","reading":"はっぴょう","meaning":"발표"}]'::jsonb, 238),
('貧', 'ヒン、ビン', 'まず.しい', '빈(貧), 가난하다', 'poor, poverty', 11, 'N3', '[{"word":"貧しい","reading":"まずしい","meaning":"가난하다"},{"word":"貧困","reading":"ひんこん","meaning":"빈곤"}]'::jsonb, 239),
('婦', 'フ', NULL, '부(婦), 여자', 'woman, wife', 11, 'N3', '[{"word":"夫婦","reading":"ふうふ","meaning":"부부"},{"word":"主婦","reading":"しゅふ","meaning":"주부"}]'::jsonb, 240),
('富', 'フ、フウ', 'と.む、とみ', '부(富), 부유하다', 'wealth, rich', 12, 'N3', '[{"word":"豊富","reading":"ほうふ","meaning":"풍부"},{"word":"富","reading":"とみ","meaning":"부"}]'::jsonb, 241),
('負', 'フ', 'ま.ける、お.う', '부(負), 지다', 'lose, bear, owe', 9, 'N3', '[{"word":"負ける","reading":"まける","meaning":"지다"},{"word":"負担","reading":"ふたん","meaning":"부담"}]'::jsonb, 242),
('布', 'フ', 'ぬの', '포(布), 천', 'cloth, spread', 5, 'N3', '[{"word":"布","reading":"ぬの","meaning":"천"},{"word":"分布","reading":"ぶんぷ","meaning":"분포"}]'::jsonb, 243),
('府', 'フ', NULL, '부(府), 관청', 'government, urban prefecture', 8, 'N3', '[{"word":"政府","reading":"せいふ","meaning":"정부"},{"word":"府","reading":"ふ","meaning":"부"}]'::jsonb, 244),
('武', 'ブ、ム', NULL, '무(武), 무예', 'military, martial', 8, 'N3', '[{"word":"武器","reading":"ぶき","meaning":"무기"},{"word":"武道","reading":"ぶどう","meaning":"무도"}]'::jsonb, 245),
('復', 'フク', NULL, '복(復), 돌아오다', 'restore, return', 12, 'N3', '[{"word":"回復","reading":"かいふく","meaning":"회복"},{"word":"復活","reading":"ふっかつ","meaning":"부활"}]'::jsonb, 246),
('複', 'フク', NULL, '복(複), 겹치다', 'duplicate, complex', 14, 'N3', '[{"word":"複雑","reading":"ふくざつ","meaning":"복잡"},{"word":"複数","reading":"ふくすう","meaning":"복수"}]'::jsonb, 247),
('仏', 'ブツ、フツ', 'ほとけ', '불(仏), 부처', 'Buddha, France', 4, 'N3', '[{"word":"仏教","reading":"ぶっきょう","meaning":"불교"},{"word":"仏","reading":"ほとけ","meaning":"부처"}]'::jsonb, 248),
('払', 'フツ', 'はら.う', '불(払), 치르다', 'pay, clear away', 5, 'N3', '[{"word":"払う","reading":"はらう","meaning":"치르다"},{"word":"支払い","reading":"しはらい","meaning":"지불"}]'::jsonb, 249),
('粉', 'フン', 'こ、こな', '분(粉), 가루', 'powder, flour', 10, 'N3', '[{"word":"粉","reading":"こな","meaning":"가루"},{"word":"花粉","reading":"かふん","meaning":"꽃가루"}]'::jsonb, 250),
('編', 'ヘン', 'あ.む', '편(編), 엮다', 'knit, compile, edit', 15, 'N3', '[{"word":"編集","reading":"へんしゅう","meaning":"편집"},{"word":"編む","reading":"あむ","meaning":"뜨다"}]'::jsonb, 251),
('辺', 'ヘン', 'あた.り', '변(辺), 근처', 'area, vicinity', 5, 'N3', '[{"word":"辺り","reading":"あたり","meaning":"근처"},{"word":"周辺","reading":"しゅうへん","meaning":"주변"}]'::jsonb, 252),
('返', 'ヘン', 'かえ.す、かえ.る', '반(返), 돌려주다', 'return, give back', 7, 'N3', '[{"word":"返す","reading":"かえす","meaning":"돌려주다"},{"word":"返事","reading":"へんじ","meaning":"대답"}]'::jsonb, 253),
('便', 'ベン、ビン', 'たよ.り', '편(便), 편리하다', 'convenience, mail', 9, 'N3', '[{"word":"便利","reading":"べんり","meaning":"편리"},{"word":"便","reading":"びん","meaning":"편"}]'::jsonb, 254),
('保', 'ホ', 'たも.つ', '보(保), 지키다', 'protect, maintain', 9, 'N3', '[{"word":"保つ","reading":"たもつ","meaning":"유지하다"},{"word":"保険","reading":"ほけん","meaning":"보험"}]'::jsonb, 255),
('捕', 'ホ', 'と.らえる、つか.まえる', '포(捕), 잡다', 'catch, capture', 10, 'N3', '[{"word":"捕まえる","reading":"つかまえる","meaning":"잡다"},{"word":"逮捕","reading":"たいほ","meaning":"체포"}]'::jsonb, 256),
('報', 'ホウ', 'むく.いる', '보(報), 알리다', 'report, reward', 12, 'N3', '[{"word":"報告","reading":"ほうこく","meaning":"보고"},{"word":"情報","reading":"じょうほう","meaning":"정보"}]'::jsonb, 257),
('法', 'ホウ', NULL, '법(法), 법', 'law, method', 8, 'N3', '[{"word":"法律","reading":"ほうりつ","meaning":"법률"},{"word":"方法","reading":"ほうほう","meaning":"방법"}]'::jsonb, 258),
('防', 'ボウ', 'ふせ.ぐ', '방(防), 막다', 'prevent, defend', 7, 'N3', '[{"word":"防ぐ","reading":"ふせぐ","meaning":"막다"},{"word":"予防","reading":"よぼう","meaning":"예방"}]'::jsonb, 259),
('貿', 'ボウ', NULL, '무(貿), 무역', 'trade, exchange', 12, 'N3', '[{"word":"貿易","reading":"ぼうえき","meaning":"무역"}]'::jsonb, 260),
('暴', 'ボウ、バク', 'あば.く、あば.れる', '폭(暴), 사나운', 'violent, expose', 15, 'N3', '[{"word":"暴力","reading":"ぼうりょく","meaning":"폭력"},{"word":"暴れる","reading":"あばれる","meaning":"날뛰다"}]'::jsonb, 261),
('棒', 'ボウ', NULL, '봉(棒), 막대기', 'stick, pole', 12, 'N3', '[{"word":"棒","reading":"ぼう","meaning":"막대기"},{"word":"泥棒","reading":"どろぼう","meaning":"도둑"}]'::jsonb, 262),
('望', 'ボウ、モウ', 'のぞ.む', '망(望), 바라다', 'desire, hope', 11, 'N3', '[{"word":"望む","reading":"のぞむ","meaning":"바라다"},{"word":"希望","reading":"きぼう","meaning":"희망"}]'::jsonb, 263),
('末', 'マツ、バツ', 'すえ', '말(末), 끝', 'end, tip', 5, 'N3', '[{"word":"週末","reading":"しゅうまつ","meaning":"주말"},{"word":"末","reading":"すえ","meaning":"끝"}]'::jsonb, 264),
('磨', NULL, 'みが.く', '마(磨), 갈다', 'polish, grind', 16, 'N3', '[{"word":"磨く","reading":"みがく","meaning":"닦다"},{"word":"研磨","reading":"けんま","meaning":"연마"}]'::jsonb, 265),
('密', 'ミツ', NULL, '밀(密), 빽빽하다', 'secret, dense', 11, 'N3', '[{"word":"秘密","reading":"ひみつ","meaning":"비밀"},{"word":"密接","reading":"みっせつ","meaning":"밀접"}]'::jsonb, 266),
('民', 'ミン', NULL, '민(民), 백성', 'people, nation', 5, 'N3', '[{"word":"国民","reading":"こくみん","meaning":"국민"},{"word":"市民","reading":"しみん","meaning":"시민"}]'::jsonb, 267),
('務', 'ム', 'つと.める', '무(務), 힘쓰다', 'duty, task', 11, 'N3', '[{"word":"義務","reading":"ぎむ","meaning":"의무"},{"word":"事務","reading":"じむ","meaning":"사무"}]'::jsonb, 268),
('夢', 'ム', 'ゆめ', '몽(夢), 꿈', 'dream', 13, 'N3', '[{"word":"夢","reading":"ゆめ","meaning":"꿈"},{"word":"夢中","reading":"むちゅう","meaning":"열중"}]'::jsonb, 269),
('命', 'メイ、ミョウ', 'いのち', '명(命), 목숨', 'life, command', 8, 'N3', '[{"word":"命","reading":"いのち","meaning":"목숨"},{"word":"命令","reading":"めいれい","meaning":"명령"}]'::jsonb, 270);

-- Batch 5 (sort_order 271-370)
INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('迷', 'メイ', 'まよ.う', '미(迷), 헤매다', 'be lost, hesitate', 9, 'N3', '[{"word":"迷う","reading":"まよう","meaning":"헤매다"},{"word":"迷惑","reading":"めいわく","meaning":"폐"}]'::jsonb, 271),
('綿', 'メン', 'わた', '면(綿), 솜', 'cotton', 14, 'N3', '[{"word":"綿","reading":"わた","meaning":"솜"},{"word":"木綿","reading":"もめん","meaning":"무명"}]'::jsonb, 272),
('面', 'メン', 'おも、おもて、つら', '면(面), 얼굴, 면', 'face, surface', 9, 'N3', '[{"word":"面","reading":"めん","meaning":"면"},{"word":"表面","reading":"ひょうめん","meaning":"표면"}]'::jsonb, 273),
('戻', NULL, 'もど.す、もど.る', '려(戻), 되돌리다', 'return, revert', 7, 'N3', '[{"word":"戻る","reading":"もどる","meaning":"돌아오다"},{"word":"戻す","reading":"もどす","meaning":"되돌리다"}]'::jsonb, 274),
('約', 'ヤク', NULL, '약(約), 약속하다', 'promise, approximately', 9, 'N3', '[{"word":"約束","reading":"やくそく","meaning":"약속"},{"word":"予約","reading":"よやく","meaning":"예약"}]'::jsonb, 275),
('薬', 'ヤク', 'くすり', '약(薬), 약', 'medicine, drug', 16, 'N3', '[{"word":"薬","reading":"くすり","meaning":"약"},{"word":"薬局","reading":"やっきょく","meaning":"약국"}]'::jsonb, 276),
('油', 'ユ、ユウ', 'あぶら', '유(油), 기름', 'oil', 8, 'N3', '[{"word":"油","reading":"あぶら","meaning":"기름"},{"word":"石油","reading":"せきゆ","meaning":"석유"}]'::jsonb, 277),
('輸', 'ユ', NULL, '수(輸), 나르다', 'transport, ship', 16, 'N3', '[{"word":"輸入","reading":"ゆにゅう","meaning":"수입"},{"word":"輸出","reading":"ゆしゅつ","meaning":"수출"}]'::jsonb, 278),
('余', 'ヨ', 'あま.る', '여(余), 남다', 'surplus, remainder', 7, 'N3', '[{"word":"余る","reading":"あまる","meaning":"남다"},{"word":"余裕","reading":"よゆう","meaning":"여유"}]'::jsonb, 279),
('予', 'ヨ', NULL, '예(予), 미리', 'beforehand, previous', 4, 'N3', '[{"word":"予約","reading":"よやく","meaning":"예약"},{"word":"予定","reading":"よてい","meaning":"예정"}]'::jsonb, 280),
('養', 'ヨウ', 'やしな.う', '양(養), 기르다', 'cultivate, foster', 15, 'N3', '[{"word":"養う","reading":"やしなう","meaning":"기르다"},{"word":"栄養","reading":"えいよう","meaning":"영양"}]'::jsonb, 281),
('様', 'ヨウ', 'さま', '양(様), 모양', 'manner, Mr/Ms', 14, 'N3', '[{"word":"様子","reading":"ようす","meaning":"상태"},{"word":"同様","reading":"どうよう","meaning":"동일"}]'::jsonb, 282),
('浴', 'ヨク', 'あ.びる', '욕(浴), 목욕하다', 'bathe', 10, 'N3', '[{"word":"入浴","reading":"にゅうよく","meaning":"입욕"},{"word":"浴びる","reading":"あびる","meaning":"뒤집어쓰다"}]'::jsonb, 283),
('頼', 'ライ', 'たの.む、たよ.る', '뢰(頼), 부탁하다', 'request, rely on', 16, 'N3', '[{"word":"依頼","reading":"いらい","meaning":"의뢰"},{"word":"頼む","reading":"たのむ","meaning":"부탁하다"}]'::jsonb, 284),
('利', 'リ', 'き.く', '리(利), 이익', 'profit, advantage', 7, 'N3', '[{"word":"利用","reading":"りよう","meaning":"이용"},{"word":"便利","reading":"べんり","meaning":"편리"}]'::jsonb, 285),
('裏', 'リ', 'うら', '리(裏), 뒤', 'reverse, back', 13, 'N3', '[{"word":"裏","reading":"うら","meaning":"뒤"},{"word":"裏側","reading":"うらがわ","meaning":"뒷면"}]'::jsonb, 286),
('律', 'リツ', NULL, '률(律), 법칙', 'rhythm, law', 9, 'N3', '[{"word":"法律","reading":"ほうりつ","meaning":"법률"},{"word":"規律","reading":"きりつ","meaning":"규율"}]'::jsonb, 287),
('量', 'リョウ', 'はか.る', '량(量), 양', 'quantity, amount', 12, 'N3', '[{"word":"量","reading":"りょう","meaning":"양"},{"word":"大量","reading":"たいりょう","meaning":"대량"}]'::jsonb, 288),
('領', 'リョウ', NULL, '령(領), 다스리다', 'territory, govern', 14, 'N3', '[{"word":"領土","reading":"りょうど","meaning":"영토"},{"word":"大統領","reading":"だいとうりょう","meaning":"대통령"}]'::jsonb, 289),
('例', 'レイ', 'たと.える', '례(例), 예', 'example, custom', 8, 'N3', '[{"word":"例えば","reading":"たとえば","meaning":"예를 들면"},{"word":"例","reading":"れい","meaning":"예"}]'::jsonb, 290),
('連', 'レン', 'つら.なる、つ.れる', '련(連), 연결하다', 'connect, accompany', 10, 'N3', '[{"word":"連絡","reading":"れんらく","meaning":"연락"},{"word":"連れる","reading":"つれる","meaning":"데리다"}]'::jsonb, 291),
('路', 'ロ', NULL, '로(路), 길', 'road, path', 13, 'N3', '[{"word":"道路","reading":"どうろ","meaning":"도로"},{"word":"路線","reading":"ろせん","meaning":"노선"}]'::jsonb, 292),
('労', 'ロウ', NULL, '로(労), 수고하다', 'labor, effort', 7, 'N3', '[{"word":"労働","reading":"ろうどう","meaning":"노동"},{"word":"苦労","reading":"くろう","meaning":"고생"}]'::jsonb, 293),
('論', 'ロン', NULL, '론(論), 논하다', 'theory, discuss', 15, 'N3', '[{"word":"理論","reading":"りろん","meaning":"이론"},{"word":"論文","reading":"ろんぶん","meaning":"논문"}]'::jsonb, 294),
('湾', 'ワン', NULL, '만(湾), 만', 'bay, gulf', 12, 'N3', '[{"word":"湾","reading":"わん","meaning":"만"},{"word":"台湾","reading":"たいわん","meaning":"대만"}]'::jsonb, 295),
('腕', 'ワン', 'うで', '완(腕), 팔', 'arm', 12, 'N3', '[{"word":"腕","reading":"うで","meaning":"팔"},{"word":"腕前","reading":"うでまえ","meaning":"솜씨"}]'::jsonb, 296);
