-- JLPT N2 漢字 シードデータ
DELETE FROM jlpt_kanji WHERE jlpt_level = 'N2';

INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('圧', 'アツ', 'お.す', '압(圧), 누르다', 'pressure', 5, 'N2', '[{"word":"圧力","reading":"あつりょく","meaning":"압력"},{"word":"気圧","reading":"きあつ","meaning":"기압"}]'::jsonb, 1),
('扱', 'ソウ', 'あつか.う', '급(扱), 다루다', 'handle, treat', 6, 'N2', '[{"word":"扱う","reading":"あつかう","meaning":"다루다"},{"word":"取扱","reading":"とりあつかい","meaning":"취급"}]'::jsonb, 2),
('宛', 'エン', 'あ.てる、あて', '완(宛), ~앞으로', 'address, just like', 8, 'N2', '[{"word":"宛先","reading":"あてさき","meaning":"수신처"},{"word":"宛てる","reading":"あてる","meaning":"보내다"}]'::jsonb, 3),
('嵐', NULL, 'あらし', '람(嵐), 폭풍', 'storm, tempest', 12, 'N2', '[{"word":"嵐","reading":"あらし","meaning":"폭풍"},{"word":"砂嵐","reading":"すなあらし","meaning":"모래폭풍"}]'::jsonb, 4),
('依', 'イ、エ', NULL, '의(依), 의지하다', 'reliant, depend on', 8, 'N2', '[{"word":"依頼","reading":"いらい","meaning":"의뢰"},{"word":"依存","reading":"いぞん","meaning":"의존"}]'::jsonb, 5),
('威', 'イ', NULL, '위(威), 위엄', 'intimidate, dignity', 9, 'N2', '[{"word":"威力","reading":"いりょく","meaning":"위력"},{"word":"脅威","reading":"きょうい","meaning":"위협"}]'::jsonb, 6),
('為', 'イ', 'ため、な.す', '위(為), 하다, 위하다', 'do, for the sake of', 9, 'N2', '[{"word":"為替","reading":"かわせ","meaning":"환전"},{"word":"行為","reading":"こうい","meaning":"행위"}]'::jsonb, 7),
('維', 'イ', NULL, '유(維), 벼리', 'maintain, fiber', 14, 'N2', '[{"word":"維持","reading":"いじ","meaning":"유지"},{"word":"繊維","reading":"せんい","meaning":"섬유"}]'::jsonb, 8),
('違', 'イ', 'ちが.う、ちが.える', '위(違), 다르다', 'differ, wrong', 13, 'N2', '[{"word":"違う","reading":"ちがう","meaning":"다르다"},{"word":"違反","reading":"いはん","meaning":"위반"}]'::jsonb, 9),
('域', 'イキ', NULL, '역(域), 지역', 'range, region', 11, 'N2', '[{"word":"地域","reading":"ちいき","meaning":"지역"},{"word":"領域","reading":"りょういき","meaning":"영역"}]'::jsonb, 10),
('壱', 'イチ', NULL, '일(壱), 하나', 'one (formal)', 7, 'N2', '[{"word":"壱万円","reading":"いちまんえん","meaning":"만 엔"},{"word":"壱番","reading":"いちばん","meaning":"일번"}]'::jsonb, 11),
('逸', 'イツ', 'そ.れる、そ.らす', '일(逸), 벗어나다', 'deviate, excel', 11, 'N2', '[{"word":"逸話","reading":"いつわ","meaning":"일화"},{"word":"逸脱","reading":"いつだつ","meaning":"일탈"}]'::jsonb, 12),
('稲', 'トウ', 'いね、いな', '도(稲), 벼', 'rice plant', 14, 'N2', '[{"word":"稲","reading":"いね","meaning":"벼"},{"word":"稲作","reading":"いなさく","meaning":"벼농사"}]'::jsonb, 13),
('芋', 'ウ', 'いも', '우(芋), 감자, 토란', 'potato, taro', 6, 'N2', '[{"word":"芋","reading":"いも","meaning":"감자"},{"word":"焼き芋","reading":"やきいも","meaning":"군고구마"}]'::jsonb, 14),
('姻', 'イン', NULL, '인(姻), 혼인', 'marriage', 9, 'N2', '[{"word":"婚姻","reading":"こんいん","meaning":"혼인"},{"word":"姻戚","reading":"いんせき","meaning":"인척"}]'::jsonb, 15),
('陰', 'イン', 'かげ、かげ.る', '음(陰), 그늘', 'shade, negative', 11, 'N2', '[{"word":"陰","reading":"かげ","meaning":"그늘"},{"word":"陰気","reading":"いんき","meaning":"음침함"}]'::jsonb, 16),
('隠', 'イン、オン', 'かく.す、かく.れる', '은(隠), 숨기다', 'hide, conceal', 14, 'N2', '[{"word":"隠す","reading":"かくす","meaning":"숨기다"},{"word":"隠居","reading":"いんきょ","meaning":"은거"}]'::jsonb, 17),
('影', 'エイ', 'かげ', '영(影), 그림자', 'shadow, influence', 15, 'N2', '[{"word":"影響","reading":"えいきょう","meaning":"영향"},{"word":"影","reading":"かげ","meaning":"그림자"}]'::jsonb, 18),
('鋭', 'エイ', 'するど.い', '예(鋭), 날카롭다', 'sharp, pointed', 15, 'N2', '[{"word":"鋭い","reading":"するどい","meaning":"날카롭다"},{"word":"鋭角","reading":"えいかく","meaning":"예각"}]'::jsonb, 19),
('越', 'エツ', 'こ.す、こ.える', '월(越), 넘다', 'surpass, cross over', 12, 'N2', '[{"word":"越える","reading":"こえる","meaning":"넘다"},{"word":"超越","reading":"ちょうえつ","meaning":"초월"}]'::jsonb, 20),
('援', 'エン', NULL, '원(援), 돕다', 'aid, support', 12, 'N2', '[{"word":"援助","reading":"えんじょ","meaning":"원조"},{"word":"支援","reading":"しえん","meaning":"지원"}]'::jsonb, 22),
('汚', 'オ', 'よご.す、よご.れる、きたな.い', '오(汚), 더럽다', 'dirty, pollute', 6, 'N2', '[{"word":"汚い","reading":"きたない","meaning":"더럽다"},{"word":"汚染","reading":"おせん","meaning":"오염"}]'::jsonb, 22),
('奥', 'オウ', 'おく', '오(奥), 안쪽', 'interior, depths', 12, 'N2', '[{"word":"奥","reading":"おく","meaning":"안쪽"},{"word":"奥さん","reading":"おくさん","meaning":"부인"}]'::jsonb, 25),
('翁', 'オウ', 'おきな', '옹(翁), 늙은이', 'old man, venerable', 10, 'N2', '[{"word":"翁","reading":"おきな","meaning":"노인"},{"word":"老翁","reading":"ろうおう","meaning":"노옹"}]'::jsonb, 26),
('沖', 'チュウ', 'おき', '충(沖), 바다 한가운데', 'open sea, offshore', 7, 'N2', '[{"word":"沖","reading":"おき","meaning":"앞바다"},{"word":"沖縄","reading":"おきなわ","meaning":"오키나와"}]'::jsonb, 27),
('憶', 'オク', NULL, '억(憶), 기억하다', 'remember, recollect', 16, 'N2', '[{"word":"記憶","reading":"きおく","meaning":"기억"},{"word":"追憶","reading":"ついおく","meaning":"추억"}]'::jsonb, 28),
('乙', 'オツ', NULL, '을(乙), 둘째', 'second, stylish', 1, 'N2', '[{"word":"乙","reading":"おつ","meaning":"을"},{"word":"甲乙","reading":"こうおつ","meaning":"갑을"}]'::jsonb, 29),
('卸', 'シャ', 'おろ.す、おろし', '사(卸), 도매', 'wholesale', 9, 'N2', '[{"word":"卸売","reading":"おろしうり","meaning":"도매"},{"word":"卸す","reading":"おろす","meaning":"도매하다"}]'::jsonb, 30),
('穏', 'オン', 'おだ.やか', '온(穏), 온화하다', 'calm, quiet', 16, 'N2', '[{"word":"穏やか","reading":"おだやか","meaning":"온화하다"},{"word":"温穏","reading":"おんおん","meaning":"온화함"}]'::jsonb, 31),
('佳', 'カ', NULL, '가(佳), 아름답다', 'beautiful, excellent', 8, 'N2', '[{"word":"佳作","reading":"かさく","meaning":"가작"},{"word":"佳人","reading":"かじん","meaning":"미인"}]'::jsonb, 32),
('架', 'カ', 'か.ける、か.かる', '가(架), 걸다', 'erect, build, shelf', 9, 'N2', '[{"word":"架空","reading":"かくう","meaning":"가공"},{"word":"書架","reading":"しょか","meaning":"서가"}]'::jsonb, 33),
('華', 'カ、ケ', 'はな', '화(華), 빛나다, 꽃', 'splendor, flower', 10, 'N2', '[{"word":"華やか","reading":"はなやか","meaning":"화려하다"},{"word":"中華","reading":"ちゅうか","meaning":"중화"}]'::jsonb, 34),
('菓', 'カ', NULL, '과(菓), 과자', 'candy, confection', 11, 'N2', '[{"word":"菓子","reading":"かし","meaning":"과자"},{"word":"和菓子","reading":"わがし","meaning":"화과자"}]'::jsonb, 35),
('雅', 'ガ', 'みやび', '아(雅), 우아하다', 'graceful, elegant', 13, 'N2', '[{"word":"雅","reading":"みやび","meaning":"우아함"},{"word":"優雅","reading":"ゆうが","meaning":"우아"}]'::jsonb, 36),
('介', 'カイ', NULL, '개(介), 끼다', 'mediate, shellfish', 4, 'N2', '[{"word":"紹介","reading":"しょうかい","meaning":"소개"},{"word":"介護","reading":"かいご","meaning":"간호"}]'::jsonb, 37),
('塊', 'カイ', 'かたまり', '괴(塊), 덩어리', 'lump, clod', 13, 'N2', '[{"word":"塊","reading":"かたまり","meaning":"덩어리"},{"word":"金塊","reading":"きんかい","meaning":"금괴"}]'::jsonb, 38),
('悔', 'カイ', 'く.いる、く.やむ、くや.しい', '회(悔), 뉘우치다', 'repent, regret', 9, 'N2', '[{"word":"後悔","reading":"こうかい","meaning":"후회"},{"word":"悔しい","reading":"くやしい","meaning":"분하다"}]'::jsonb, 39),
('慨', 'ガイ', NULL, '개(慨), 분개하다', 'rue, lament', 13, 'N2', '[{"word":"感慨","reading":"かんがい","meaning":"감개"},{"word":"憤慨","reading":"ふんがい","meaning":"분개"}]'::jsonb, 40),
('概', 'ガイ', 'おおむ.ね', '개(概), 대개', 'outline, approximate', 14, 'N2', '[{"word":"概要","reading":"がいよう","meaning":"개요"},{"word":"概念","reading":"がいねん","meaning":"개념"}]'::jsonb, 41),
('該', 'ガイ', NULL, '해(該), 해당하다', 'applicable, correspond', 13, 'N2', '[{"word":"該当","reading":"がいとう","meaning":"해당"},{"word":"当該","reading":"とうがい","meaning":"당해"}]'::jsonb, 42),
('拡', 'カク', 'ひろ.がる、ひろ.げる', '확(拡), 넓히다', 'expand, spread', 8, 'N2', '[{"word":"拡大","reading":"かくだい","meaning":"확대"},{"word":"拡張","reading":"かくちょう","meaning":"확장"}]'::jsonb, 43),
('閣', 'カク', NULL, '각(閣), 누각', 'cabinet, tower', 14, 'N2', '[{"word":"内閣","reading":"ないかく","meaning":"내각"},{"word":"閣僚","reading":"かくりょう","meaning":"각료"}]'::jsonb, 44),
('革', 'カク', 'かわ', '혁(革), 가죽, 고치다', 'leather, reform', 9, 'N2', '[{"word":"革命","reading":"かくめい","meaning":"혁명"},{"word":"改革","reading":"かいかく","meaning":"개혁"}]'::jsonb, 45),
('獲', 'カク', 'え.る', '획(獲), 얻다', 'seize, catch', 16, 'N2', '[{"word":"獲得","reading":"かくとく","meaning":"획득"},{"word":"捕獲","reading":"ほかく","meaning":"포획"}]'::jsonb, 46),
('嚇', 'カク', 'おど.す', '혁(嚇), 위협하다', 'threaten, menace', 17, 'N2', '[{"word":"威嚇","reading":"いかく","meaning":"위협"},{"word":"脅嚇","reading":"きょうかく","meaning":"협박"}]'::jsonb, 47),
('滑', 'カツ', 'すべ.る、なめ.らか', '활(滑), 미끄럽다', 'slippery, smooth', 13, 'N2', '[{"word":"滑る","reading":"すべる","meaning":"미끄러지다"},{"word":"滑走","reading":"かっそう","meaning":"활주"}]'::jsonb, 48),
('轄', 'カツ', NULL, '할(轄), 관할하다', 'control, jurisdiction', 17, 'N2', '[{"word":"管轄","reading":"かんかつ","meaning":"관할"},{"word":"直轄","reading":"ちょっかつ","meaning":"직할"}]'::jsonb, 49),
('且', 'ショ', 'か.つ', '차(且), 또', 'moreover, also', 5, 'N2', '[{"word":"且つ","reading":"かつ","meaning":"또한"},{"word":"尚且つ","reading":"なおかつ","meaning":"게다가"}]'::jsonb, 50),
('株', 'シュ', 'かぶ', '주(株), 그루, 주식', 'stock, share', 10, 'N2', '[{"word":"株式","reading":"かぶしき","meaning":"주식"},{"word":"株","reading":"かぶ","meaning":"주식"}]'::jsonb, 51),
('刈', 'ガイ', 'か.る', '예(刈), 베다', 'reap, cut', 4, 'N2', '[{"word":"刈る","reading":"かる","meaning":"베다"},{"word":"草刈り","reading":"くさかり","meaning":"풀베기"}]'::jsonb, 52),
('乾', 'カン、ケン', 'かわ.く、かわ.かす', '건(乾), 마르다', 'dry', 11, 'N2', '[{"word":"乾く","reading":"かわく","meaning":"마르다"},{"word":"乾燥","reading":"かんそう","meaning":"건조"}]'::jsonb, 53),
('冠', 'カン', 'かんむり', '관(冠), 갓', 'crown, best', 9, 'N2', '[{"word":"王冠","reading":"おうかん","meaning":"왕관"},{"word":"冠","reading":"かんむり","meaning":"관"}]'::jsonb, 54),
('勘', 'カン', NULL, '감(勘), 직감', 'intuition, sixth sense', 11, 'N2', '[{"word":"勘","reading":"かん","meaning":"직감"},{"word":"勘違い","reading":"かんちがい","meaning":"착각"}]'::jsonb, 55),
('勧', 'カン', 'すす.める', '권(勧), 권하다', 'recommend, advise', 13, 'N2', '[{"word":"勧める","reading":"すすめる","meaning":"권하다"},{"word":"勧告","reading":"かんこく","meaning":"권고"}]'::jsonb, 56),
('喚', 'カン', 'わめ.く', '환(喚), 부르짖다', 'yell, call out', 12, 'N2', '[{"word":"召喚","reading":"しょうかん","meaning":"소환"},{"word":"喚起","reading":"かんき","meaning":"환기"}]'::jsonb, 57),
('堪', 'カン、タン', 'た.える、たま.らない', '감(堪), 견디다', 'endure, withstand', 12, 'N2', '[{"word":"堪える","reading":"たえる","meaning":"견디다"},{"word":"堪能","reading":"たんのう","meaning":"능숙함"}]'::jsonb, 58),
('寛', 'カン', 'くつろ.ぐ', '관(寛), 너그럽다', 'tolerant, lenient', 13, 'N2', '[{"word":"寛大","reading":"かんだい","meaning":"관대"},{"word":"寛容","reading":"かんよう","meaning":"관용"}]'::jsonb, 59),
('幹', 'カン', 'みき', '간(幹), 줄기', 'trunk, main part', 13, 'N2', '[{"word":"幹部","reading":"かんぶ","meaning":"간부"},{"word":"幹線","reading":"かんせん","meaning":"간선"}]'::jsonb, 60),
('患', 'カン', 'わずら.う', '환(患), 앓다', 'afflicted, ill', 11, 'N2', '[{"word":"患者","reading":"かんじゃ","meaning":"환자"},{"word":"患う","reading":"わずらう","meaning":"앓다"}]'::jsonb, 61),
('換', 'カン', 'か.える、か.わる', '환(換), 바꾸다', 'exchange, replace', 12, 'N2', '[{"word":"交換","reading":"こうかん","meaning":"교환"},{"word":"換気","reading":"かんき","meaning":"환기"}]'::jsonb, 62),
('敢', 'カン', 'あ.えて', '감(敢), 감히', 'daring, brave', 12, 'N2', '[{"word":"勇敢","reading":"ゆうかん","meaning":"용감"},{"word":"敢えて","reading":"あえて","meaning":"감히"}]'::jsonb, 63),
('棺', 'カン', NULL, '관(棺), 관', 'coffin, casket', 12, 'N2', '[{"word":"棺","reading":"ひつぎ","meaning":"관"},{"word":"棺桶","reading":"かんおけ","meaning":"관"}]'::jsonb, 64),
('款', 'カン', NULL, '관(款), 조항', 'article, goodwill', 12, 'N2', '[{"word":"定款","reading":"ていかん","meaning":"정관"},{"word":"借款","reading":"しゃっかん","meaning":"차관"}]'::jsonb, 65),
('環', 'カン', 'わ', '환(環), 고리', 'ring, circle, loop', 17, 'N2', '[{"word":"環境","reading":"かんきょう","meaning":"환경"},{"word":"循環","reading":"じゅんかん","meaning":"순환"}]'::jsonb, 66),
('監', 'カン', NULL, '감(監), 감독하다', 'oversee, supervise', 15, 'N2', '[{"word":"監督","reading":"かんとく","meaning":"감독"},{"word":"監視","reading":"かんし","meaning":"감시"}]'::jsonb, 67),
('緩', 'カン', 'ゆる.い、ゆる.やか', '완(緩), 느슨하다', 'loose, slow', 15, 'N2', '[{"word":"緩い","reading":"ゆるい","meaning":"느슨하다"},{"word":"緩和","reading":"かんわ","meaning":"완화"}]'::jsonb, 68),
('缶', 'カン', NULL, '관(缶), 깡통', 'can, tin', 6, 'N2', '[{"word":"缶","reading":"かん","meaning":"깡통"},{"word":"缶詰","reading":"かんづめ","meaning":"통조림"}]'::jsonb, 69),
('肝', 'カン', 'きも', '간(肝), 간', 'liver, vital', 7, 'N2', '[{"word":"肝臓","reading":"かんぞう","meaning":"간장"},{"word":"肝心","reading":"かんじん","meaning":"중요한"}]'::jsonb, 70),
('艦', 'カン', NULL, '함(艦), 군함', 'warship', 21, 'N2', '[{"word":"軍艦","reading":"ぐんかん","meaning":"군함"},{"word":"艦隊","reading":"かんたい","meaning":"함대"}]'::jsonb, 71),
('鑑', 'カン', 'かんが.みる', '감(鑑), 거울, 감별하다', 'appraise, model', 23, 'N2', '[{"word":"鑑定","reading":"かんてい","meaning":"감정"},{"word":"年鑑","reading":"ねんかん","meaning":"연감"}]'::jsonb, 72),
('含', 'ガン', 'ふく.む、ふく.める', '함(含), 포함하다', 'include, contain', 7, 'N2', '[{"word":"含む","reading":"ふくむ","meaning":"포함하다"},{"word":"含有","reading":"がんゆう","meaning":"함유"}]'::jsonb, 73),
('頑', 'ガン', 'かたく.な', '완(頑), 완고하다', 'stubborn, firm', 13, 'N2', '[{"word":"頑張る","reading":"がんばる","meaning":"힘내다"},{"word":"頑固","reading":"がんこ","meaning":"완고"}]'::jsonb, 74),
('企', 'キ', 'くわだ.てる', '기(企), 꾀하다', 'plan, undertake', 6, 'N2', '[{"word":"企業","reading":"きぎょう","meaning":"기업"},{"word":"企画","reading":"きかく","meaning":"기획"}]'::jsonb, 75),
('奇', 'キ', NULL, '기(奇), 기이하다', 'strange, curious', 8, 'N2', '[{"word":"奇妙","reading":"きみょう","meaning":"기묘"},{"word":"好奇心","reading":"こうきしん","meaning":"호기심"}]'::jsonb, 76),
('岐', 'キ', NULL, '기(岐), 갈래', 'branch, fork', 7, 'N2', '[{"word":"岐路","reading":"きろ","meaning":"기로"},{"word":"分岐","reading":"ぶんき","meaning":"분기"}]'::jsonb, 77),
('幾', 'キ', 'いく', '기(幾), 몇', 'how many, some', 12, 'N2', '[{"word":"幾つ","reading":"いくつ","meaning":"몇 개"},{"word":"幾何学","reading":"きかがく","meaning":"기하학"}]'::jsonb, 78),
('忌', 'キ', 'い.む、い.まわしい', '기(忌), 꺼리다', 'mourning, abhor', 7, 'N2', '[{"word":"忌避","reading":"きひ","meaning":"기피"},{"word":"忌む","reading":"いむ","meaning":"꺼리다"}]'::jsonb, 79),
('既', 'キ', 'すで.に', '기(既), 이미', 'already, previously', 9, 'N2', '[{"word":"既に","reading":"すでに","meaning":"이미"},{"word":"既存","reading":"きそん","meaning":"기존"}]'::jsonb, 80),
('棄', 'キ', NULL, '기(棄), 버리다', 'abandon, discard', 12, 'N2', '[{"word":"放棄","reading":"ほうき","meaning":"포기"},{"word":"廃棄","reading":"はいき","meaning":"폐기"}]'::jsonb, 81),
('棋', 'キ', NULL, '기(棋), 바둑', 'chess, shogi', 12, 'N2', '[{"word":"将棋","reading":"しょうぎ","meaning":"장기"},{"word":"棋士","reading":"きし","meaning":"기사"}]'::jsonb, 82),
('祈', 'キ', 'いの.る', '기(祈), 빌다', 'pray, wish', 8, 'N2', '[{"word":"祈る","reading":"いのる","meaning":"빌다"},{"word":"祈願","reading":"きがん","meaning":"기원"}]'::jsonb, 83),
('輝', 'キ', 'かがや.く', '휘(輝), 빛나다', 'radiance, shine', 15, 'N2', '[{"word":"輝く","reading":"かがやく","meaning":"빛나다"},{"word":"光輝","reading":"こうき","meaning":"광휘"}]'::jsonb, 84),
('飢', 'キ', 'う.える', '기(飢), 굶주리다', 'hungry, starve', 10, 'N2', '[{"word":"飢える","reading":"うえる","meaning":"굶주리다"},{"word":"飢餓","reading":"きが","meaning":"기아"}]'::jsonb, 85),
('鬼', 'キ', 'おに', '귀(鬼), 귀신', 'ghost, demon', 10, 'N2', '[{"word":"鬼","reading":"おに","meaning":"도깨비"},{"word":"鬼才","reading":"きさい","meaning":"귀재"}]'::jsonb, 86),
('偽', 'ギ', 'いつわ.る、にせ', '위(偽), 거짓', 'falsify, fake', 11, 'N2', '[{"word":"偽物","reading":"にせもの","meaning":"가짜"},{"word":"偽造","reading":"ぎぞう","meaning":"위조"}]'::jsonb, 87),
('儀', 'ギ', NULL, '의(儀), 의식', 'ceremony, affair', 15, 'N2', '[{"word":"儀式","reading":"ぎしき","meaning":"의식"},{"word":"礼儀","reading":"れいぎ","meaning":"예의"}]'::jsonb, 88),
('宜', 'ギ', 'よろ.しい', '의(宜), 마땅하다', 'suitable, best regards', 8, 'N2', '[{"word":"便宜","reading":"べんぎ","meaning":"편의"},{"word":"適宜","reading":"てきぎ","meaning":"적절히"}]'::jsonb, 89),
('戯', 'ギ、ゲ', 'たわむ.れる', '희(戯), 장난치다', 'play, frolic', 15, 'N2', '[{"word":"遊戯","reading":"ゆうぎ","meaning":"유희"},{"word":"戯れる","reading":"たわむれる","meaning":"장난치다"}]'::jsonb, 90),
('擬', 'ギ', 'まが.い、もど.き', '의(擬), 흉내내다', 'mimic, imitate', 17, 'N2', '[{"word":"擬似","reading":"ぎじ","meaning":"유사"},{"word":"模擬","reading":"もぎ","meaning":"모의"}]'::jsonb, 91),
('犠', 'ギ', NULL, '희(犠), 희생', 'sacrifice, victim', 17, 'N2', '[{"word":"犠牲","reading":"ぎせい","meaning":"희생"},{"word":"犠牲者","reading":"ぎせいしゃ","meaning":"희생자"}]'::jsonb, 92),
('菊', 'キク', NULL, '국(菊), 국화', 'chrysanthemum', 11, 'N2', '[{"word":"菊","reading":"きく","meaning":"국화"},{"word":"菊花","reading":"きっか","meaning":"국화꽃"}]'::jsonb, 93),
('吉', 'キチ、キツ', NULL, '길(吉), 길하다', 'good luck, auspicious', 6, 'N2', '[{"word":"吉日","reading":"きちじつ","meaning":"길일"},{"word":"不吉","reading":"ふきつ","meaning":"불길"}]'::jsonb, 94),
('喫', 'キツ', NULL, '끽(喫), 마시다', 'eat, drink, smoke', 12, 'N2', '[{"word":"喫茶店","reading":"きっさてん","meaning":"다방"},{"word":"喫煙","reading":"きつえん","meaning":"흡연"}]'::jsonb, 95),
('詰', 'キツ', 'つ.める、つ.まる', '힐(詰), 채우다', 'pack, cram', 13, 'N2', '[{"word":"詰める","reading":"つめる","meaning":"채우다"},{"word":"詰問","reading":"きつもん","meaning":"힐문"}]'::jsonb, 96),
('虐', 'ギャク', 'しいた.げる', '학(虐), 학대하다', 'oppress, tyrannize', 9, 'N2', '[{"word":"虐待","reading":"ぎゃくたい","meaning":"학대"},{"word":"残虐","reading":"ざんぎゃく","meaning":"잔학"}]'::jsonb, 97),
('丘', 'キュウ', 'おか', '구(丘), 언덕', 'hill, mound', 5, 'N2', '[{"word":"丘","reading":"おか","meaning":"언덕"},{"word":"砂丘","reading":"さきゅう","meaning":"사구"}]'::jsonb, 98),
('及', 'キュウ', 'およ.ぶ、およ.び', '급(及), 미치다', 'reach, and', 3, 'N2', '[{"word":"及ぶ","reading":"およぶ","meaning":"미치다"},{"word":"及び","reading":"および","meaning":"및"}]'::jsonb, 99),
('朽', 'キュウ', 'く.ちる', '후(朽), 썩다', 'decay, rot', 6, 'N2', '[{"word":"朽ちる","reading":"くちる","meaning":"썩다"},{"word":"不朽","reading":"ふきゅう","meaning":"불후"}]'::jsonb, 100),
('窮', 'キュウ', 'きわ.める、きわ.まる', '궁(窮), 궁하다', 'distress, cornered', 15, 'N2', '[{"word":"窮地","reading":"きゅうち","meaning":"궁지"},{"word":"困窮","reading":"こんきゅう","meaning":"곤궁"}]'::jsonb, 101),
('糾', 'キュウ', NULL, '규(糾), 규명하다', 'investigate, twist', 9, 'N2', '[{"word":"糾弾","reading":"きゅうだん","meaning":"규탄"},{"word":"糾明","reading":"きゅうめい","meaning":"규명"}]'::jsonb, 102),
('拠', 'キョ、コ', 'よ.る', '거(拠), 근거', 'base, evidence', 8, 'N2', '[{"word":"根拠","reading":"こんきょ","meaning":"근거"},{"word":"拠点","reading":"きょてん","meaning":"거점"}]'::jsonb, 103),
('虚', 'キョ、コ', 'むな.しい', '허(虚), 허무하다', 'empty, void', 11, 'N2', '[{"word":"虚偽","reading":"きょぎ","meaning":"허위"},{"word":"虚無","reading":"きょむ","meaning":"허무"}]'::jsonb, 104),
('距', 'キョ', NULL, '거(距), 거리', 'distance, gap', 11, 'N2', '[{"word":"距離","reading":"きょり","meaning":"거리"},{"word":"長距離","reading":"ちょうきょり","meaning":"장거리"}]'::jsonb, 105),
('享', 'キョウ', 'う.ける', '향(享), 누리다', 'enjoy, receive', 8, 'N2', '[{"word":"享受","reading":"きょうじゅ","meaning":"향수"},{"word":"享楽","reading":"きょうらく","meaning":"향락"}]'::jsonb, 106),
('凶', 'キョウ', NULL, '흉(凶), 흉하다', 'villain, disaster', 4, 'N2', '[{"word":"凶悪","reading":"きょうあく","meaning":"흉악"},{"word":"凶器","reading":"きょうき","meaning":"흉기"}]'::jsonb, 107),
('叫', 'キョウ', 'さけ.ぶ', '규(叫), 외치다', 'shout, cry', 6, 'N2', '[{"word":"叫ぶ","reading":"さけぶ","meaning":"외치다"},{"word":"絶叫","reading":"ぜっきょう","meaning":"절규"}]'::jsonb, 108),
('峡', 'キョウ', NULL, '협(峡), 골짜기', 'gorge, ravine', 9, 'N2', '[{"word":"海峡","reading":"かいきょう","meaning":"해협"},{"word":"峡谷","reading":"きょうこく","meaning":"협곡"}]'::jsonb, 109),
('恐', 'キョウ', 'おそ.れる、おそ.ろしい', '공(恐), 두렵다', 'fear, dread', 10, 'N2', '[{"word":"恐れる","reading":"おそれる","meaning":"두려워하다"},{"word":"恐怖","reading":"きょうふ","meaning":"공포"}]'::jsonb, 110),
('恭', 'キョウ', 'うやうや.しい', '공(恭), 공손하다', 'respectful, reverent', 10, 'N2', '[{"word":"恭しい","reading":"うやうやしい","meaning":"공손하다"},{"word":"恭順","reading":"きょうじゅん","meaning":"공순"}]'::jsonb, 111),
('挟', 'キョウ', 'はさ.む、はさ.まる', '협(挟), 끼다', 'pinch, between', 9, 'N2', '[{"word":"挟む","reading":"はさむ","meaning":"끼다"},{"word":"板挟み","reading":"いたばさみ","meaning":"진퇴양난"}]'::jsonb, 112),
('脅', 'キョウ', 'おびや.かす、おど.す', '협(脅), 위협하다', 'threaten, coerce', 10, 'N2', '[{"word":"脅威","reading":"きょうい","meaning":"위협"},{"word":"脅迫","reading":"きょうはく","meaning":"협박"}]'::jsonb, 113),
('狂', 'キョウ', 'くる.う、くる.おしい', '광(狂), 미치다', 'crazy, mad', 7, 'N2', '[{"word":"狂う","reading":"くるう","meaning":"미치다"},{"word":"熱狂","reading":"ねっきょう","meaning":"열광"}]'::jsonb, 114),
('狭', 'キョウ', 'せま.い、せば.める', '협(狭), 좁다', 'narrow, cramped', 9, 'N2', '[{"word":"狭い","reading":"せまい","meaning":"좁다"},{"word":"狭量","reading":"きょうりょう","meaning":"도량이 좁음"}]'::jsonb, 115),
('矯', 'キョウ', 'た.める', '교(矯), 바로잡다', 'rectify, straighten', 17, 'N2', '[{"word":"矯正","reading":"きょうせい","meaning":"교정"},{"word":"矯正歯科","reading":"きょうせいしか","meaning":"교정치과"}]'::jsonb, 116),
('響', 'キョウ', 'ひび.く', '향(響), 울리다', 'echo, resound', 20, 'N2', '[{"word":"影響","reading":"えいきょう","meaning":"영향"},{"word":"響く","reading":"ひびく","meaning":"울리다"}]'::jsonb, 117),
('驚', 'キョウ', 'おどろ.く、おどろ.かす', '경(驚), 놀라다', 'surprise, be amazed', 22, 'N2', '[{"word":"驚く","reading":"おどろく","meaning":"놀라다"},{"word":"驚異","reading":"きょうい","meaning":"경이"}]'::jsonb, 118),
('仰', 'ギョウ、コウ', 'あお.ぐ、おお.せ', '앙(仰), 우러르다', 'look up, respect', 6, 'N2', '[{"word":"仰ぐ","reading":"あおぐ","meaning":"우러르다"},{"word":"信仰","reading":"しんこう","meaning":"신앙"}]'::jsonb, 119),
('凝', 'ギョウ', 'こ.る、こ.らす', '응(凝), 엉기다', 'congeal, concentrate', 16, 'N2', '[{"word":"凝る","reading":"こる","meaning":"몰두하다"},{"word":"凝固","reading":"ぎょうこ","meaning":"응고"}]'::jsonb, 120),
('暁', 'ギョウ', 'あかつき', '효(暁), 새벽', 'dawn, daybreak', 12, 'N2', '[{"word":"暁","reading":"あかつき","meaning":"새벽"},{"word":"今暁","reading":"こんぎょう","meaning":"오늘 새벽"}]'::jsonb, 121),
('斤', 'キン', NULL, '근(斤), 근', 'axe, unit of weight', 4, 'N2', '[{"word":"一斤","reading":"いっきん","meaning":"한 근"},{"word":"斤量","reading":"きんりょう","meaning":"근량"}]'::jsonb, 122),
('菌', 'キン', NULL, '균(菌), 균', 'germ, bacteria', 11, 'N2', '[{"word":"細菌","reading":"さいきん","meaning":"세균"},{"word":"殺菌","reading":"さっきん","meaning":"살균"}]'::jsonb, 123),
('僅', 'キン', 'わず.か', '근(僅), 겨우', 'merely, only', 13, 'N2', '[{"word":"僅か","reading":"わずか","meaning":"겨우"},{"word":"僅差","reading":"きんさ","meaning":"근소한 차이"}]'::jsonb, 124),
('緊', 'キン', NULL, '긴(緊), 긴박하다', 'tense, tight', 15, 'N2', '[{"word":"緊張","reading":"きんちょう","meaning":"긴장"},{"word":"緊急","reading":"きんきゅう","meaning":"긴급"}]'::jsonb, 125),
('愚', 'グ', 'おろ.か', '우(愚), 어리석다', 'foolish, stupid', 13, 'N2', '[{"word":"愚か","reading":"おろか","meaning":"어리석다"},{"word":"愚痴","reading":"ぐち","meaning":"불평"}]'::jsonb, 126),
('偶', 'グウ', 'たま', '우(偶), 우연', 'accidentally, even number', 11, 'N2', '[{"word":"偶然","reading":"ぐうぜん","meaning":"우연"},{"word":"偶数","reading":"ぐうすう","meaning":"짝수"}]'::jsonb, 127),
('遇', 'グウ', 'あ.う', '우(遇), 만나다', 'meet, treat', 12, 'N2', '[{"word":"待遇","reading":"たいぐう","meaning":"대우"},{"word":"遭遇","reading":"そうぐう","meaning":"조우"}]'::jsonb, 128),
('隅', 'グウ', 'すみ', '우(隅), 구석', 'corner, nook', 12, 'N2', '[{"word":"隅","reading":"すみ","meaning":"구석"},{"word":"片隅","reading":"かたすみ","meaning":"한구석"}]'::jsonb, 129),
('屈', 'クツ', 'かが.む', '굴(屈), 굽히다', 'bend, submit', 8, 'N2', '[{"word":"屈辱","reading":"くつじょく","meaning":"굴욕"},{"word":"退屈","reading":"たいくつ","meaning":"지루함"}]'::jsonb, 130),
('掘', 'クツ', 'ほ.る', '굴(掘), 파다', 'dig, excavate', 11, 'N2', '[{"word":"掘る","reading":"ほる","meaning":"파다"},{"word":"発掘","reading":"はっくつ","meaning":"발굴"}]'::jsonb, 131),
('繰', 'ソウ', 'く.る', '조(繰), 감다', 'reel, wind', 19, 'N2', '[{"word":"繰り返す","reading":"くりかえす","meaning":"반복하다"},{"word":"繰る","reading":"くる","meaning":"감다"}]'::jsonb, 132),
('桑', 'ソウ', 'くわ', '상(桑), 뽕나무', 'mulberry', 10, 'N2', '[{"word":"桑","reading":"くわ","meaning":"뽕나무"},{"word":"桑畑","reading":"くわばたけ","meaning":"뽕밭"}]'::jsonb, 133),
('勲', 'クン', NULL, '훈(勲), 공훈', 'merit, order', 15, 'N2', '[{"word":"勲章","reading":"くんしょう","meaning":"훈장"},{"word":"殊勲","reading":"しゅくん","meaning":"수훈"}]'::jsonb, 134),
('薫', 'クン', 'かお.る', '훈(薫), 향기롭다', 'fragrant, scent', 16, 'N2', '[{"word":"薫る","reading":"かおる","meaning":"향기롭다"},{"word":"薫陶","reading":"くんとう","meaning":"훈도"}]'::jsonb, 135),
('傾', 'ケイ', 'かたむ.く、かたむ.ける', '경(傾), 기울다', 'incline, lean', 13, 'N2', '[{"word":"傾く","reading":"かたむく","meaning":"기울다"},{"word":"傾向","reading":"けいこう","meaning":"경향"}]'::jsonb, 136),
('刑', 'ケイ', NULL, '형(刑), 형벌', 'punishment, penalty', 6, 'N2', '[{"word":"刑事","reading":"けいじ","meaning":"형사"},{"word":"死刑","reading":"しけい","meaning":"사형"}]'::jsonb, 137),
('啓', 'ケイ', NULL, '계(啓), 열다', 'enlighten, open', 11, 'N2', '[{"word":"啓発","reading":"けいはつ","meaning":"계발"},{"word":"啓示","reading":"けいじ","meaning":"계시"}]'::jsonb, 138),
('契', 'ケイ', 'ちぎ.る', '계(契), 계약', 'pledge, promise', 9, 'N2', '[{"word":"契約","reading":"けいやく","meaning":"계약"},{"word":"契機","reading":"けいき","meaning":"계기"}]'::jsonb, 139),
('恵', 'ケイ、エ', 'めぐ.む', '혜(恵), 은혜', 'grace, blessing', 10, 'N2', '[{"word":"恵み","reading":"めぐみ","meaning":"은혜"},{"word":"恩恵","reading":"おんけい","meaning":"은혜"}]'::jsonb, 140),
('慶', 'ケイ', NULL, '경(慶), 경사', 'jubilee, congratulate', 15, 'N2', '[{"word":"慶応","reading":"けいおう","meaning":"게이오"},{"word":"慶祝","reading":"けいしゅく","meaning":"경축"}]'::jsonb, 141),
('憩', 'ケイ', 'いこ.い、いこ.う', '게(憩), 쉬다', 'rest, repose', 16, 'N2', '[{"word":"休憩","reading":"きゅうけい","meaning":"휴게"},{"word":"憩い","reading":"いこい","meaning":"휴식"}]'::jsonb, 142),
('掲', 'ケイ', 'かか.げる', '게(掲), 내걸다', 'put up, display', 11, 'N2', '[{"word":"掲示","reading":"けいじ","meaning":"게시"},{"word":"掲載","reading":"けいさい","meaning":"게재"}]'::jsonb, 143),
('携', 'ケイ', 'たずさ.える、たずさ.わる', '휴(携), 가지고 다니다', 'carry, portable', 13, 'N2', '[{"word":"携帯","reading":"けいたい","meaning":"휴대"},{"word":"提携","reading":"ていけい","meaning":"제휴"}]'::jsonb, 144),
('渓', 'ケイ', NULL, '계(渓), 시내', 'valley, ravine', 11, 'N2', '[{"word":"渓谷","reading":"けいこく","meaning":"계곡"},{"word":"渓流","reading":"けいりゅう","meaning":"계류"}]'::jsonb, 145),
('継', 'ケイ', 'つ.ぐ', '계(継), 잇다', 'inherit, succeed', 13, 'N2', '[{"word":"継続","reading":"けいぞく","meaning":"계속"},{"word":"相続","reading":"そうぞく","meaning":"상속"}]'::jsonb, 146),
('茎', 'ケイ', 'くき', '경(茎), 줄기', 'stem, stalk', 8, 'N2', '[{"word":"茎","reading":"くき","meaning":"줄기"},{"word":"根茎","reading":"こんけい","meaning":"근경"}]'::jsonb, 147),
('蛍', 'ケイ', 'ほたる', '형(蛍), 반딧불이', 'firefly', 11, 'N2', '[{"word":"蛍","reading":"ほたる","meaning":"반딧불이"},{"word":"蛍光","reading":"けいこう","meaning":"형광"}]'::jsonb, 148),
('鶏', 'ケイ', 'にわとり', '계(鶏), 닭', 'chicken', 19, 'N2', '[{"word":"鶏","reading":"にわとり","meaning":"닭"},{"word":"鶏肉","reading":"とりにく","meaning":"닭고기"}]'::jsonb, 149),
('迎', 'ゲイ', 'むか.える', '영(迎), 맞이하다', 'welcome, greet', 7, 'N2', '[{"word":"迎える","reading":"むかえる","meaning":"맞이하다"},{"word":"歓迎","reading":"かんげい","meaning":"환영"}]'::jsonb, 150),
('鯨', 'ゲイ', 'くじら', '경(鯨), 고래', 'whale', 19, 'N2', '[{"word":"鯨","reading":"くじら","meaning":"고래"},{"word":"捕鯨","reading":"ほげい","meaning":"포경"}]'::jsonb, 151),
('撃', 'ゲキ', 'う.つ', '격(撃), 치다', 'attack, strike', 15, 'N2', '[{"word":"攻撃","reading":"こうげき","meaning":"공격"},{"word":"撃つ","reading":"うつ","meaning":"쏘다"}]'::jsonb, 152),
('傑', 'ケツ', NULL, '걸(傑), 뛰어나다', 'outstanding, hero', 13, 'N2', '[{"word":"傑作","reading":"けっさく","meaning":"걸작"},{"word":"豪傑","reading":"ごうけつ","meaning":"호걸"}]'::jsonb, 153),
('倹', 'ケン', NULL, '검(倹), 검소하다', 'frugal, thrifty', 10, 'N2', '[{"word":"倹約","reading":"けんやく","meaning":"검약"},{"word":"勤倹","reading":"きんけん","meaning":"근검"}]'::jsonb, 154),
('兼', 'ケン', 'か.ねる', '겸(兼), 겸하다', 'combine, also serve as', 10, 'N2', '[{"word":"兼ねる","reading":"かねる","meaning":"겸하다"},{"word":"兼業","reading":"けんぎょう","meaning":"겸업"}]'::jsonb, 155),
('剣', 'ケン', 'つるぎ', '검(剣), 칼', 'sword, blade', 10, 'N2', '[{"word":"剣","reading":"つるぎ","meaning":"칼"},{"word":"剣道","reading":"けんどう","meaning":"검도"}]'::jsonb, 156),
('圏', 'ケン', NULL, '권(圏), 범위', 'sphere, range', 12, 'N2', '[{"word":"圏内","reading":"けんない","meaning":"권내"},{"word":"首都圏","reading":"しゅとけん","meaning":"수도권"}]'::jsonb, 157),
('堅', 'ケン', 'かた.い', '견(堅), 굳다', 'hard, firm', 12, 'N2', '[{"word":"堅い","reading":"かたい","meaning":"단단하다"},{"word":"堅実","reading":"けんじつ","meaning":"견실"}]'::jsonb, 158),
('嫌', 'ケン、ゲン', 'きら.う、いや', '혐(嫌), 싫어하다', 'dislike, hate', 13, 'N2', '[{"word":"嫌い","reading":"きらい","meaning":"싫어함"},{"word":"嫌疑","reading":"けんぎ","meaning":"혐의"}]'::jsonb, 159),
('懸', 'ケン、ケ', 'か.ける、か.かる', '현(懸), 걸다', 'suspend, hang', 20, 'N2', '[{"word":"懸念","reading":"けねん","meaning":"우려"},{"word":"懸命","reading":"けんめい","meaning":"필사적"}]'::jsonb, 160),
('献', 'ケン、コン', NULL, '헌(献), 바치다', 'offer, dedicate', 13, 'N2', '[{"word":"献血","reading":"けんけつ","meaning":"헌혈"},{"word":"貢献","reading":"こうけん","meaning":"공헌"}]'::jsonb, 161),
('謙', 'ケン', NULL, '겸(謙), 겸손하다', 'modest, humble', 17, 'N2', '[{"word":"謙虚","reading":"けんきょ","meaning":"겸허"},{"word":"謙遜","reading":"けんそん","meaning":"겸손"}]'::jsonb, 162),
('遣', 'ケン', 'つか.わす、つか.う', '견(遣), 보내다', 'dispatch, send', 13, 'N2', '[{"word":"派遣","reading":"はけん","meaning":"파견"},{"word":"遣う","reading":"つかう","meaning":"쓰다"}]'::jsonb, 163),
('顕', 'ケン', NULL, '현(顕), 나타나다', 'manifest, appear', 18, 'N2', '[{"word":"顕著","reading":"けんちょ","meaning":"현저"},{"word":"顕微鏡","reading":"けんびきょう","meaning":"현미경"}]'::jsonb, 164),
('幻', 'ゲン', 'まぼろし', '환(幻), 환상', 'phantom, illusion', 4, 'N2', '[{"word":"幻","reading":"まぼろし","meaning":"환상"},{"word":"幻想","reading":"げんそう","meaning":"환상"}]'::jsonb, 165),
('弦', 'ゲン', 'つる', '현(弦), 줄', 'bowstring, string', 8, 'N2', '[{"word":"弦","reading":"つる","meaning":"줄"},{"word":"弦楽","reading":"げんがく","meaning":"현악"}]'::jsonb, 166),
('玄', 'ゲン', NULL, '현(玄), 검다, 오묘하다', 'mysterious, dark', 5, 'N2', '[{"word":"玄関","reading":"げんかん","meaning":"현관"},{"word":"玄米","reading":"げんまい","meaning":"현미"}]'::jsonb, 167),
('孤', 'コ', NULL, '고(孤), 외롭다', 'orphan, alone', 8, 'N2', '[{"word":"孤独","reading":"こどく","meaning":"고독"},{"word":"孤立","reading":"こりつ","meaning":"고립"}]'::jsonb, 168),
('弧', 'コ', NULL, '호(弧), 활', 'arc, bow', 9, 'N2', '[{"word":"括弧","reading":"かっこ","meaning":"괄호"},{"word":"円弧","reading":"えんこ","meaning":"원호"}]'::jsonb, 169),
('枯', 'コ', 'か.れる、か.らす', '고(枯), 마르다', 'wither, dry up', 9, 'N2', '[{"word":"枯れる","reading":"かれる","meaning":"시들다"},{"word":"枯渇","reading":"こかつ","meaning":"고갈"}]'::jsonb, 170),
('雇', 'コ', 'やと.う', '고(雇), 고용하다', 'employ, hire', 12, 'N2', '[{"word":"雇う","reading":"やとう","meaning":"고용하다"},{"word":"雇用","reading":"こよう","meaning":"고용"}]'::jsonb, 171),
('誇', 'コ', 'ほこ.る', '과(誇), 자랑하다', 'boast, pride', 13, 'N2', '[{"word":"誇り","reading":"ほこり","meaning":"자부심"},{"word":"誇張","reading":"こちょう","meaning":"과장"}]'::jsonb, 172),
('顧', 'コ', 'かえり.みる', '고(顧), 돌아보다', 'look back, take care of', 21, 'N2', '[{"word":"顧客","reading":"こきゃく","meaning":"고객"},{"word":"回顧","reading":"かいこ","meaning":"회고"}]'::jsonb, 173),
('鼓', 'コ', 'つづみ', '고(鼓), 북', 'drum, beat', 13, 'N2', '[{"word":"太鼓","reading":"たいこ","meaning":"큰북"},{"word":"鼓舞","reading":"こぶ","meaning":"고무"}]'::jsonb, 174),
('互', 'ゴ', 'たが.い', '호(互), 서로', 'mutual, reciprocal', 4, 'N2', '[{"word":"互い","reading":"たがい","meaning":"서로"},{"word":"相互","reading":"そうご","meaning":"상호"}]'::jsonb, 175),
('呉', 'ゴ', 'く.れる', '오(呉), 주다', 'give, do for', 7, 'N2', '[{"word":"呉服","reading":"ごふく","meaning":"옷감"},{"word":"呉れる","reading":"くれる","meaning":"주다"}]'::jsonb, 176),
('娯', 'ゴ', NULL, '오(娯), 즐기다', 'recreation, amusement', 10, 'N2', '[{"word":"娯楽","reading":"ごらく","meaning":"오락"},{"word":"娯楽施設","reading":"ごらくしせつ","meaning":"오락시설"}]'::jsonb, 177),
('悟', 'ゴ', 'さと.る', '오(悟), 깨닫다', 'enlightenment, realize', 10, 'N2', '[{"word":"悟る","reading":"さとる","meaning":"깨닫다"},{"word":"覚悟","reading":"かくご","meaning":"각오"}]'::jsonb, 178),
('碁', 'ゴ', NULL, '기(碁), 바둑', 'Go (board game)', 13, 'N2', '[{"word":"碁","reading":"ご","meaning":"바둑"},{"word":"囲碁","reading":"いご","meaning":"바둑"}]'::jsonb, 179),
('侯', 'コウ', NULL, '후(侯), 제후', 'marquis, lord', 9, 'N2', '[{"word":"侯爵","reading":"こうしゃく","meaning":"후작"},{"word":"諸侯","reading":"しょこう","meaning":"제후"}]'::jsonb, 180),
('克', 'コク', NULL, '극(克), 이기다', 'overcome, subdue', 7, 'N2', '[{"word":"克服","reading":"こくふく","meaning":"극복"},{"word":"克明","reading":"こくめい","meaning":"극명"}]'::jsonb, 181),
('剛', 'ゴウ', NULL, '강(剛), 굳세다', 'strong, sturdy', 10, 'N2', '[{"word":"剛力","reading":"ごうりき","meaning":"강력"},{"word":"金剛","reading":"こんごう","meaning":"금강"}]'::jsonb, 182),
('恒', 'コウ', NULL, '항(恒), 항상', 'constant, always', 9, 'N2', '[{"word":"恒例","reading":"こうれい","meaning":"항례"},{"word":"恒常","reading":"こうじょう","meaning":"항상"}]'::jsonb, 183),
('慌', 'コウ', 'あわ.てる、あわ.ただしい', '황(慌), 당황하다', 'flustered, hurry', 12, 'N2', '[{"word":"慌てる","reading":"あわてる","meaning":"당황하다"},{"word":"大慌て","reading":"おおあわて","meaning":"허둥지둥"}]'::jsonb, 184),
('抗', 'コウ', NULL, '항(抗), 대항하다', 'resist, oppose', 7, 'N2', '[{"word":"抵抗","reading":"ていこう","meaning":"저항"},{"word":"抗議","reading":"こうぎ","meaning":"항의"}]'::jsonb, 185),
('拘', 'コウ', 'かか.わる', '구(拘), 구속하다', 'arrest, restrict', 8, 'N2', '[{"word":"拘束","reading":"こうそく","meaning":"구속"},{"word":"拘る","reading":"こだわる","meaning":"구애되다"}]'::jsonb, 186),
('控', 'コウ', 'ひか.える', '공(控), 삼가다', 'refrain, note', 11, 'N2', '[{"word":"控える","reading":"ひかえる","meaning":"삼가다"},{"word":"控除","reading":"こうじょ","meaning":"공제"}]'::jsonb, 187),
('攻', 'コウ', 'せ.める', '공(攻), 공격하다', 'attack, assault', 7, 'N2', '[{"word":"攻撃","reading":"こうげき","meaning":"공격"},{"word":"攻める","reading":"せめる","meaning":"공격하다"}]'::jsonb, 188),
('更', 'コウ', 'さら、ふ.ける', '경(更), 다시, 고치다', 'renew, again', 7, 'N2', '[{"word":"変更","reading":"へんこう","meaning":"변경"},{"word":"更に","reading":"さらに","meaning":"더욱"}]'::jsonb, 189),
('梗', 'コウ', NULL, '경(梗), 줄기', 'outline, ingestion', 11, 'N2', '[{"word":"梗概","reading":"こうがい","meaning":"줄거리"},{"word":"脳梗塞","reading":"のうこうそく","meaning":"뇌경색"}]'::jsonb, 190),
('江', 'コウ', 'え', '강(江), 큰 강', 'bay, inlet', 6, 'N2', '[{"word":"江戸","reading":"えど","meaning":"에도"},{"word":"入り江","reading":"いりえ","meaning":"만"}]'::jsonb, 191),
('硬', 'コウ', 'かた.い', '경(硬), 딱딱하다', 'hard, stiff', 12, 'N2', '[{"word":"硬い","reading":"かたい","meaning":"딱딱하다"},{"word":"硬貨","reading":"こうか","meaning":"동전"}]'::jsonb, 192),
('絞', 'コウ', 'しぼ.る、し.める', '교(絞), 짜다', 'strangle, wring', 12, 'N2', '[{"word":"絞る","reading":"しぼる","meaning":"짜다"},{"word":"絞首","reading":"こうしゅ","meaning":"교수"}]'::jsonb, 193),
('綱', 'コウ', 'つな', '강(綱), 밧줄', 'rope, outline', 14, 'N2', '[{"word":"綱","reading":"つな","meaning":"밧줄"},{"word":"横綱","reading":"よこづな","meaning":"요코즈나"}]'::jsonb, 194),
('肯', 'コウ', NULL, '긍(肯), 긍정하다', 'agreement, consent', 8, 'N2', '[{"word":"肯定","reading":"こうてい","meaning":"긍정"},{"word":"首肯","reading":"しゅこう","meaning":"수긍"}]'::jsonb, 195),
('購', 'コウ', NULL, '구(購), 사다', 'purchase, buy', 17, 'N2', '[{"word":"購入","reading":"こうにゅう","meaning":"구입"},{"word":"購買","reading":"こうばい","meaning":"구매"}]'::jsonb, 196),
('郊', 'コウ', NULL, '교(郊), 교외', 'suburb, outskirts', 9, 'N2', '[{"word":"郊外","reading":"こうがい","meaning":"교외"},{"word":"近郊","reading":"きんこう","meaning":"근교"}]'::jsonb, 197),
('酵', 'コウ', NULL, '효(酵), 발효', 'fermentation, yeast', 14, 'N2', '[{"word":"発酵","reading":"はっこう","meaning":"발효"},{"word":"酵素","reading":"こうそ","meaning":"효소"}]'::jsonb, 198),
('鋼', 'コウ', 'はがね', '강(鋼), 강철', 'steel', 16, 'N2', '[{"word":"鋼","reading":"はがね","meaning":"강철"},{"word":"鉄鋼","reading":"てっこう","meaning":"철강"}]'::jsonb, 199),
('衡', 'コウ', NULL, '형(衡), 저울', 'balance, scales', 16, 'N2', '[{"word":"均衡","reading":"きんこう","meaning":"균형"},{"word":"平衡","reading":"へいこう","meaning":"평형"}]'::jsonb, 200),
('豪', 'ゴウ', NULL, '호(豪), 호걸', 'overpowering, magnificent', 14, 'N2', '[{"word":"豪華","reading":"ごうか","meaning":"호화"},{"word":"豪雨","reading":"ごうう","meaning":"호우"}]'::jsonb, 201),
('酷', 'コク', 'ひど.い', '혹(酷), 혹독하다', 'cruel, harsh', 14, 'N2', '[{"word":"酷い","reading":"ひどい","meaning":"심하다"},{"word":"残酷","reading":"ざんこく","meaning":"잔혹"}]'::jsonb, 202),
('獄', 'ゴク', NULL, '옥(獄), 감옥', 'prison, jail', 14, 'N2', '[{"word":"監獄","reading":"かんごく","meaning":"감옥"},{"word":"地獄","reading":"じごく","meaning":"지옥"}]'::jsonb, 203),
('腰', 'ヨウ', 'こし', '요(腰), 허리', 'waist, hips', 13, 'N2', '[{"word":"腰","reading":"こし","meaning":"허리"},{"word":"腰痛","reading":"ようつう","meaning":"요통"}]'::jsonb, 204),
('込', NULL, 'こ.む、こ.める', '입(込), 들어가다', 'crowded, include', 5, 'N2', '[{"word":"込む","reading":"こむ","meaning":"붐비다"},{"word":"申し込む","reading":"もうしこむ","meaning":"신청하다"}]'::jsonb, 205),
('昆', 'コン', NULL, '곤(昆), 벌레', 'insect, descendants', 8, 'N2', '[{"word":"昆虫","reading":"こんちゅう","meaning":"곤충"},{"word":"昆布","reading":"こんぶ","meaning":"다시마"}]'::jsonb, 206),
('恨', 'コン', 'うら.む、うら.めしい', '한(恨), 한탄하다', 'resentment, grudge', 9, 'N2', '[{"word":"恨む","reading":"うらむ","meaning":"원망하다"},{"word":"恨み","reading":"うらみ","meaning":"원한"}]'::jsonb, 207),
('懇', 'コン', 'ねんご.ろ', '간(懇), 간절하다', 'earnest, friendly', 17, 'N2', '[{"word":"懇親","reading":"こんしん","meaning":"친목"},{"word":"懇談","reading":"こんだん","meaning":"간담"}]'::jsonb, 208),
('紺', 'コン', NULL, '감(紺), 감색', 'dark blue, navy', 11, 'N2', '[{"word":"紺色","reading":"こんいろ","meaning":"감색"},{"word":"紺","reading":"こん","meaning":"남색"}]'::jsonb, 209),
('魂', 'コン', 'たましい', '혼(魂), 넋', 'soul, spirit', 14, 'N2', '[{"word":"魂","reading":"たましい","meaning":"영혼"},{"word":"霊魂","reading":"れいこん","meaning":"영혼"}]'::jsonb, 210),
('佐', 'サ', NULL, '좌(佐), 돕다', 'assist, help', 7, 'N2', '[{"word":"補佐","reading":"ほさ","meaning":"보좌"},{"word":"大佐","reading":"たいさ","meaning":"대좌"}]'::jsonb, 211),
('唆', 'サ', 'そそのか.す', '사(唆), 부추기다', 'tempt, instigate', 10, 'N2', '[{"word":"唆す","reading":"そそのかす","meaning":"부추기다"},{"word":"教唆","reading":"きょうさ","meaning":"교사"}]'::jsonb, 212),
('詐', 'サ', NULL, '사(詐), 속이다', 'lie, deceive', 12, 'N2', '[{"word":"詐欺","reading":"さぎ","meaning":"사기"},{"word":"詐称","reading":"さしょう","meaning":"사칭"}]'::jsonb, 213),
('鎖', 'サ', 'くさり', '쇄(鎖), 사슬', 'chain, lock', 18, 'N2', '[{"word":"鎖","reading":"くさり","meaning":"사슬"},{"word":"閉鎖","reading":"へいさ","meaning":"폐쇄"}]'::jsonb, 214),
('債', 'サイ', NULL, '채(債), 빚', 'debt, bond', 13, 'N2', '[{"word":"債務","reading":"さいむ","meaning":"채무"},{"word":"国債","reading":"こくさい","meaning":"국채"}]'::jsonb, 215),
('催', 'サイ', 'もよお.す', '최(催), 재촉하다', 'sponsor, hold event', 13, 'N2', '[{"word":"催す","reading":"もよおす","meaning":"개최하다"},{"word":"催促","reading":"さいそく","meaning":"재촉"}]'::jsonb, 216),
('宰', 'サイ', NULL, '재(宰), 재상', 'manage, govern', 10, 'N2', '[{"word":"主宰","reading":"しゅさい","meaning":"주재"},{"word":"宰相","reading":"さいしょう","meaning":"재상"}]'::jsonb, 217),
('彩', 'サイ', 'いろど.る', '채(彩), 채색', 'coloring, paint', 11, 'N2', '[{"word":"色彩","reading":"しきさい","meaning":"색채"},{"word":"彩り","reading":"いろどり","meaning":"색감"}]'::jsonb, 218),
('栽', 'サイ', NULL, '재(栽), 심다', 'planting, cultivation', 10, 'N2', '[{"word":"栽培","reading":"さいばい","meaning":"재배"},{"word":"盆栽","reading":"ぼんさい","meaning":"분재"}]'::jsonb, 219),
('歳', 'サイ、セイ', 'とし', '세(歳), 나이', 'year-old, age', 13, 'N2', '[{"word":"歳","reading":"さい","meaning":"살"},{"word":"万歳","reading":"ばんざい","meaning":"만세"}]'::jsonb, 220),
('裁', 'サイ', 'た.つ、さば.く', '재(裁), 재단하다', 'judge, cut', 12, 'N2', '[{"word":"裁判","reading":"さいばん","meaning":"재판"},{"word":"裁く","reading":"さばく","meaning":"재판하다"}]'::jsonb, 221),
('載', 'サイ', 'の.せる、の.る', '재(載), 싣다', 'load, publish', 13, 'N2', '[{"word":"掲載","reading":"けいさい","meaning":"게재"},{"word":"記載","reading":"きさい","meaning":"기재"}]'::jsonb, 222),
('剤', 'ザイ', NULL, '제(剤), 약제', 'dose, medicine', 10, 'N2', '[{"word":"薬剤","reading":"やくざい","meaning":"약제"},{"word":"洗剤","reading":"せんざい","meaning":"세제"}]'::jsonb, 223),
('崎', 'キ', 'さき', '기(崎), 곶', 'cape, promontory', 11, 'N2', '[{"word":"山崎","reading":"やまざき","meaning":"야마자키"},{"word":"崎","reading":"さき","meaning":"곶"}]'::jsonb, 224),
('削', 'サク', 'けず.る', '삭(削), 깎다', 'shave, scrape', 9, 'N2', '[{"word":"削る","reading":"けずる","meaning":"깎다"},{"word":"削除","reading":"さくじょ","meaning":"삭제"}]'::jsonb, 225),
('索', 'サク', NULL, '색(索), 찾다, 밧줄', 'search, rope', 10, 'N2', '[{"word":"検索","reading":"けんさく","meaning":"검색"},{"word":"索引","reading":"さくいん","meaning":"색인"}]'::jsonb, 226),
('搾', 'サク', 'しぼ.る', '착(搾), 짜다', 'squeeze, press', 13, 'N2', '[{"word":"搾取","reading":"さくしゅ","meaning":"착취"},{"word":"搾る","reading":"しぼる","meaning":"짜내다"}]'::jsonb, 227),
('錯', 'サク', NULL, '착(錯), 엇갈리다', 'confused, mix', 16, 'N2', '[{"word":"錯覚","reading":"さっかく","meaning":"착각"},{"word":"交錯","reading":"こうさく","meaning":"교착"}]'::jsonb, 228),
('撮', 'サツ', 'と.る', '촬(撮), 찍다', 'photograph, take', 15, 'N2', '[{"word":"撮影","reading":"さつえい","meaning":"촬영"},{"word":"撮る","reading":"とる","meaning":"찍다"}]'::jsonb, 229),
('擦', 'サツ', 'す.る、こす.る', '찰(擦), 문지르다', 'rub, scrape', 17, 'N2', '[{"word":"摩擦","reading":"まさつ","meaning":"마찰"},{"word":"擦る","reading":"する","meaning":"문지르다"}]'::jsonb, 230),
('暫', 'ザン', 'しばら.く', '잠(暫), 잠시', 'temporarily, a while', 15, 'N2', '[{"word":"暫く","reading":"しばらく","meaning":"잠시"},{"word":"暫定","reading":"ざんてい","meaning":"잠정"}]'::jsonb, 231),
('惨', 'サン、ザン', 'みじ.め', '참(惨), 비참하다', 'miserable, wretched', 11, 'N2', '[{"word":"悲惨","reading":"ひさん","meaning":"비참"},{"word":"惨事","reading":"さんじ","meaning":"참사"}]'::jsonb, 232),
('桟', 'サン', NULL, '잔(桟), 나무다리', 'scaffold, pier', 10, 'N2', '[{"word":"桟橋","reading":"さんばし","meaning":"부두"},{"word":"桟敷","reading":"さじき","meaning":"관람석"}]'::jsonb, 233),
('施', 'シ、セ', 'ほどこ.す', '시(施), 베풀다', 'carry out, administer', 9, 'N2', '[{"word":"施設","reading":"しせつ","meaning":"시설"},{"word":"実施","reading":"じっし","meaning":"실시"}]'::jsonb, 234),
('旨', 'シ', 'むね、うま.い', '지(旨), 뜻, 맛있다', 'purport, delicious', 6, 'N2', '[{"word":"旨い","reading":"うまい","meaning":"맛있다"},{"word":"趣旨","reading":"しゅし","meaning":"취지"}]'::jsonb, 235),
('嗣', 'シ', NULL, '사(嗣), 잇다', 'heir, succeed', 13, 'N2', '[{"word":"嗣子","reading":"しし","meaning":"후계자"},{"word":"後嗣","reading":"こうし","meaning":"후계"}]'::jsonb, 236),
('紫', 'シ', 'むらさき', '자(紫), 보라색', 'purple, violet', 12, 'N2', '[{"word":"紫","reading":"むらさき","meaning":"보라색"},{"word":"紫外線","reading":"しがいせん","meaning":"자외선"}]'::jsonb, 237),
('飼', 'シ', 'か.う', '사(飼), 기르다', 'domesticate, raise', 13, 'N2', '[{"word":"飼う","reading":"かう","meaning":"기르다"},{"word":"飼育","reading":"しいく","meaning":"사육"}]'::jsonb, 238),
('諮', 'シ', 'はか.る', '자(諮), 자문하다', 'consult, inquire', 16, 'N2', '[{"word":"諮問","reading":"しもん","meaning":"자문"},{"word":"諮る","reading":"はかる","meaning":"자문하다"}]'::jsonb, 239),
('賜', 'シ', 'たまわ.る', '사(賜), 하사하다', 'grant, bestow', 15, 'N2', '[{"word":"賜る","reading":"たまわる","meaning":"하사받다"},{"word":"恩賜","reading":"おんし","meaning":"은사"}]'::jsonb, 240),
('雌', 'シ', 'め、めす', '자(雌), 암컷', 'female, feminine', 14, 'N2', '[{"word":"雌","reading":"めす","meaning":"암컷"},{"word":"雌雄","reading":"しゆう","meaning":"자웅"}]'::jsonb, 241),
('侍', 'ジ', 'さむらい', '시(侍), 사무라이', 'samurai, attend', 8, 'N2', '[{"word":"侍","reading":"さむらい","meaning":"사무라이"},{"word":"侍従","reading":"じじゅう","meaning":"시종"}]'::jsonb, 242),
('慈', 'ジ', 'いつく.しむ', '자(慈), 사랑하다', 'mercy, compassion', 13, 'N2', '[{"word":"慈悲","reading":"じひ","meaning":"자비"},{"word":"慈善","reading":"じぜん","meaning":"자선"}]'::jsonb, 243),
('滋', 'ジ', NULL, '자(滋), 불어나다', 'nourishing, thick', 12, 'N2', '[{"word":"滋養","reading":"じよう","meaning":"자양"},{"word":"滋賀","reading":"しが","meaning":"시가"}]'::jsonb, 244),
('璽', 'ジ', NULL, '새(璽), 옥새', 'imperial seal', 19, 'N2', '[{"word":"国璽","reading":"こくじ","meaning":"국새"},{"word":"御璽","reading":"ぎょじ","meaning":"어새"}]'::jsonb, 245),
('軸', 'ジク', NULL, '축(軸), 축', 'axis, scroll', 12, 'N2', '[{"word":"軸","reading":"じく","meaning":"축"},{"word":"車軸","reading":"しゃじく","meaning":"차축"}]'::jsonb, 246),
('漆', 'シツ', 'うるし', '칠(漆), 옻', 'lacquer, varnish', 14, 'N2', '[{"word":"漆","reading":"うるし","meaning":"옻"},{"word":"漆器","reading":"しっき","meaning":"칠기"}]'::jsonb, 247),
('疾', 'シツ', NULL, '질(疾), 질병', 'illness, rapid', 10, 'N2', '[{"word":"疾病","reading":"しっぺい","meaning":"질병"},{"word":"疾走","reading":"しっそう","meaning":"질주"}]'::jsonb, 248),
('執', 'シツ、シュウ', 'と.る', '집(執), 잡다', 'execute, take', 11, 'N2', '[{"word":"執行","reading":"しっこう","meaning":"집행"},{"word":"執着","reading":"しゅうちゃく","meaning":"집착"}]'::jsonb, 249),
('芝', 'シバ', 'しば', '지(芝), 잔디', 'lawn, turf', 6, 'N2', '[{"word":"芝生","reading":"しばふ","meaning":"잔디밭"},{"word":"芝","reading":"しば","meaning":"잔디"}]'::jsonb, 250),
('赦', 'シャ', NULL, '사(赦), 용서하다', 'pardon, forgive', 11, 'N2', '[{"word":"恩赦","reading":"おんしゃ","meaning":"은사"},{"word":"赦免","reading":"しゃめん","meaning":"사면"}]'::jsonb, 251),
('斜', 'シャ', 'なな.め', '사(斜), 비스듬하다', 'diagonal, slanting', 11, 'N2', '[{"word":"斜め","reading":"ななめ","meaning":"비스듬히"},{"word":"傾斜","reading":"けいしゃ","meaning":"경사"}]'::jsonb, 252),
('煮', 'シャ', 'に.る、に.える', '자(煮), 삶다', 'boil, cook', 12, 'N2', '[{"word":"煮る","reading":"にる","meaning":"삶다"},{"word":"煮物","reading":"にもの","meaning":"조림"}]'::jsonb, 253),
('遮', 'シャ', 'さえぎ.る', '차(遮), 가리다', 'intercept, block', 14, 'N2', '[{"word":"遮る","reading":"さえぎる","meaning":"가로막다"},{"word":"遮断","reading":"しゃだん","meaning":"차단"}]'::jsonb, 254),
('蛇', 'ジャ、ダ', 'へび', '사(蛇), 뱀', 'snake, serpent', 11, 'N2', '[{"word":"蛇","reading":"へび","meaning":"뱀"},{"word":"蛇口","reading":"じゃぐち","meaning":"수도꼭지"}]'::jsonb, 255),
('邪', 'ジャ', NULL, '사(邪), 사악하다', 'evil, wicked', 8, 'N2', '[{"word":"邪魔","reading":"じゃま","meaning":"방해"},{"word":"風邪","reading":"かぜ","meaning":"감기"}]'::jsonb, 256),
('爵', 'シャク', NULL, '작(爵), 작위', 'baron, peerage', 17, 'N2', '[{"word":"爵位","reading":"しゃくい","meaning":"작위"},{"word":"公爵","reading":"こうしゃく","meaning":"공작"}]'::jsonb, 257),
('酌', 'シャク', 'く.む', '작(酌), 술 따르다', 'serve sake, consider', 10, 'N2', '[{"word":"酌む","reading":"くむ","meaning":"술을 따르다"},{"word":"晩酌","reading":"ばんしゃく","meaning":"반주"}]'::jsonb, 258),
('趣', 'シュ', 'おもむき', '취(趣), 취미, 취지', 'gist, elegance', 15, 'N2', '[{"word":"趣味","reading":"しゅみ","meaning":"취미"},{"word":"趣旨","reading":"しゅし","meaning":"취지"}]'::jsonb, 259),
('殊', 'シュ', 'こと', '수(殊), 다르다, 특히', 'especially, different', 10, 'N2', '[{"word":"特殊","reading":"とくしゅ","meaning":"특수"},{"word":"殊に","reading":"ことに","meaning":"특히"}]'::jsonb, 260),
('狩', 'シュ', 'か.る、か.り', '수(狩), 사냥하다', 'hunt, hunting', 9, 'N2', '[{"word":"狩り","reading":"かり","meaning":"사냥"},{"word":"狩猟","reading":"しゅりょう","meaning":"수렵"}]'::jsonb, 261),
('珠', 'シュ', 'たま', '주(珠), 구슬', 'pearl, jewel', 10, 'N2', '[{"word":"真珠","reading":"しんじゅ","meaning":"진주"},{"word":"珠算","reading":"しゅざん","meaning":"주산"}]'::jsonb, 262),
('儒', 'ジュ', NULL, '유(儒), 선비', 'Confucian, scholar', 16, 'N2', '[{"word":"儒教","reading":"じゅきょう","meaning":"유교"},{"word":"儒学","reading":"じゅがく","meaning":"유학"}]'::jsonb, 263),
('呪', 'ジュ', 'のろ.う', '주(呪), 저주하다', 'curse, spell', 8, 'N2', '[{"word":"呪う","reading":"のろう","meaning":"저주하다"},{"word":"呪文","reading":"じゅもん","meaning":"주문"}]'::jsonb, 264),
('寿', 'ジュ', 'ことぶき', '수(寿), 목숨, 축하', 'longevity, congratulations', 7, 'N2', '[{"word":"寿命","reading":"じゅみょう","meaning":"수명"},{"word":"長寿","reading":"ちょうじゅ","meaning":"장수"}]'::jsonb, 265),
('需', 'ジュ', NULL, '수(需), 필요하다', 'demand, need', 14, 'N2', '[{"word":"需要","reading":"じゅよう","meaning":"수요"},{"word":"必需品","reading":"ひつじゅひん","meaning":"필수품"}]'::jsonb, 266),
('囚', 'シュウ', NULL, '수(囚), 가두다', 'prisoner, criminal', 5, 'N2', '[{"word":"囚人","reading":"しゅうじん","meaning":"죄수"},{"word":"死囚","reading":"ししゅう","meaning":"사형수"}]'::jsonb, 267),
('愁', 'シュウ', 'うれ.い、うれ.える', '수(愁), 근심', 'worry, sorrow', 13, 'N2', '[{"word":"郷愁","reading":"きょうしゅう","meaning":"향수"},{"word":"愁い","reading":"うれい","meaning":"근심"}]'::jsonb, 268),
('秀', 'シュウ', 'ひい.でる', '수(秀), 뛰어나다', 'excel, outstanding', 7, 'N2', '[{"word":"優秀","reading":"ゆうしゅう","meaning":"우수"},{"word":"秀才","reading":"しゅうさい","meaning":"수재"}]'::jsonb, 269),
('臭', 'シュウ', 'くさ.い、にお.う', '취(臭), 냄새나다', 'stinking, smelly', 9, 'N2', '[{"word":"臭い","reading":"くさい","meaning":"냄새나다"},{"word":"悪臭","reading":"あくしゅう","meaning":"악취"}]'::jsonb, 270),
('舟', 'シュウ', 'ふね、ふな', '주(舟), 배', 'boat, ship', 6, 'N2', '[{"word":"舟","reading":"ふね","meaning":"배"},{"word":"小舟","reading":"こぶね","meaning":"작은 배"}]'::jsonb, 271),
('襲', 'シュウ', 'おそ.う', '습(襲), 습격하다', 'attack, inherit', 22, 'N2', '[{"word":"襲う","reading":"おそう","meaning":"습격하다"},{"word":"襲撃","reading":"しゅうげき","meaning":"습격"}]'::jsonb, 272),
('酬', 'シュウ', NULL, '수(酬), 갚다', 'repay, reward', 13, 'N2', '[{"word":"報酬","reading":"ほうしゅう","meaning":"보수"},{"word":"応酬","reading":"おうしゅう","meaning":"응수"}]'::jsonb, 273),
('醜', 'シュウ', 'みにく.い', '추(醜), 추하다', 'ugly, disgraceful', 17, 'N2', '[{"word":"醜い","reading":"みにくい","meaning":"추하다"},{"word":"醜聞","reading":"しゅうぶん","meaning":"추문"}]'::jsonb, 274),
('充', 'ジュウ', 'あ.てる、み.たす', '충(充), 채우다', 'fill,充실', 6, 'N2', '[{"word":"充実","reading":"じゅうじつ","meaning":"충실"},{"word":"充分","reading":"じゅうぶん","meaning":"충분"}]'::jsonb, 275),
('柔', 'ジュウ、ニュウ', 'やわ.らかい', '유(柔), 부드럽다', 'tender, soft', 9, 'N2', '[{"word":"柔らかい","reading":"やわらかい","meaning":"부드럽다"},{"word":"柔道","reading":"じゅうどう","meaning":"유도"}]'::jsonb, 276),
('渋', 'ジュウ', 'しぶ、しぶ.い', '삽(渋), 떫다', 'astringent, hesitate', 11, 'N2', '[{"word":"渋い","reading":"しぶい","meaning":"떫다"},{"word":"渋滞","reading":"じゅうたい","meaning":"정체"}]'::jsonb, 277),
('銃', 'ジュウ', NULL, '총(銃), 총', 'gun, rifle', 14, 'N2', '[{"word":"銃","reading":"じゅう","meaning":"총"},{"word":"拳銃","reading":"けんじゅう","meaning":"권총"}]'::jsonb, 278),
('塾', 'ジュク', NULL, '숙(塾), 서당', 'cram school, private school', 14, 'N2', '[{"word":"塾","reading":"じゅく","meaning":"학원"},{"word":"私塾","reading":"しじゅく","meaning":"사숙"}]'::jsonb, 279),
('俊', 'シュン', NULL, '준(俊), 뛰어나다', 'talented, genius', 9, 'N2', '[{"word":"俊才","reading":"しゅんさい","meaning":"준재"},{"word":"俊敏","reading":"しゅんびん","meaning":"민첩"}]'::jsonb, 280),
('瞬', 'シュン', 'またた.く、まばた.き', '순(瞬), 눈 깜빡하다', 'blink, instant', 18, 'N2', '[{"word":"瞬間","reading":"しゅんかん","meaning":"순간"},{"word":"一瞬","reading":"いっしゅん","meaning":"일순"}]'::jsonb, 281),
('准', 'ジュン', NULL, '준(准), 준하다', 'quasi, approve', 10, 'N2', '[{"word":"准教授","reading":"じゅんきょうじゅ","meaning":"준교수"},{"word":"批准","reading":"ひじゅん","meaning":"비준"}]'::jsonb, 282),
('循', 'ジュン', NULL, '순(循), 돌다', 'circulate, follow', 12, 'N2', '[{"word":"循環","reading":"じゅんかん","meaning":"순환"},{"word":"循守","reading":"じゅんしゅ","meaning":"준수"}]'::jsonb, 283),
('殉', 'ジュン', NULL, '순(殉), 순교하다', 'martyrdom', 10, 'N2', '[{"word":"殉職","reading":"じゅんしょく","meaning":"순직"},{"word":"殉教","reading":"じゅんきょう","meaning":"순교"}]'::jsonb, 284),
('潤', 'ジュン', 'うるお.う、うるお.す', '윤(潤), 윤택하다', 'moist, profit', 15, 'N2', '[{"word":"潤う","reading":"うるおう","meaning":"윤택해지다"},{"word":"利潤","reading":"りじゅん","meaning":"이윤"}]'::jsonb, 285),
('盾', 'ジュン', 'たて', '순(盾), 방패', 'shield, escutcheon', 9, 'N2', '[{"word":"盾","reading":"たて","meaning":"방패"},{"word":"矛盾","reading":"むじゅん","meaning":"모순"}]'::jsonb, 286),
('巡', 'ジュン', 'めぐ.る', '순(巡), 돌다', 'patrol, go around', 6, 'N2', '[{"word":"巡る","reading":"めぐる","meaning":"돌아다니다"},{"word":"巡査","reading":"じゅんさ","meaning":"순사"}]'::jsonb, 287),
('遵', 'ジュン', NULL, '준(遵), 따르다', 'abide by, follow', 15, 'N2', '[{"word":"遵守","reading":"じゅんしゅ","meaning":"준수"},{"word":"遵法","reading":"じゅんぽう","meaning":"준법"}]'::jsonb, 288),
('庶', 'ショ', NULL, '서(庶), 여러', 'commoner, many', 11, 'N2', '[{"word":"庶民","reading":"しょみん","meaning":"서민"},{"word":"庶務","reading":"しょむ","meaning":"서무"}]'::jsonb, 289),
('緒', 'ショ、チョ', 'お', '서(緒), 실마리', 'beginning, thread', 14, 'N2', '[{"word":"一緒","reading":"いっしょ","meaning":"함께"},{"word":"緒言","reading":"しょげん","meaning":"서언"}]'::jsonb, 290),
('叙', 'ジョ', NULL, '서(叙), 서술하다', 'narrate, describe', 9, 'N2', '[{"word":"叙述","reading":"じょじゅつ","meaning":"서술"},{"word":"叙勲","reading":"じょくん","meaning":"서훈"}]'::jsonb, 291),
('徐', 'ジョ', 'おもむ.ろに', '서(徐), 천천히', 'gradually, slowly', 10, 'N2', '[{"word":"徐々に","reading":"じょじょに","meaning":"서서히"},{"word":"徐行","reading":"じょこう","meaning":"서행"}]'::jsonb, 292),
('償', 'ショウ', 'つぐな.う', '상(償), 갚다', 'compensate, repay', 17, 'N2', '[{"word":"賠償","reading":"ばいしょう","meaning":"배상"},{"word":"弁償","reading":"べんしょう","meaning":"변상"}]'::jsonb, 293),
('匠', 'ショウ', NULL, '장(匠), 장인', 'artisan, craftsman', 6, 'N2', '[{"word":"匠","reading":"たくみ","meaning":"장인"},{"word":"師匠","reading":"ししょう","meaning":"스승"}]'::jsonb, 294),
('升', 'ショウ', 'ます', '승(升), 되', 'measuring box, unit', 4, 'N2', '[{"word":"升","reading":"ます","meaning":"되"},{"word":"一升","reading":"いっしょう","meaning":"한 되"}]'::jsonb, 295),
('召', 'ショウ', 'め.す', '소(召), 부르다', 'summon, call', 5, 'N2', '[{"word":"召集","reading":"しょうしゅう","meaning":"소집"},{"word":"召す","reading":"めす","meaning":"부르다"}]'::jsonb, 296),
('奨', 'ショウ', NULL, '장(奨), 장려하다', 'encourage, promote', 13, 'N2', '[{"word":"奨学金","reading":"しょうがくきん","meaning":"장학금"},{"word":"推奨","reading":"すいしょう","meaning":"추천"}]'::jsonb, 297),
('宵', 'ショウ', 'よい', '소(宵), 밤', 'evening, night', 10, 'N2', '[{"word":"宵","reading":"よい","meaning":"초저녁"},{"word":"今宵","reading":"こよい","meaning":"오늘 밤"}]'::jsonb, 298),
('尚', 'ショウ', 'なお', '상(尚), 오히려', 'furthermore, esteem', 8, 'N2', '[{"word":"尚","reading":"なお","meaning":"게다가"},{"word":"高尚","reading":"こうしょう","meaning":"고상"}]'::jsonb, 299),
('床', 'ショウ', 'とこ、ゆか', '상(床), 마루, 침대', 'bed, floor', 7, 'N2', '[{"word":"床","reading":"ゆか","meaning":"마루"},{"word":"起床","reading":"きしょう","meaning":"기상"}]'::jsonb, 300),
('彰', 'ショウ', NULL, '창(彰), 밝히다', 'manifest, patent', 14, 'N2', '[{"word":"表彰","reading":"ひょうしょう","meaning":"표창"},{"word":"顕彰","reading":"けんしょう","meaning":"현창"}]'::jsonb, 301),
('抄', 'ショウ', NULL, '초(抄), 베끼다', 'extract, excerpt', 7, 'N2', '[{"word":"抄訳","reading":"しょうやく","meaning":"초역"},{"word":"抄録","reading":"しょうろく","meaning":"초록"}]'::jsonb, 302),
('掌', 'ショウ', 'てのひら', '장(掌), 손바닥', 'palm, administer', 12, 'N2', '[{"word":"掌","reading":"てのひら","meaning":"손바닥"},{"word":"掌握","reading":"しょうあく","meaning":"장악"}]'::jsonb, 303),
('昇', 'ショウ', 'のぼ.る', '승(昇), 오르다', 'rise, ascend', 8, 'N2', '[{"word":"昇進","reading":"しょうしん","meaning":"승진"},{"word":"上昇","reading":"じょうしょう","meaning":"상승"}]'::jsonb, 304),
('晶', 'ショウ', NULL, '정(晶), 수정', 'crystal, clear', 12, 'N2', '[{"word":"水晶","reading":"すいしょう","meaning":"수정"},{"word":"結晶","reading":"けっしょう","meaning":"결정"}]'::jsonb, 305),
('沼', 'ショウ', 'ぬま', '소(沼), 늪', 'swamp, marsh', 8, 'N2', '[{"word":"沼","reading":"ぬま","meaning":"늪"},{"word":"沼地","reading":"ぬまち","meaning":"늪지"}]'::jsonb, 306),
('渉', 'ショウ', NULL, '섭(渉), 건너다', 'ford, cross, negotiate', 11, 'N2', '[{"word":"交渉","reading":"こうしょう","meaning":"교섭"},{"word":"干渉","reading":"かんしょう","meaning":"간섭"}]'::jsonb, 307),
('焦', 'ショウ', 'こ.げる、こ.がす、あせ.る', '초(焦), 타다, 초조하다', 'char, scorch, hurry', 12, 'N2', '[{"word":"焦る","reading":"あせる","meaning":"초조해하다"},{"word":"焦点","reading":"しょうてん","meaning":"초점"}]'::jsonb, 308),
('症', 'ショウ', NULL, '증(症), 증세', 'symptoms, illness', 10, 'N2', '[{"word":"症状","reading":"しょうじょう","meaning":"증상"},{"word":"炎症","reading":"えんしょう","meaning":"염증"}]'::jsonb, 309),
('硝', 'ショウ', NULL, '초(硝), 초석', 'nitrate, saltpeter', 12, 'N2', '[{"word":"硝子","reading":"ガラス","meaning":"유리"},{"word":"硝酸","reading":"しょうさん","meaning":"초산"}]'::jsonb, 310),
('粧', 'ショウ', NULL, '장(粧), 꾸미다', 'cosmetics, adorn', 12, 'N2', '[{"word":"化粧","reading":"けしょう","meaning":"화장"},{"word":"粧品","reading":"しょうひん","meaning":"화장품"}]'::jsonb, 311),
('紹', 'ショウ', NULL, '소(紹), 잇다', 'introduce', 11, 'N2', '[{"word":"紹介","reading":"しょうかい","meaning":"소개"},{"word":"自己紹介","reading":"じこしょうかい","meaning":"자기소개"}]'::jsonb, 312),
('肖', 'ショウ', NULL, '초(肖), 닮다', 'resemble, portrait', 7, 'N2', '[{"word":"肖像","reading":"しょうぞう","meaning":"초상"},{"word":"不肖","reading":"ふしょう","meaning":"불초"}]'::jsonb, 313),
('衝', 'ショウ', NULL, '충(衝), 찌르다', 'collide, impact', 15, 'N2', '[{"word":"衝突","reading":"しょうとつ","meaning":"충돌"},{"word":"衝撃","reading":"しょうげき","meaning":"충격"}]'::jsonb, 314),
('訟', 'ショウ', NULL, '송(訟), 송사하다', 'lawsuit, litigation', 11, 'N2', '[{"word":"訴訟","reading":"そしょう","meaning":"소송"},{"word":"民事訟","reading":"みんじそしょう","meaning":"민사소송"}]'::jsonb, 315),
('詔', 'ショウ', 'みことのり', '조(詔), 조서', 'imperial edict', 12, 'N2', '[{"word":"詔書","reading":"しょうしょ","meaning":"조서"},{"word":"詔","reading":"みことのり","meaning":"칙서"}]'::jsonb, 316),
('障', 'ショウ', 'さわ.る', '장(障), 막다', 'obstacle, hinder', 14, 'N2', '[{"word":"障害","reading":"しょうがい","meaning":"장애"},{"word":"故障","reading":"こしょう","meaning":"고장"}]'::jsonb, 317),
('錠', 'ジョウ', NULL, '정(錠), 자물쇠', 'lock, tablet', 16, 'N2', '[{"word":"錠","reading":"じょう","meaning":"자물쇠"},{"word":"錠剤","reading":"じょうざい","meaning":"정제"}]'::jsonb, 318),
('譲', 'ジョウ', 'ゆず.る', '양(譲), 양보하다', 'hand over, yield', 20, 'N2', '[{"word":"譲る","reading":"ゆずる","meaning":"양보하다"},{"word":"譲歩","reading":"じょうほ","meaning":"양보"}]'::jsonb, 319),
('醸', 'ジョウ', 'かも.す', '양(醸), 빚다', 'brew, cause', 20, 'N2', '[{"word":"醸造","reading":"じょうぞう","meaning":"양조"},{"word":"醸す","reading":"かもす","meaning":"빚다"}]'::jsonb, 320),
('飾', 'ショク', 'かざ.る', '식(飾), 꾸미다', 'decorate, ornament', 13, 'N2', '[{"word":"飾る","reading":"かざる","meaning":"장식하다"},{"word":"装飾","reading":"そうしょく","meaning":"장식"}]'::jsonb, 321),
('嘱', 'ショク', NULL, '촉(嘱), 부탁하다', 'entrust, request', 15, 'N2', '[{"word":"嘱託","reading":"しょくたく","meaning":"촉탁"},{"word":"委嘱","reading":"いしょく","meaning":"위촉"}]'::jsonb, 322),
('殖', 'ショク', 'ふ.える、ふ.やす', '식(殖), 번식하다', 'multiply, increase', 12, 'N2', '[{"word":"繁殖","reading":"はんしょく","meaning":"번식"},{"word":"増殖","reading":"ぞうしょく","meaning":"증식"}]'::jsonb, 323),
('触', 'ショク', 'ふ.れる、さわ.る', '촉(触), 닿다', 'touch, contact', 13, 'N2', '[{"word":"接触","reading":"せっしょく","meaning":"접촉"},{"word":"触れる","reading":"ふれる","meaning":"닿다"}]'::jsonb, 324),
('辱', 'ジョク', 'はずかし.める', '욕(辱), 욕되다', 'disgrace, humiliate', 10, 'N2', '[{"word":"屈辱","reading":"くつじょく","meaning":"굴욕"},{"word":"侮辱","reading":"ぶじょく","meaning":"모욕"}]'::jsonb, 325),
('伸', 'シン', 'の.びる、の.ばす', '신(伸), 펴다', 'extend, stretch', 7, 'N2', '[{"word":"伸びる","reading":"のびる","meaning":"늘어나다"},{"word":"伸張","reading":"しんちょう","meaning":"신장"}]'::jsonb, 326),
('審', 'シン', NULL, '심(審), 심사하다', 'judge, examine', 15, 'N2', '[{"word":"審査","reading":"しんさ","meaning":"심사"},{"word":"審判","reading":"しんぱん","meaning":"심판"}]'::jsonb, 327),
('慎', 'シン', 'つつし.む', '신(慎), 삼가다', 'careful, prudent', 13, 'N2', '[{"word":"慎重","reading":"しんちょう","meaning":"신중"},{"word":"慎む","reading":"つつしむ","meaning":"삼가다"}]'::jsonb, 328),
('振', 'シン', 'ふ.る、ふ.るう', '진(振), 떨치다', 'shake, wave', 10, 'N2', '[{"word":"振る","reading":"ふる","meaning":"흔들다"},{"word":"振動","reading":"しんどう","meaning":"진동"}]'::jsonb, 329),
('浸', 'シン', 'ひた.す、ひた.る', '침(浸), 잠기다', 'soak, immerse', 10, 'N2', '[{"word":"浸す","reading":"ひたす","meaning":"담그다"},{"word":"浸水","reading":"しんすい","meaning":"침수"}]'::jsonb, 330),
('紳', 'シン', NULL, '신(紳), 신사', 'gentleman', 11, 'N2', '[{"word":"紳士","reading":"しんし","meaning":"신사"},{"word":"紳士的","reading":"しんしてき","meaning":"신사적"}]'::jsonb, 331),
('診', 'シン', 'み.る', '진(診), 진찰하다', 'examine, diagnose', 12, 'N2', '[{"word":"診察","reading":"しんさつ","meaning":"진찰"},{"word":"診断","reading":"しんだん","meaning":"진단"}]'::jsonb, 332),
('辛', 'シン', 'から.い、つら.い', '신(辛), 맵다, 괴롭다', 'spicy, painful', 7, 'N2', '[{"word":"辛い","reading":"からい","meaning":"맵다"},{"word":"辛抱","reading":"しんぼう","meaning":"인내"}]'::jsonb, 333),
('刃', 'ジン', 'は、やいば', '인(刃), 칼날', 'blade, edge', 3, 'N2', '[{"word":"刃","reading":"は","meaning":"날"},{"word":"刃物","reading":"はもの","meaning":"칼"}]'::jsonb, 334),
('尋', 'ジン', 'たず.ねる、ひろ', '심(尋), 찾다', 'inquire, search', 12, 'N2', '[{"word":"尋ねる","reading":"たずねる","meaning":"묻다"},{"word":"尋問","reading":"じんもん","meaning":"심문"}]'::jsonb, 335),
('甚', 'ジン', 'はなは.だ、はなは.だしい', '심(甚), 심하다', 'extreme, very', 9, 'N2', '[{"word":"甚だ","reading":"はなはだ","meaning":"심히"},{"word":"甚大","reading":"じんだい","meaning":"심대"}]'::jsonb, 336),
('尽', 'ジン', 'つ.くす、つ.きる', '진(尽), 다하다', 'exhaust, use up', 6, 'N2', '[{"word":"尽くす","reading":"つくす","meaning":"다하다"},{"word":"尽力","reading":"じんりょく","meaning":"진력"}]'::jsonb, 337),
('迅', 'ジン', NULL, '신(迅), 빠르다', 'swift, fast', 6, 'N2', '[{"word":"迅速","reading":"じんそく","meaning":"신속"},{"word":"迅雷","reading":"じんらい","meaning":"신뢰"}]'::jsonb, 338),
('陣', 'ジン', NULL, '진(陣), 진', 'camp, battle array', 10, 'N2', '[{"word":"陣営","reading":"じんえい","meaning":"진영"},{"word":"陣地","reading":"じんち","meaning":"진지"}]'::jsonb, 339),
('酢', 'サク', 'す', '초(酢), 식초', 'vinegar', 12, 'N2', '[{"word":"酢","reading":"す","meaning":"식초"},{"word":"酢の物","reading":"すのもの","meaning":"초무침"}]'::jsonb, 340),
('吹', 'スイ', 'ふ.く', '취(吹), 불다', 'blow, breathe', 7, 'N2', '[{"word":"吹く","reading":"ふく","meaning":"불다"},{"word":"吹雪","reading":"ふぶき","meaning":"눈보라"}]'::jsonb, 341),
('炊', 'スイ', 'た.く', '취(炊), 밥짓다', 'cook, boil', 8, 'N2', '[{"word":"炊く","reading":"たく","meaning":"밥짓다"},{"word":"炊飯器","reading":"すいはんき","meaning":"밥솥"}]'::jsonb, 342),
('帥', 'スイ', NULL, '수(帥), 장수', 'commander, general', 9, 'N2', '[{"word":"元帥","reading":"げんすい","meaning":"원수"},{"word":"統帥","reading":"とうすい","meaning":"통수"}]'::jsonb, 343),
('粋', 'スイ', 'いき', '수(粋), 정수', 'chic, essence', 10, 'N2', '[{"word":"純粋","reading":"じゅんすい","meaning":"순수"},{"word":"粋","reading":"いき","meaning":"멋"}]'::jsonb, 344),
('衰', 'スイ', 'おとろ.える', '쇠(衰), 쇠하다', 'decline, weaken', 10, 'N2', '[{"word":"衰える","reading":"おとろえる","meaning":"쇠약해지다"},{"word":"衰退","reading":"すいたい","meaning":"쇠퇴"}]'::jsonb, 345),
('遂', 'スイ', 'と.げる', '수(遂), 이루다', 'accomplish, carry out', 12, 'N2', '[{"word":"遂げる","reading":"とげる","meaning":"이루다"},{"word":"完遂","reading":"かんすい","meaning":"완수"}]'::jsonb, 346),
('酔', 'スイ', 'よ.う', '취(酔), 취하다', 'drunk, intoxicated', 11, 'N2', '[{"word":"酔う","reading":"よう","meaning":"취하다"},{"word":"酔っ払い","reading":"よっぱらい","meaning":"취객"}]'::jsonb, 347),
('随', 'ズイ', NULL, '수(随), 따르다', 'follow, comply', 12, 'N2', '[{"word":"随分","reading":"ずいぶん","meaning":"꽤"},{"word":"随筆","reading":"ずいひつ","meaning":"수필"}]'::jsonb, 348),
('髄', 'ズイ', NULL, '수(髄), 골수', 'marrow, pith', 19, 'N2', '[{"word":"骨髄","reading":"こつずい","meaning":"골수"},{"word":"真髄","reading":"しんずい","meaning":"진수"}]'::jsonb, 349),
('崇', 'スウ', 'あが.める', '숭(崇), 숭배하다', 'worship, adore', 11, 'N2', '[{"word":"崇拝","reading":"すうはい","meaning":"숭배"},{"word":"崇高","reading":"すうこう","meaning":"숭고"}]'::jsonb, 350),
('枢', 'スウ', NULL, '추(枢), 지도리', 'pivot, vital point', 8, 'N2', '[{"word":"中枢","reading":"ちゅうすう","meaning":"중추"},{"word":"枢軸","reading":"すうじく","meaning":"추축"}]'::jsonb, 351),
('据', 'キョ', 'す.える、す.わる', '거(据), 놓다', 'set, install', 11, 'N2', '[{"word":"据える","reading":"すえる","meaning":"놓다"},{"word":"据え置き","reading":"すえおき","meaning":"거치"}]'::jsonb, 352),
('杉', 'サン', 'すぎ', '삼(杉), 삼나무', 'cedar', 7, 'N2', '[{"word":"杉","reading":"すぎ","meaning":"삼나무"},{"word":"杉林","reading":"すぎばやし","meaning":"삼나무숲"}]'::jsonb, 353),
('澄', 'チョウ', 'す.む、す.ます', '징(澄), 맑다', 'clear, serene', 15, 'N2', '[{"word":"澄む","reading":"すむ","meaning":"맑아지다"},{"word":"清澄","reading":"せいちょう","meaning":"청징"}]'::jsonb, 354),
('瀬', 'ライ', 'せ', '뢰(瀬), 여울', 'rapids, shallows', 19, 'N2', '[{"word":"瀬","reading":"せ","meaning":"여울"},{"word":"浅瀬","reading":"あさせ","meaning":"얕은 곳"}]'::jsonb, 355),
('畝', 'ボウ、ム', 'うね、せ', '묘(畝), 이랑', 'furrow, ridge', 10, 'N2', '[{"word":"畝","reading":"うね","meaning":"이랑"},{"word":"畝間","reading":"うねま","meaning":"이랑 사이"}]'::jsonb, 356),
('是', 'ゼ', NULL, '시(是), 이것, 옳다', 'just so, this', 9, 'N2', '[{"word":"是非","reading":"ぜひ","meaning":"꼭, 시비"},{"word":"是正","reading":"ぜせい","meaning":"시정"}]'::jsonb, 357),
('征', 'セイ', NULL, '정(征), 치다', 'subjugate, conquer', 8, 'N2', '[{"word":"遠征","reading":"えんせい","meaning":"원정"},{"word":"征服","reading":"せいふく","meaning":"정복"}]'::jsonb, 358),
('牲', 'セイ', NULL, '생(牲), 희생', 'sacrifice, animal', 9, 'N2', '[{"word":"犠牲","reading":"ぎせい","meaning":"희생"},{"word":"牲畜","reading":"せいちく","meaning":"가축"}]'::jsonb, 359),
('誓', 'セイ', 'ちか.う', '서(誓), 맹세하다', 'vow, swear', 14, 'N2', '[{"word":"誓う","reading":"ちかう","meaning":"맹세하다"},{"word":"誓約","reading":"せいやく","meaning":"서약"}]'::jsonb, 360),
('逝', 'セイ', 'ゆ.く、い.く', '서(逝), 가다', 'departed, die', 10, 'N2', '[{"word":"逝去","reading":"せいきょ","meaning":"서거"},{"word":"急逝","reading":"きゅうせい","meaning":"급서"}]'::jsonb, 361),
('斉', 'セイ、サイ', NULL, '제(斉), 가지런하다', 'uniform, equal', 8, 'N2', '[{"word":"一斉","reading":"いっせい","meaning":"일제히"},{"word":"斉唱","reading":"せいしょう","meaning":"제창"}]'::jsonb, 362),
('隻', 'セキ', NULL, '척(隻), 척', 'counter for ships', 10, 'N2', '[{"word":"一隻","reading":"いっせき","meaning":"한 척"},{"word":"隻眼","reading":"せきがん","meaning":"외눈"}]'::jsonb, 363),
('惜', 'セキ', 'お.しい、お.しむ', '석(惜), 아깝다', 'regret, pity', 11, 'N2', '[{"word":"惜しい","reading":"おしい","meaning":"아깝다"},{"word":"惜敗","reading":"せきはい","meaning":"석패"}]'::jsonb, 364),
('斥', 'セキ', NULL, '척(斥), 물리치다', 'reject, repel', 5, 'N2', '[{"word":"排斥","reading":"はいせき","meaning":"배척"},{"word":"斥力","reading":"せきりょく","meaning":"척력"}]'::jsonb, 365),
('析', 'セキ', NULL, '석(析), 쪼개다', 'chop, analyze', 8, 'N2', '[{"word":"分析","reading":"ぶんせき","meaning":"분석"},{"word":"解析","reading":"かいせき","meaning":"해석"}]'::jsonb, 366),
('籍', 'セキ', NULL, '적(籍), 문서', 'register, book', 20, 'N2', '[{"word":"国籍","reading":"こくせき","meaning":"국적"},{"word":"書籍","reading":"しょせき","meaning":"서적"}]'::jsonb, 367),
('跡', 'セキ', 'あと', '적(跡), 자취', 'traces, mark', 13, 'N2', '[{"word":"跡","reading":"あと","meaning":"자취"},{"word":"遺跡","reading":"いせき","meaning":"유적"}]'::jsonb, 368),
('拙', 'セツ', 'つたな.い', '졸(拙), 졸렬하다', 'clumsy, unskillful', 8, 'N2', '[{"word":"拙い","reading":"つたない","meaning":"서투르다"},{"word":"稚拙","reading":"ちせつ","meaning":"치졸"}]'::jsonb, 369),
('摂', 'セツ', NULL, '섭(摂), 섭취하다', 'absorb, take in', 13, 'N2', '[{"word":"摂取","reading":"せっしゅ","meaning":"섭취"},{"word":"摂氏","reading":"せっし","meaning":"섭씨"}]'::jsonb, 370),
('窃', 'セツ', 'ぬす.む', '절(窃), 훔치다', 'steal, secretly', 9, 'N2', '[{"word":"窃盗","reading":"せっとう","meaning":"절도"},{"word":"窃取","reading":"せっしゅ","meaning":"절취"}]'::jsonb, 371),
('仙', 'セン', NULL, '선(仙), 신선', 'hermit, wizard', 5, 'N2', '[{"word":"仙人","reading":"せんにん","meaning":"선인"},{"word":"仙台","reading":"せんだい","meaning":"센다이"}]'::jsonb, 372),
('繊', 'セン', NULL, '섬(繊), 가늘다', 'slender, fiber', 17, 'N2', '[{"word":"繊維","reading":"せんい","meaning":"섬유"},{"word":"繊細","reading":"せんさい","meaning":"섬세"}]'::jsonb, 373),
('鮮', 'セン', 'あざ.やか', '선(鮮), 선명하다', 'fresh, vivid', 17, 'N2', '[{"word":"新鮮","reading":"しんせん","meaning":"신선"},{"word":"鮮明","reading":"せんめい","meaning":"선명"}]'::jsonb, 374),
('膳', 'ゼン', NULL, '선(膳), 상', 'dining tray, small table', 16, 'N2', '[{"word":"膳","reading":"ぜん","meaning":"상"},{"word":"御膳","reading":"ごぜん","meaning":"진지"}]'::jsonb, 375),
('措', 'ソ', NULL, '조(措), 놓다', 'dispose, manage', 11, 'N2', '[{"word":"措置","reading":"そち","meaning":"조치"},{"word":"措置法","reading":"そちほう","meaning":"조치법"}]'::jsonb, 376),
('礎', 'ソ', 'いしずえ', '초(礎), 주춧돌', 'foundation, cornerstone', 18, 'N2', '[{"word":"基礎","reading":"きそ","meaning":"기초"},{"word":"礎石","reading":"そせき","meaning":"초석"}]'::jsonb, 377),
('租', 'ソ', NULL, '조(租), 세금', 'tax, rent', 10, 'N2', '[{"word":"租税","reading":"そぜい","meaning":"조세"},{"word":"租借","reading":"そしゃく","meaning":"조차"}]'::jsonb, 378),
('粗', 'ソ', 'あら.い', '조(粗), 거칠다', 'coarse, rough', 11, 'N2', '[{"word":"粗い","reading":"あらい","meaning":"거칠다"},{"word":"粗末","reading":"そまつ","meaning":"조잡"}]'::jsonb, 379),
('訴', 'ソ', 'うった.える', '소(訴), 호소하다', 'accuse, appeal', 12, 'N2', '[{"word":"訴える","reading":"うったえる","meaning":"호소하다"},{"word":"訴訟","reading":"そしょう","meaning":"소송"}]'::jsonb, 380),
('阻', 'ソ', 'はば.む', '조(阻), 막다', 'obstruct, prevent', 8, 'N2', '[{"word":"阻止","reading":"そし","meaning":"저지"},{"word":"阻害","reading":"そがい","meaning":"저해"}]'::jsonb, 381),
('僧', 'ソウ', NULL, '승(僧), 중', 'monk, priest', 13, 'N2', '[{"word":"僧","reading":"そう","meaning":"승려"},{"word":"僧侶","reading":"そうりょ","meaning":"승려"}]'::jsonb, 382),
('双', 'ソウ', 'ふた', '쌍(双), 쌍', 'pair, both', 4, 'N2', '[{"word":"双子","reading":"ふたご","meaning":"쌍둥이"},{"word":"双方","reading":"そうほう","meaning":"쌍방"}]'::jsonb, 383),
('壮', 'ソウ', NULL, '장(壮), 씩씩하다', 'robust, manhood', 6, 'N2', '[{"word":"壮大","reading":"そうだい","meaning":"장대"},{"word":"壮年","reading":"そうねん","meaning":"장년"}]'::jsonb, 384),
('捜', 'ソウ', 'さが.す', '수(捜), 찾다', 'search, look for', 10, 'N2', '[{"word":"捜す","reading":"さがす","meaning":"찾다"},{"word":"捜査","reading":"そうさ","meaning":"수사"}]'::jsonb, 385),
('挿', 'ソウ', 'さ.す', '삽(挿), 꽂다', 'insert, put in', 10, 'N2', '[{"word":"挿す","reading":"さす","meaning":"꽂다"},{"word":"挿入","reading":"そうにゅう","meaning":"삽입"}]'::jsonb, 386),
('曹', 'ソウ', NULL, '조(曹), 무리', 'official, comrade', 11, 'N2', '[{"word":"曹長","reading":"そうちょう","meaning":"조장"},{"word":"法曹","reading":"ほうそう","meaning":"법조"}]'::jsonb, 387),
('槽', 'ソウ', NULL, '조(槽), 통', 'tank, trough', 15, 'N2', '[{"word":"水槽","reading":"すいそう","meaning":"수조"},{"word":"浴槽","reading":"よくそう","meaning":"욕조"}]'::jsonb, 388),
('燥', 'ソウ', NULL, '조(燥), 마르다', 'dry, parch', 17, 'N2', '[{"word":"乾燥","reading":"かんそう","meaning":"건조"},{"word":"燥ぐ","reading":"はしゃぐ","meaning":"들뜨다"}]'::jsonb, 389),
('荘', 'ソウ', NULL, '장(荘), 장원', 'villa, solemn', 9, 'N2', '[{"word":"荘厳","reading":"そうごん","meaning":"장엄"},{"word":"別荘","reading":"べっそう","meaning":"별장"}]'::jsonb, 390),
('藻', 'ソウ', 'も', '조(藻), 해초', 'seaweed, algae', 19, 'N2', '[{"word":"海藻","reading":"かいそう","meaning":"해초"},{"word":"藻","reading":"も","meaning":"해초"}]'::jsonb, 391),
('遭', 'ソウ', 'あ.う', '조(遭), 만나다', 'encounter, meet', 14, 'N2', '[{"word":"遭遇","reading":"そうぐう","meaning":"조우"},{"word":"遭難","reading":"そうなん","meaning":"조난"}]'::jsonb, 392),
('霜', 'ソウ', 'しも', '상(霜), 서리', 'frost', 17, 'N2', '[{"word":"霜","reading":"しも","meaning":"서리"},{"word":"霜柱","reading":"しもばしら","meaning":"서리기둥"}]'::jsonb, 393),
('騒', 'ソウ', 'さわ.ぐ', '소(騒), 떠들다', 'noisy, boisterous', 18, 'N2', '[{"word":"騒ぐ","reading":"さわぐ","meaning":"떠들다"},{"word":"騒音","reading":"そうおん","meaning":"소음"}]'::jsonb, 394),
('憎', 'ゾウ', 'にく.む、にく.い', '증(憎), 미워하다', 'hate, detest', 14, 'N2', '[{"word":"憎い","reading":"にくい","meaning":"밉다"},{"word":"憎悪","reading":"ぞうお","meaning":"증오"}]'::jsonb, 395),
('贈', 'ゾウ、ソウ', 'おく.る', '증(贈), 보내다', 'present, gift', 18, 'N2', '[{"word":"贈る","reading":"おくる","meaning":"선물하다"},{"word":"贈呈","reading":"ぞうてい","meaning":"증정"}]'::jsonb, 396),
('促', 'ソク', 'うなが.す', '촉(促), 재촉하다', 'urge, promote', 9, 'N2', '[{"word":"促す","reading":"うながす","meaning":"재촉하다"},{"word":"促進","reading":"そくしん","meaning":"촉진"}]'::jsonb, 397),
('即', 'ソク', 'すなわ.ち、つ.く', '즉(即), 곧', 'instant, immediately', 7, 'N2', '[{"word":"即座に","reading":"そくざに","meaning":"즉시"},{"word":"即興","reading":"そっきょう","meaning":"즉흥"}]'::jsonb, 398),
('俗', 'ゾク', NULL, '속(俗), 풍속', 'vulgar, custom', 9, 'N2', '[{"word":"風俗","reading":"ふうぞく","meaning":"풍속"},{"word":"俗語","reading":"ぞくご","meaning":"속어"}]'::jsonb, 399),
('賊', 'ゾク', NULL, '적(賊), 도적', 'thief, rebel', 13, 'N2', '[{"word":"海賊","reading":"かいぞく","meaning":"해적"},{"word":"賊","reading":"ぞく","meaning":"도적"}]'::jsonb, 400);

