-- JLPT N5 漢字 シードデータ
DELETE FROM jlpt_kanji WHERE jlpt_level = 'N5';

INSERT INTO jlpt_kanji (kanji, reading_on, reading_kun, meaning_ko, meaning_en, stroke_count, jlpt_level, example_words, sort_order) VALUES
('一', 'イチ、イツ', 'ひと.つ', '일(一), 하나', 'one', 1, 'N5',
 '[{"word":"一人","reading":"ひとり","meaning":"혼자, 한 명"},{"word":"一つ","reading":"ひとつ","meaning":"하나"},{"word":"一日","reading":"いちにち","meaning":"하루"}]'::jsonb, 1),
('二', 'ニ', 'ふた.つ', '이(二), 둘', 'two', 2, 'N5',
 '[{"word":"二人","reading":"ふたり","meaning":"두 명"},{"word":"二つ","reading":"ふたつ","meaning":"둘"}]'::jsonb, 2),
('三', 'サン', 'み.つ、み.っつ', '삼(三), 셋', 'three', 3, 'N5',
 '[{"word":"三人","reading":"さんにん","meaning":"세 명"},{"word":"三つ","reading":"みっつ","meaning":"셋"}]'::jsonb, 3),
('四', 'シ', 'よ.つ、よ.っつ、よん', '사(四), 넷', 'four', 5, 'N5',
 '[{"word":"四人","reading":"よにん","meaning":"네 명"},{"word":"四つ","reading":"よっつ","meaning":"넷"},{"word":"四月","reading":"しがつ","meaning":"4월"}]'::jsonb, 4),
('五', 'ゴ', 'いつ.つ', '오(五), 다섯', 'five', 4, 'N5',
 '[{"word":"五人","reading":"ごにん","meaning":"다섯 명"},{"word":"五つ","reading":"いつつ","meaning":"다섯"},{"word":"五月","reading":"ごがつ","meaning":"5월"}]'::jsonb, 5),
('六', 'ロク', 'む.つ、む.っつ', '육(六), 여섯', 'six', 4, 'N5',
 '[{"word":"六人","reading":"ろくにん","meaning":"여섯 명"},{"word":"六つ","reading":"むっつ","meaning":"여섯"},{"word":"六月","reading":"ろくがつ","meaning":"6월"}]'::jsonb, 6),
('七', 'シチ', 'なな.つ、なな、なの', '칠(七), 일곱', 'seven', 2, 'N5',
 '[{"word":"七人","reading":"しちにん","meaning":"일곱 명"},{"word":"七つ","reading":"ななつ","meaning":"일곱"},{"word":"七月","reading":"しちがつ","meaning":"7월"}]'::jsonb, 7),
('八', 'ハチ', 'や.つ、や.っつ、よう', '팔(八), 여덟', 'eight', 2, 'N5',
 '[{"word":"八人","reading":"はちにん","meaning":"여덟 명"},{"word":"八つ","reading":"やっつ","meaning":"여덟"},{"word":"八百","reading":"はっぴゃく","meaning":"팔백"}]'::jsonb, 8),
('九', 'キュウ、ク', 'ここの.つ', '구(九), 아홉', 'nine', 2, 'N5',
 '[{"word":"九人","reading":"きゅうにん","meaning":"아홉 명"},{"word":"九つ","reading":"ここのつ","meaning":"아홉"},{"word":"九月","reading":"くがつ","meaning":"9월"}]'::jsonb, 9),
('十', 'ジュウ、ジッ', 'とお、と', '십(十), 열', 'ten', 2, 'N5',
 '[{"word":"十人","reading":"じゅうにん","meaning":"열 명"},{"word":"十日","reading":"とおか","meaning":"열흘, 10일"},{"word":"二十","reading":"にじゅう","meaning":"스물"}]'::jsonb, 10),
('百', 'ヒャク', NULL, '백(百), 온', 'hundred', 6, 'N5',
 '[{"word":"百人","reading":"ひゃくにん","meaning":"백 명"},{"word":"三百","reading":"さんびゃく","meaning":"삼백"},{"word":"百円","reading":"ひゃくえん","meaning":"백 엔"}]'::jsonb, 11),
('千', 'セン', 'ち', '천(千), 천', 'thousand', 3, 'N5',
 '[{"word":"千人","reading":"せんにん","meaning":"천 명"},{"word":"千円","reading":"せんえん","meaning":"천 엔"},{"word":"三千","reading":"さんぜん","meaning":"삼천"}]'::jsonb, 12),
('万', 'マン、バン', 'よろず', '만(萬), 일만', 'ten thousand', 3, 'N5',
 '[{"word":"一万","reading":"いちまん","meaning":"만"},{"word":"万年筆","reading":"まんねんひつ","meaning":"만년필"}]'::jsonb, 13),
('円', 'エン', 'まる.い', '원(圓), 둥글다', 'circle, yen', 4, 'N5',
 '[{"word":"百円","reading":"ひゃくえん","meaning":"백 엔"},{"word":"千円","reading":"せんえん","meaning":"천 엔"},{"word":"円い","reading":"まるい","meaning":"둥글다"}]'::jsonb, 14),
('人', 'ジン、ニン', 'ひと', '인(人), 사람', 'person, people', 2, 'N5',
 '[{"word":"一人","reading":"ひとり","meaning":"혼자"},{"word":"日本人","reading":"にほんじん","meaning":"일본인"},{"word":"大人","reading":"おとな","meaning":"어른"}]'::jsonb, 15),
('日', 'ニチ、ジツ', 'ひ、か', '일(日), 날', 'day, sun', 4, 'N5',
 '[{"word":"日本","reading":"にほん","meaning":"일본"},{"word":"毎日","reading":"まいにち","meaning":"매일"},{"word":"今日","reading":"きょう","meaning":"오늘"}]'::jsonb, 16),
('月', 'ゲツ、ガツ', 'つき', '월(月), 달', 'month, moon', 4, 'N5',
 '[{"word":"一月","reading":"いちがつ","meaning":"1월"},{"word":"今月","reading":"こんげつ","meaning":"이번 달"},{"word":"月曜日","reading":"げつようび","meaning":"월요일"}]'::jsonb, 17),
('火', 'カ', 'ひ、ほ', '화(火), 불', 'fire', 4, 'N5',
 '[{"word":"火曜日","reading":"かようび","meaning":"화요일"},{"word":"火事","reading":"かじ","meaning":"화재"},{"word":"花火","reading":"はなび","meaning":"불꽃놀이"}]'::jsonb, 18),
('水', 'スイ', 'みず', '수(水), 물', 'water', 4, 'N5',
 '[{"word":"水曜日","reading":"すいようび","meaning":"수요일"},{"word":"お水","reading":"おみず","meaning":"물"},{"word":"水泳","reading":"すいえい","meaning":"수영"}]'::jsonb, 19),
('木', 'モク、ボク', 'き、こ', '목(木), 나무', 'tree, wood', 4, 'N5',
 '[{"word":"木曜日","reading":"もくようび","meaning":"목요일"},{"word":"木","reading":"き","meaning":"나무"},{"word":"大木","reading":"たいぼく","meaning":"큰 나무"}]'::jsonb, 20),
('金', 'キン、コン', 'かね、かな', '금(金), 쇠, 돈', 'gold, money, metal', 8, 'N5',
 '[{"word":"金曜日","reading":"きんようび","meaning":"금요일"},{"word":"お金","reading":"おかね","meaning":"돈"},{"word":"金色","reading":"きんいろ","meaning":"금색"}]'::jsonb, 21),
('土', 'ド、ト', 'つち', '토(土), 흙', 'earth, soil', 3, 'N5',
 '[{"word":"土曜日","reading":"どようび","meaning":"토요일"},{"word":"土地","reading":"とち","meaning":"토지"},{"word":"土","reading":"つち","meaning":"흙"}]'::jsonb, 22),
('年', 'ネン', 'とし', '년(年), 해', 'year', 6, 'N5',
 '[{"word":"今年","reading":"ことし","meaning":"올해"},{"word":"去年","reading":"きょねん","meaning":"작년"},{"word":"毎年","reading":"まいとし","meaning":"매년"}]'::jsonb, 23),
('時', 'ジ', 'とき', '시(時), 때', 'time, hour', 10, 'N5',
 '[{"word":"時間","reading":"じかん","meaning":"시간"},{"word":"時計","reading":"とけい","meaning":"시계"},{"word":"何時","reading":"なんじ","meaning":"몇 시"}]'::jsonb, 24),
('分', 'ブン、フン、ブ', 'わ.かる、わ.ける', '분(分), 나누다', 'minute, part, understand', 4, 'N5',
 '[{"word":"十分","reading":"じゅっぷん","meaning":"10분"},{"word":"自分","reading":"じぶん","meaning":"자기 자신"},{"word":"半分","reading":"はんぶん","meaning":"절반"}]'::jsonb, 25),
('半', 'ハン', 'なか.ば', '반(半), 반', 'half', 5, 'N5',
 '[{"word":"半分","reading":"はんぶん","meaning":"절반"},{"word":"半年","reading":"はんとし","meaning":"반년"},{"word":"三時半","reading":"さんじはん","meaning":"3시 반"}]'::jsonb, 26),
('今', 'コン、キン', 'いま', '금(今), 이제', 'now, present', 4, 'N5',
 '[{"word":"今日","reading":"きょう","meaning":"오늘"},{"word":"今月","reading":"こんげつ","meaning":"이번 달"},{"word":"今年","reading":"ことし","meaning":"올해"}]'::jsonb, 27),
('何', 'カ', 'なに、なん', '하(何), 무엇', 'what', 7, 'N5',
 '[{"word":"何人","reading":"なんにん","meaning":"몇 명"},{"word":"何時","reading":"なんじ","meaning":"몇 시"},{"word":"何曜日","reading":"なんようび","meaning":"무슨 요일"}]'::jsonb, 28),
('前', 'ゼン', 'まえ', '전(前), 앞', 'before, front', 9, 'N5',
 '[{"word":"名前","reading":"なまえ","meaning":"이름"},{"word":"午前","reading":"ごぜん","meaning":"오전"},{"word":"前","reading":"まえ","meaning":"앞"}]'::jsonb, 29),
('後', 'ゴ、コウ', 'のち、うし.ろ、あと', '후(後), 뒤', 'after, behind', 9, 'N5',
 '[{"word":"午後","reading":"ごご","meaning":"오후"},{"word":"後ろ","reading":"うしろ","meaning":"뒤"},{"word":"最後","reading":"さいご","meaning":"마지막"}]'::jsonb, 30),
('午', 'ゴ', NULL, '오(午), 낮', 'noon', 4, 'N5',
 '[{"word":"午前","reading":"ごぜん","meaning":"오전"},{"word":"午後","reading":"ごご","meaning":"오후"},{"word":"正午","reading":"しょうご","meaning":"정오"}]'::jsonb, 31),
('上', 'ジョウ、ショウ', 'うえ、あ.がる、のぼ.る', '상(上), 위', 'up, above', 3, 'N5',
 '[{"word":"上","reading":"うえ","meaning":"위"},{"word":"上手","reading":"じょうず","meaning":"잘하다"},{"word":"上がる","reading":"あがる","meaning":"오르다"}]'::jsonb, 32),
('下', 'カ、ゲ', 'した、さ.がる、くだ.る、お.りる', '하(下), 아래', 'down, below', 3, 'N5',
 '[{"word":"下","reading":"した","meaning":"아래"},{"word":"下手","reading":"へた","meaning":"서투르다"},{"word":"地下鉄","reading":"ちかてつ","meaning":"지하철"}]'::jsonb, 33),
('中', 'チュウ', 'なか', '중(中), 가운데', 'middle, inside', 4, 'N5',
 '[{"word":"中","reading":"なか","meaning":"안, 가운데"},{"word":"中国","reading":"ちゅうごく","meaning":"중국"},{"word":"一日中","reading":"いちにちじゅう","meaning":"하루 종일"}]'::jsonb, 34),
('外', 'ガイ、ゲ', 'そと、ほか、はず.す', '외(外), 바깥', 'outside', 5, 'N5',
 '[{"word":"外","reading":"そと","meaning":"바깥"},{"word":"外国","reading":"がいこく","meaning":"외국"},{"word":"外国人","reading":"がいこくじん","meaning":"외국인"}]'::jsonb, 35),
('大', 'ダイ、タイ', 'おお.きい', '대(大), 크다', 'big, large', 3, 'N5',
 '[{"word":"大きい","reading":"おおきい","meaning":"크다"},{"word":"大学","reading":"だいがく","meaning":"대학"},{"word":"大人","reading":"おとな","meaning":"어른"}]'::jsonb, 36),
('小', 'ショウ', 'ちい.さい、こ、お', '소(小), 작다', 'small, little', 3, 'N5',
 '[{"word":"小さい","reading":"ちいさい","meaning":"작다"},{"word":"小学校","reading":"しょうがっこう","meaning":"초등학교"},{"word":"小説","reading":"しょうせつ","meaning":"소설"}]'::jsonb, 37),
('長', 'チョウ', 'なが.い', '장(長), 길다', 'long, chief', 8, 'N5',
 '[{"word":"長い","reading":"ながい","meaning":"길다"},{"word":"社長","reading":"しゃちょう","meaning":"사장"},{"word":"長さ","reading":"ながさ","meaning":"길이"}]'::jsonb, 38),
('高', 'コウ', 'たか.い', '고(高), 높다', 'tall, high, expensive', 10, 'N5',
 '[{"word":"高い","reading":"たかい","meaning":"높다, 비싸다"},{"word":"高校","reading":"こうこう","meaning":"고등학교"},{"word":"最高","reading":"さいこう","meaning":"최고"}]'::jsonb, 39),
('安', 'アン', 'やす.い', '안(安), 싸다, 편안하다', 'cheap, peaceful', 6, 'N5',
 '[{"word":"安い","reading":"やすい","meaning":"싸다"},{"word":"安心","reading":"あんしん","meaning":"안심"},{"word":"安全","reading":"あんぜん","meaning":"안전"}]'::jsonb, 40),
('新', 'シン', 'あたら.しい、あら.た、にい', '신(新), 새롭다', 'new', 13, 'N5',
 '[{"word":"新しい","reading":"あたらしい","meaning":"새롭다"},{"word":"新聞","reading":"しんぶん","meaning":"신문"},{"word":"新年","reading":"しんねん","meaning":"새해"}]'::jsonb, 41),
('古', 'コ', 'ふる.い', '고(古), 오래되다', 'old (not for age)', 5, 'N5',
 '[{"word":"古い","reading":"ふるい","meaning":"오래되다"},{"word":"中古","reading":"ちゅうこ","meaning":"중고"},{"word":"古典","reading":"こてん","meaning":"고전"}]'::jsonb, 42),
('多', 'タ', 'おお.い', '다(多), 많다', 'many, much', 6, 'N5',
 '[{"word":"多い","reading":"おおい","meaning":"많다"},{"word":"多分","reading":"たぶん","meaning":"아마"},{"word":"多少","reading":"たしょう","meaning":"다소"}]'::jsonb, 43),
('少', 'ショウ', 'すく.ない、すこ.し', '소(少), 적다', 'few, little', 4, 'N5',
 '[{"word":"少ない","reading":"すくない","meaning":"적다"},{"word":"少し","reading":"すこし","meaning":"조금"},{"word":"少年","reading":"しょうねん","meaning":"소년"}]'::jsonb, 44),
('白', 'ハク、ビャク', 'しろ、しろ.い', '백(白), 흰', 'white', 5, 'N5',
 '[{"word":"白い","reading":"しろい","meaning":"하얗다"},{"word":"白","reading":"しろ","meaning":"흰색"},{"word":"白人","reading":"はくじん","meaning":"백인"}]'::jsonb, 45),
('黒', 'コク', 'くろ、くろ.い', '흑(黑), 검다', 'black', 11, 'N5',
 '[{"word":"黒い","reading":"くろい","meaning":"검다"},{"word":"黒","reading":"くろ","meaning":"검은색"},{"word":"黒板","reading":"こくばん","meaning":"칠판"}]'::jsonb, 46),
('赤', 'セキ、シャク', 'あか、あか.い', '적(赤), 붉다', 'red', 7, 'N5',
 '[{"word":"赤い","reading":"あかい","meaning":"빨갛다"},{"word":"赤ちゃん","reading":"あかちゃん","meaning":"아기"},{"word":"赤","reading":"あか","meaning":"빨간색"}]'::jsonb, 47),
('青', 'セイ、ショウ', 'あお、あお.い', '청(靑), 푸르다', 'blue, green', 8, 'N5',
 '[{"word":"青い","reading":"あおい","meaning":"파랗다"},{"word":"青年","reading":"せいねん","meaning":"청년"},{"word":"青空","reading":"あおぞら","meaning":"푸른 하늘"}]'::jsonb, 48),
('北', 'ホク', 'きた', '북(北), 북쪽', 'north', 5, 'N5',
 '[{"word":"北","reading":"きた","meaning":"북쪽"},{"word":"北海道","reading":"ほっかいどう","meaning":"홋카이도"},{"word":"北口","reading":"きたぐち","meaning":"북쪽 출구"}]'::jsonb, 49),
('南', 'ナン、ナ', 'みなみ', '남(南), 남쪽', 'south', 9, 'N5',
 '[{"word":"南","reading":"みなみ","meaning":"남쪽"},{"word":"南口","reading":"みなみぐち","meaning":"남쪽 출구"},{"word":"南米","reading":"なんべい","meaning":"남미"}]'::jsonb, 50),
('東', 'トウ', 'ひがし', '동(東), 동쪽', 'east', 8, 'N5',
 '[{"word":"東","reading":"ひがし","meaning":"동쪽"},{"word":"東京","reading":"とうきょう","meaning":"도쿄"},{"word":"東口","reading":"ひがしぐち","meaning":"동쪽 출구"}]'::jsonb, 51),
('西', 'セイ、サイ', 'にし', '서(西), 서쪽', 'west', 6, 'N5',
 '[{"word":"西","reading":"にし","meaning":"서쪽"},{"word":"西口","reading":"にしぐち","meaning":"서쪽 출구"},{"word":"北西","reading":"ほくせい","meaning":"북서"}]'::jsonb, 52),
('右', 'ウ、ユウ', 'みぎ', '우(右), 오른쪽', 'right', 5, 'N5',
 '[{"word":"右","reading":"みぎ","meaning":"오른쪽"},{"word":"右手","reading":"みぎて","meaning":"오른손"},{"word":"左右","reading":"さゆう","meaning":"좌우"}]'::jsonb, 53),
('左', 'サ', 'ひだり', '좌(左), 왼쪽', 'left', 5, 'N5',
 '[{"word":"左","reading":"ひだり","meaning":"왼쪽"},{"word":"左手","reading":"ひだりて","meaning":"왼손"},{"word":"左右","reading":"さゆう","meaning":"좌우"}]'::jsonb, 54),
('間', 'カン、ケン', 'あいだ、ま', '간(間), 사이', 'between, interval', 12, 'N5',
 '[{"word":"時間","reading":"じかん","meaning":"시간"},{"word":"間","reading":"あいだ","meaning":"사이"},{"word":"人間","reading":"にんげん","meaning":"인간"}]'::jsonb, 55),
('入', 'ニュウ', 'い.る、はい.る', '입(入), 들다', 'enter, insert', 2, 'N5',
 '[{"word":"入る","reading":"はいる","meaning":"들어가다"},{"word":"入口","reading":"いりぐち","meaning":"입구"},{"word":"入学","reading":"にゅうがく","meaning":"입학"}]'::jsonb, 56),
('出', 'シュツ、スイ', 'で.る、だ.す', '출(出), 나다', 'exit, leave', 5, 'N5',
 '[{"word":"出る","reading":"でる","meaning":"나가다"},{"word":"出口","reading":"でぐち","meaning":"출구"},{"word":"出す","reading":"だす","meaning":"꺼내다"}]'::jsonb, 57),
('行', 'コウ、ギョウ', 'い.く、ゆ.く、おこな.う', '행(行), 가다', 'go, carry out', 6, 'N5',
 '[{"word":"行く","reading":"いく","meaning":"가다"},{"word":"旅行","reading":"りょこう","meaning":"여행"},{"word":"銀行","reading":"ぎんこう","meaning":"은행"}]'::jsonb, 58),
('来', 'ライ', 'く.る、きた.る', '래(來), 오다', 'come', 7, 'N5',
 '[{"word":"来る","reading":"くる","meaning":"오다"},{"word":"来月","reading":"らいげつ","meaning":"다음 달"},{"word":"来年","reading":"らいねん","meaning":"내년"}]'::jsonb, 59),
('帰', 'キ', 'かえ.る、かえ.す', '귀(歸), 돌아가다', 'return, go home', 10, 'N5',
 '[{"word":"帰る","reading":"かえる","meaning":"돌아가다"},{"word":"帰り","reading":"かえり","meaning":"귀가"},{"word":"帰国","reading":"きこく","meaning":"귀국"}]'::jsonb, 60),
('食', 'ショク、ジキ', 'た.べる、く.う', '식(食), 먹다', 'eat, food, meal', 9, 'N5',
 '[{"word":"食べる","reading":"たべる","meaning":"먹다"},{"word":"食事","reading":"しょくじ","meaning":"식사"},{"word":"食堂","reading":"しょくどう","meaning":"식당"}]'::jsonb, 61),
('飲', 'イン', 'の.む', '음(飮), 마시다', 'drink', 12, 'N5',
 '[{"word":"飲む","reading":"のむ","meaning":"마시다"},{"word":"飲み物","reading":"のみもの","meaning":"음료"},{"word":"飲料","reading":"いんりょう","meaning":"음료수"}]'::jsonb, 62),
('見', 'ケン', 'み.る、み.える', '견(見), 보다', 'see, look', 7, 'N5',
 '[{"word":"見る","reading":"みる","meaning":"보다"},{"word":"見える","reading":"みえる","meaning":"보이다"},{"word":"花見","reading":"はなみ","meaning":"꽃구경"}]'::jsonb, 63),
('聞', 'ブン、モン', 'き.く、き.こえる', '문(聞), 듣다', 'hear, listen, ask', 14, 'N5',
 '[{"word":"聞く","reading":"きく","meaning":"듣다"},{"word":"聞こえる","reading":"きこえる","meaning":"들리다"},{"word":"新聞","reading":"しんぶん","meaning":"신문"}]'::jsonb, 64),
('読', 'ドク、トク、トウ', 'よ.む', '독(讀), 읽다', 'read', 14, 'N5',
 '[{"word":"読む","reading":"よむ","meaning":"읽다"},{"word":"読書","reading":"どくしょ","meaning":"독서"},{"word":"読み方","reading":"よみかた","meaning":"읽는 법"}]'::jsonb, 65),
('書', 'ショ', 'か.く', '서(書), 쓰다', 'write, book', 10, 'N5',
 '[{"word":"書く","reading":"かく","meaning":"쓰다"},{"word":"辞書","reading":"じしょ","meaning":"사전"},{"word":"図書館","reading":"としょかん","meaning":"도서관"}]'::jsonb, 66),
('話', 'ワ', 'はな.す、はなし', '화(話), 말하다', 'speak, talk, story', 13, 'N5',
 '[{"word":"話す","reading":"はなす","meaning":"말하다"},{"word":"電話","reading":"でんわ","meaning":"전화"},{"word":"会話","reading":"かいわ","meaning":"회화"}]'::jsonb, 67),
('買', 'バイ', 'か.う', '매(買), 사다', 'buy', 12, 'N5',
 '[{"word":"買う","reading":"かう","meaning":"사다"},{"word":"買い物","reading":"かいもの","meaning":"쇼핑"},{"word":"売買","reading":"ばいばい","meaning":"매매"}]'::jsonb, 68),
('立', 'リツ、リュウ', 'た.つ、た.てる', '립(立), 서다', 'stand', 5, 'N5',
 '[{"word":"立つ","reading":"たつ","meaning":"서다"},{"word":"立てる","reading":"たてる","meaning":"세우다"},{"word":"国立","reading":"こくりつ","meaning":"국립"}]'::jsonb, 69),
('休', 'キュウ', 'やす.む、やす.み', '휴(休), 쉬다', 'rest, holiday', 6, 'N5',
 '[{"word":"休む","reading":"やすむ","meaning":"쉬다"},{"word":"休み","reading":"やすみ","meaning":"휴일"},{"word":"休日","reading":"きゅうじつ","meaning":"휴일"}]'::jsonb, 70),
('学', 'ガク', 'まな.ぶ', '학(學), 배우다', 'study, learn', 8, 'N5',
 '[{"word":"学生","reading":"がくせい","meaning":"학생"},{"word":"大学","reading":"だいがく","meaning":"대학"},{"word":"学校","reading":"がっこう","meaning":"학교"}]'::jsonb, 71),
('先', 'セン', 'さき', '선(先), 먼저', 'previous, ahead', 6, 'N5',
 '[{"word":"先生","reading":"せんせい","meaning":"선생님"},{"word":"先月","reading":"せんげつ","meaning":"지난 달"},{"word":"先週","reading":"せんしゅう","meaning":"지난 주"}]'::jsonb, 72),
('生', 'セイ、ショウ', 'い.きる、う.まれる、なま', '생(生), 나다, 살다', 'life, birth, raw', 5, 'N5',
 '[{"word":"先生","reading":"せんせい","meaning":"선생님"},{"word":"学生","reading":"がくせい","meaning":"학생"},{"word":"生まれる","reading":"うまれる","meaning":"태어나다"}]'::jsonb, 73),
('電', 'デン', NULL, '전(電), 번개', 'electricity', 13, 'N5',
 '[{"word":"電話","reading":"でんわ","meaning":"전화"},{"word":"電車","reading":"でんしゃ","meaning":"전철"},{"word":"電気","reading":"でんき","meaning":"전기"}]'::jsonb, 74),
('車', 'シャ', 'くるま', '차(車), 수레', 'car, vehicle', 7, 'N5',
 '[{"word":"電車","reading":"でんしゃ","meaning":"전철"},{"word":"自転車","reading":"じてんしゃ","meaning":"자전거"},{"word":"車","reading":"くるま","meaning":"자동차"}]'::jsonb, 75),
('天', 'テン', 'あめ、あま', '천(天), 하늘', 'heaven, sky', 4, 'N5',
 '[{"word":"天気","reading":"てんき","meaning":"날씨"},{"word":"天国","reading":"てんごく","meaning":"천국"},{"word":"天才","reading":"てんさい","meaning":"천재"}]'::jsonb, 76),
('気', 'キ、ケ', NULL, '기(氣), 기운', 'spirit, energy, mood', 6, 'N5',
 '[{"word":"天気","reading":"てんき","meaning":"날씨"},{"word":"元気","reading":"げんき","meaning":"건강, 활기"},{"word":"気持ち","reading":"きもち","meaning":"기분"}]'::jsonb, 77),
('雨', 'ウ', 'あめ、あま', '우(雨), 비', 'rain', 8, 'N5',
 '[{"word":"雨","reading":"あめ","meaning":"비"},{"word":"大雨","reading":"おおあめ","meaning":"폭우"},{"word":"梅雨","reading":"つゆ","meaning":"장마"}]'::jsonb, 78),
('国', 'コク', 'くに', '국(國), 나라', 'country', 8, 'N5',
 '[{"word":"国","reading":"くに","meaning":"나라"},{"word":"外国","reading":"がいこく","meaning":"외국"},{"word":"中国","reading":"ちゅうごく","meaning":"중국"}]'::jsonb, 79),
('山', 'サン、セン', 'やま', '산(山), 산', 'mountain', 3, 'N5',
 '[{"word":"山","reading":"やま","meaning":"산"},{"word":"富士山","reading":"ふじさん","meaning":"후지산"},{"word":"火山","reading":"かざん","meaning":"화산"}]'::jsonb, 80),
('川', 'セン', 'かわ', '천(川), 내', 'river', 3, 'N5',
 '[{"word":"川","reading":"かわ","meaning":"강"},{"word":"小川","reading":"おがわ","meaning":"시내, 개울"}]'::jsonb, 81),
('花', 'カ', 'はな', '화(花), 꽃', 'flower', 7, 'N5',
 '[{"word":"花","reading":"はな","meaning":"꽃"},{"word":"花見","reading":"はなみ","meaning":"꽃구경"},{"word":"花火","reading":"はなび","meaning":"불꽃놀이"}]'::jsonb, 82),
('道', 'ドウ、トウ', 'みち', '도(道), 길', 'road, way, path', 12, 'N5',
 '[{"word":"道","reading":"みち","meaning":"길"},{"word":"北海道","reading":"ほっかいどう","meaning":"홋카이도"},{"word":"道路","reading":"どうろ","meaning":"도로"}]'::jsonb, 83),
('駅', 'エキ', NULL, '역(驛), 역', 'station', 14, 'N5',
 '[{"word":"駅","reading":"えき","meaning":"역"},{"word":"駅前","reading":"えきまえ","meaning":"역 앞"},{"word":"東京駅","reading":"とうきょうえき","meaning":"도쿄역"}]'::jsonb, 84),
('名', 'メイ、ミョウ', 'な', '명(名), 이름', 'name', 6, 'N5',
 '[{"word":"名前","reading":"なまえ","meaning":"이름"},{"word":"有名","reading":"ゆうめい","meaning":"유명"},{"word":"名人","reading":"めいじん","meaning":"명인"}]'::jsonb, 85),
('語', 'ゴ', 'かた.る', '어(語), 말씀', 'language, word', 14, 'N5',
 '[{"word":"日本語","reading":"にほんご","meaning":"일본어"},{"word":"英語","reading":"えいご","meaning":"영어"},{"word":"物語","reading":"ものがたり","meaning":"이야기"}]'::jsonb, 86),
('英', 'エイ', NULL, '영(英), 꽃부리', 'English, excellent', 8, 'N5',
 '[{"word":"英語","reading":"えいご","meaning":"영어"},{"word":"英国","reading":"えいこく","meaning":"영국"},{"word":"英会話","reading":"えいかいわ","meaning":"영어 회화"}]'::jsonb, 87),
('会', 'カイ、エ', 'あ.う', '회(會), 만나다, 모이다', 'meet, society', 6, 'N5',
 '[{"word":"会う","reading":"あう","meaning":"만나다"},{"word":"会社","reading":"かいしゃ","meaning":"회사"},{"word":"会話","reading":"かいわ","meaning":"회화"}]'::jsonb, 88),
('社', 'シャ', 'やしろ', '사(社), 모이다', 'company, shrine', 7, 'N5',
 '[{"word":"会社","reading":"かいしゃ","meaning":"회사"},{"word":"社長","reading":"しゃちょう","meaning":"사장"},{"word":"社会","reading":"しゃかい","meaning":"사회"}]'::jsonb, 89),
('校', 'コウ', NULL, '교(校), 학교', 'school', 10, 'N5',
 '[{"word":"学校","reading":"がっこう","meaning":"학교"},{"word":"高校","reading":"こうこう","meaning":"고등학교"},{"word":"校長","reading":"こうちょう","meaning":"교장"}]'::jsonb, 90),
('店', 'テン', 'みせ', '점(店), 가게', 'shop, store', 8, 'N5',
 '[{"word":"店","reading":"みせ","meaning":"가게"},{"word":"喫茶店","reading":"きっさてん","meaning":"찻집"},{"word":"店員","reading":"てんいん","meaning":"점원"}]'::jsonb, 91),
('家', 'カ、ケ', 'いえ、や、うち', '가(家), 집', 'house, home, family', 10, 'N5',
 '[{"word":"家","reading":"いえ","meaning":"집"},{"word":"家族","reading":"かぞく","meaning":"가족"},{"word":"家庭","reading":"かてい","meaning":"가정"}]'::jsonb, 92),
('母', 'ボ', 'はは、かあ', '모(母), 어머니', 'mother', 5, 'N5',
 '[{"word":"お母さん","reading":"おかあさん","meaning":"어머니"},{"word":"母","reading":"はは","meaning":"어머니(겸양)"},{"word":"母国","reading":"ぼこく","meaning":"모국"}]'::jsonb, 93),
('父', 'フ', 'ちち、とう', '부(父), 아버지', 'father', 4, 'N5',
 '[{"word":"お父さん","reading":"おとうさん","meaning":"아버지"},{"word":"父","reading":"ちち","meaning":"아버지(겸양)"},{"word":"父母","reading":"ふぼ","meaning":"부모"}]'::jsonb, 94),
('友', 'ユウ', 'とも', '우(友), 벗', 'friend', 4, 'N5',
 '[{"word":"友達","reading":"ともだち","meaning":"친구"},{"word":"友人","reading":"ゆうじん","meaning":"친구"},{"word":"親友","reading":"しんゆう","meaning":"친한 친구"}]'::jsonb, 95),
('子', 'シ、ス', 'こ', '자(子), 아이', 'child', 3, 'N5',
 '[{"word":"子供","reading":"こども","meaning":"아이"},{"word":"女の子","reading":"おんなのこ","meaning":"여자아이"},{"word":"男の子","reading":"おとこのこ","meaning":"남자아이"}]'::jsonb, 96),
('男', 'ダン、ナン', 'おとこ', '남(男), 사내', 'man, male', 7, 'N5',
 '[{"word":"男","reading":"おとこ","meaning":"남자"},{"word":"男の子","reading":"おとこのこ","meaning":"남자아이"},{"word":"男性","reading":"だんせい","meaning":"남성"}]'::jsonb, 97),
('女', 'ジョ、ニョ', 'おんな、め', '여(女), 여자', 'woman, female', 3, 'N5',
 '[{"word":"女","reading":"おんな","meaning":"여자"},{"word":"女の子","reading":"おんなのこ","meaning":"여자아이"},{"word":"女性","reading":"じょせい","meaning":"여성"}]'::jsonb, 98),
('本', 'ホン', 'もと', '본(本), 근본, 책', 'book, origin', 5, 'N5',
 '[{"word":"本","reading":"ほん","meaning":"책"},{"word":"日本","reading":"にほん","meaning":"일본"},{"word":"本当","reading":"ほんとう","meaning":"정말"}]'::jsonb, 99),
('手', 'シュ', 'て', '수(手), 손', 'hand', 4, 'N5',
 '[{"word":"手","reading":"て","meaning":"손"},{"word":"上手","reading":"じょうず","meaning":"잘하다"},{"word":"手紙","reading":"てがみ","meaning":"편지"}]'::jsonb, 100),
('足', 'ソク', 'あし、た.りる、た.す', '족(足), 발, 충분하다', 'foot, leg, enough', 7, 'N5',
 '[{"word":"足","reading":"あし","meaning":"발, 다리"},{"word":"足りる","reading":"たりる","meaning":"충분하다"},{"word":"遠足","reading":"えんそく","meaning":"소풍"}]'::jsonb, 101),
('目', 'モク、ボク', 'め', '목(目), 눈', 'eye', 5, 'N5',
 '[{"word":"目","reading":"め","meaning":"눈"},{"word":"目的","reading":"もくてき","meaning":"목적"},{"word":"科目","reading":"かもく","meaning":"과목"}]'::jsonb, 102),
('口', 'コウ、ク', 'くち', '구(口), 입', 'mouth', 3, 'N5',
 '[{"word":"口","reading":"くち","meaning":"입"},{"word":"入口","reading":"いりぐち","meaning":"입구"},{"word":"出口","reading":"でぐち","meaning":"출구"}]'::jsonb, 103),
('耳', 'ジ', 'みみ', '이(耳), 귀', 'ear', 6, 'N5',
 '[{"word":"耳","reading":"みみ","meaning":"귀"},{"word":"耳鳴り","reading":"みみなり","meaning":"이명"},{"word":"早耳","reading":"はやみみ","meaning":"빠른 귀"}]'::jsonb, 104),
('毎', 'マイ', 'ごと', '매(每), 매양', 'every, each', 6, 'N5',
 '[{"word":"毎日","reading":"まいにち","meaning":"매일"},{"word":"毎月","reading":"まいつき","meaning":"매월"},{"word":"毎年","reading":"まいとし","meaning":"매년"}]'::jsonb, 105),
('週', 'シュウ', NULL, '주(週), 주', 'week', 11, 'N5',
 '[{"word":"今週","reading":"こんしゅう","meaning":"이번 주"},{"word":"来週","reading":"らいしゅう","meaning":"다음 주"},{"word":"先週","reading":"せんしゅう","meaning":"지난 주"}]'::jsonb, 106),
('曜', 'ヨウ', NULL, '요(曜), 빛나다', 'day of the week', 18, 'N5',
 '[{"word":"月曜日","reading":"げつようび","meaning":"월요일"},{"word":"火曜日","reading":"かようび","meaning":"화요일"},{"word":"曜日","reading":"ようび","meaning":"요일"}]'::jsonb, 107),
('体', 'タイ、テイ', 'からだ', '체(體), 몸', 'body', 7, 'N5',
 '[{"word":"体","reading":"からだ","meaning":"몸"},{"word":"大体","reading":"だいたい","meaning":"대체로"},{"word":"体育","reading":"たいいく","meaning":"체육"}]'::jsonb, 108),
('空', 'クウ', 'そら、あ.く、から', '공(空), 하늘, 비다', 'sky, empty', 8, 'N5',
 '[{"word":"空","reading":"そら","meaning":"하늘"},{"word":"空気","reading":"くうき","meaning":"공기"},{"word":"空港","reading":"くうこう","meaning":"공항"}]'::jsonb, 109),
('田', 'デン', 'た', '전(田), 밭', 'rice field', 5, 'N5',
 '[{"word":"田中","reading":"たなか","meaning":"다나카(성)"},{"word":"田んぼ","reading":"たんぼ","meaning":"논"},{"word":"水田","reading":"すいでん","meaning":"논"}]'::jsonb, 110);
